### ISSUE TITLE
Where is the documentation?

### ISSUE THREAD

**Issue by RockGuitarist1** [burtonator/polar-bookshelf#1]
Where is the documentation on how to set this up with an Electron project? I am trying to load a blob into this viewer and can't find any documentation on how to even setup Polar Bookshelf.

EDIT: My blob resides in Electron's main process, so I am expecting something along the lines of creating a new BrowserWindow, but whatever Polar Bookshelf is when you import it and then `PolarBookshelf.loadurl(blob)`?

**Comment by burtonator** [comment]
Polar is not a API... it's a client side app...
