### ISSUE TITLE
Survey pops up every day

### ISSUE THREAD

**Issue by qbatten** [burtonator/polar-bookshelf#1043]
**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

https://opencollective.com/polar-bookshelf

**Describe the bug**
I am asked "how likely are you to recommend polar to friends" every single day. Not sure exactly what the timing is but there's no "dismiss" button so I have to choose a rating basically every time I use the app. I've probably submitted 40 survey results by now.

**To Reproduce**
1. Open app
2. There is a survey in the bottom right corner, even if you've answered it many times.

**Expected behavior**
The survey should only appear once in my usage of polar.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.2
 - Browser N/A, using the app
 - Version 1.19.7

**Additional context**
This happens whether or not I have a cloud sync account; it was happening before I made one and it is still happening now that I have one.

**Comment by burtonator** [comment]
definitely a bug and not supposed to happen that often.
