### ISSUE TITLE
Night mode

### ISSUE THREAD

**Issue by galantra** [burtonator/polar-bookshelf#1056]
**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

https://opencollective.com/polar-bookshelf

**Describe the solution you'd like**
Being able to switch to a dark theme that lenient to the eyes. Preferably, it should feature a shortcut and a different colour for pagemarks (because blue makes one awake).

**Describe alternatives you've considered**
flux has a dark room mode which converts all screen colors. It's very unspecific.

**Comment by burtonator** [comment]
We accept pull requests... it's a frequently requested feature but no on has send a pull release yet ;)

**Comment by burtonator** [comment]
https://github.com/izuzak/atom-pdf-view/pull/178

**Comment by burtonator** [comment]
duplicate of https://github.com/burtonator/polar-bookshelf/issues/280
