### ISSUE TITLE
[Bug] Unable to archive documents on Windows

### ISSUE THREAD

**Issue by baobabKoodaa** [burtonator/polar-bookshelf#1057]
Here is a screenshot of what happens when I try to archive documents. I get both the "success" message and also an error message, and the document appears to be archived, but when I restart Polar, it is no longer archived. I'm glad the web app version of Polar is working, because this makes the **Windows** version of Polar entirely unusable for me. This bug appeared after updating to **1.30.0**.

![alt text](https://i.imgur.com/7fpgcGY.jpg "Logo Title Text 1")

**Comment by burtonator** [comment]
which version of windows?

**Comment by burtonator** [comment]
Good news.. it happens on Linux too ;) ...easy fix!

**Comment by baobabKoodaa** [comment]
Wow, what a fast response :)

**Comment by burtonator** [comment]
Will be fixed in 1.30.1 ... probably out today or tomorrow.

**Comment by baobabKoodaa** [comment]
Probably the same bug, but FWIW: archiving doesn't work in the web version either (no error message, appears to work during the same session, but changes do not persist across sessions).

**Comment by burtonator** [comment]
Should be fixed now if you can confirm.

**Comment by baobabKoodaa** [comment]
Confirmed.
