### ISSUE TITLE
A concern from polar fans

### ISSUE THREAD

**Issue by wzpfish** [burtonator/polar-bookshelf#1062]
Hi, 

I really like your excellent polar-bookshelf. I read many papers using polar and polar is what I'm looking for to read book and paper exactly. 

However, since about 3 months ago, I find that there is a storage limit for free account. I want to upgrade to a payed account but find that it's a little expensive for me. I know the cloud storage may be expensive, but is there any other solutions for somebody like me? For example is there a way to use my own cloud storage like onedrive etc.

And I try to use desktop polar with git sync, but don't find a way to move the documents in cloud to offline.

Now I'm so disappeared and afraid to continue to use polar since if one day my documents touch the limit of free account, I have no way to download my documents and I can't cover the 5$ per month either. BTW, i'm willing to pay if I only need to pay once for the polar not pay by month or year.

**Comment by burtonator** [comment]
Thanks. We're going to have a yearly payment plan option in the next release. It provides 1 month free when you pre-purchase a  year.

We can't do infinite accounts.  It's selling infinite service for a finite amount of money.  :)

I think the per-year option is the best price.  

We'd have to lock you into a major version of polar and I don't think this is a good idea.

**Comment by wzpfish** [comment]
Thanks for your reply. BTW, is there any way to export the documents in polar from cloud to local ?

**Comment by burtonator** [comment]
The desktop client has a full local copy
