### ISSUE TITLE
Huge delay in opening document

### ISSUE THREAD

**Issue by Cupbox** [burtonator/polar-bookshelf#1063]
**Describe the bug**
Polar takes 10-15 minutes to open a document that is heavily annotated. During this time CPU ranges from 12-20%.

**To Reproduce**
Open the file

**Expected behavior**
Open quickly

**Desktop (please complete the following information):**
Windows 10
Firefox
polar-bookshelf-1.30.6

**Additional context**
Document is heavily annotated with images.
Do not have this issue in Polar 1.19.8

**Comment by burtonator** [comment]
Ah... interesting.  That's way way way too long. Is it a PDF?  Would it be possible for you to archive your  .polar dir and send it to me along with the document title?  Once I have that I can probably fix it in 5 minutes.  I think I have an idea what it is...

**Comment by Cupbox** [comment]
Here's a [MEGA](https://mega.nz/#F!u8Q2EYRY!pHT3lOMGpJMPE61_p8KJwQ) with .polar directory.
I removed the rest of the PDF's from the stash folder to reduce the size. 
4b13d32fdd3df7bb3ddc1b0493c7199b is the corresponding directory to the file (which is in itself 1.3 gb due to state.json-xxxxxx files)

**Comment by burtonator** [comment]
k.. it will probably take me a few days to get to it.  I think what's happening is the sidebar might be re-rendering constantly.   I tagged it appropriately so that this gets fixed soon.

**Comment by oparii** [comment]
+1
I have the same problem. After update from 1.19.8 to 1.32.0

**Comment by burtonator** [comment]
The MEGA link above won't download for me.

Can you guys help me out with this issue? I need a .polar directory backed up and saved in a .tar or a .zip and the title of the document that locks up.

You could use:

https://send.firefox.com/

and just paste the link here.

**Comment by oparii** [comment]
I have only one book in the **.polar** directory.
http://ge.tt/64bok1y2

**Comment by burtonator** [comment]
Got it working... sure enough, it locks up!

**Comment by burtonator** [comment]
OK... I think I have a fix now. Will release it in a day or two...

**Comment by burtonator** [comment]
And this is definitely a very slow document to load... need to do a better job with larger documents like this.

**Comment by oparii** [comment]
Thank you for your work!

**Comment by burtonator** [comment]
Just pushed 1.32.14 ... should fix this. Can you guys verify?  Webapp is pushed too.

**Comment by oparii** [comment]
I have the same problem on version 1.32.14

**Comment by burtonator** [comment]
Can you confirm this is fixed so I can close it?

**Comment by oparii** [comment]
In the current version, everything is fine. Thank!
