### ISSUE TITLE
document tools not visible on ipad

### ISSUE THREAD

**Issue by qmztmabxq** [burtonator/polar-bookshelf#1067]
**Describe the bug**
when the contents was selected, the document tools didn't show up, but it work properly on a android phone

**Screenshots**
![微信图片_20190804162307](https://user-images.githubusercontent.com/49702866/62421472-cc64f080-b6d4-11e9-933b-6e1e05dda4c1.jpg)

**Desktop (please complete the following information):**
 - OS: ipad air 3
 - Browser: chrome

**Comment by burtonator** [comment]
That's weird... ok.. The problem is I don't have an ipad to test.  Will have to get one.
