### ISSUE TITLE
Support for split text page mark

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [burtonator/polar-bookshelf#1081]
In the following picture you can see the type of pdf a phd student has to read several times a day :
![Screenshot from 2019-08-31 19-51-27](https://user-images.githubusercontent.com/26625900/64067438-fc41de00-cc17-11e9-83eb-7462c6f190ed.png)
This way of splitting text into two (or more) is not really compatible with the current pagemark system. As you can see the blue pagemark is too wide for the text.

**Describe the solution you'd like**
It's probably not so trivial to code but I think the best way to go about this (and that would be adaptable to virtually any splitting of text) would be to split the "blue zone" in two (or better : in *n* parts) for the whole document.
* Clicking "create pagemark to point" somewhere on the left side would extend the left "blue zone" and fill the progress bar only half of what it would amount to in a non splitted document.
* Clicking the same button on the right side though, would instantly fill the left zone entirely and the right zone to the clicked point.

If you decide to go about this, maybe make it work also for right-to-left text like arabic ?

Thanks for taking the time to read this :)

**Comment by burtonator** [comment]
You can do this now with 'create pagemark box' and then resizing the box.

I agree the UI here should be improved.  It would be nice to automatically detect the page type and number of columns.
