### ISSUE TITLE
Automatically Copy Annotation Text into Cloze Deletion Flashcard upon Creation

### ISSUE THREAD

**Issue by Carrots-N-Peas** [burtonator/polar-bookshelf#1083]
Automatically copying the highlighted text from an Annotation into the Cloze-Deletion flashcard for it would be really helpful reducing the time/clicks it takes to make flashcards for a document.

Currently, the workflow for creating a cloze-deletion flashcard is as follows:
1) Highlight PDF
2) Click on "Create Flashcard" on annotations sidebar
3) Go to the annotation to copy the text
4) Paste the text into the flashcard
5) Create the Cloze-Deletions
6) Publish the card

The feature I am proposing would cut out steps 3 and 4 because the text would automatically appear in the Cloze-Deletion card:
1) Highlight PDF
2) Click on "Create Flashcard" on annotations sidebar; text automatically appears in the textbox for the flashcard
3) Create the Cloze-Deletions
4) Publish the card

**Comment by burtonator** [comment]
Could we have it more along the lines of a button (which could have a key binding) to copy it over?

Here's what needs to change for this to happen:

web/js/annotation_sidebar/AnnotationControlBar.tsx

web/js/annotation_sidebar/child_annotations/flashcards/CreateFlashcard.tsx

I'm not 100% certain having the flashcard filled out by default is a good idea but I'm open-minded.  

I guess the user could delete the data anyway... I think this makes MORE sense with cloze ... does it not? 

What needs to happen is that the annotation text would need to be passed to CreateFlashcard which will then pass it to FlashcardInput which will then need to pass it to FlashcardInputForCloze then RichTextArea...

One BIG issue though is images.  Right now we would have to convert these to data URLs but I want to migrate these to URLs in the cloud.  I'd need to give you an API for automatically doing that.  

For now, we would have to strip the <img> and then fix that in the future. 

In the future we might be able to make this a pref.

**Comment by Carrots-N-Peas** [comment]
Thank you for responding!  I do think that a button or checkbox (so it automatically happens only when the checkbox is ticked) would be a better solution!  I do think it makes more sense for Cloze than Front-Back cards as well.  The image thing does sound like a problem; although I think that the solution you outlined should work for the majority of cases for now.  Once again, thanks!

**Comment by burtonator** [comment]
re-opening as this isn't fixed yet.
