### ISSUE TITLE
Internal Error On Launch When Building From Source 

### ISSUE THREAD

**Issue by Carrots-N-Peas** [burtonator/polar-bookshelf#1084]
**Describe the bug**
Upon running the `npm run-script compile && npm start` command (after cloning the respository and running `npm install`), a window with the Polar Bookshelf logo and toolbar appears, but I get the an "Internal Error" message on the main window and cannot actually interact with the GUI beyond interacting with the toolbar.

![2](https://user-images.githubusercontent.com/54776368/64083071-f4993c80-ccde-11e9-9431-a5b3746d92e4.png)

![1](https://user-images.githubusercontent.com/54776368/64083072-f95df080-ccde-11e9-8eb0-fb91f707443c.png)

**To Reproduce**
1. Download git from https://git-scm.com/
2. Download node.js from https://nodejs.org/en/download/
3. Follow instructions on Polar Bookshelf github
`$ git clone https://github.com/burtonator/polar-bookshelf`
`$ cd polar-bookshelf`
`$ npm install && npm run-script compile && npm start`
4. The window will appear at this point

**Expected behavior**
Polar Bookshelf starts like like it normally does.
![image](https://user-images.githubusercontent.com/54776368/64083115-84d78180-ccdf-11e9-9eca-a778859a7b30.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bit

**Additional context**
I can run the Polar Bookshelf exe downloaded from the website.  However, I'd like to be able to build from source to hack it and perhaps help in development!

**Comment by burtonator** [comment]
Go to Tools | Javascript Console and what error does it show?

**Comment by burtonator** [comment]
git pull and compile again. I think I fixed it. I'm landing some important changes and usually head is stable but some key things are changing.

**Comment by Carrots-N-Peas** [comment]
I pulled the updated repo and went through the same instructions and it worked!  Thank you!
