### ISSUE TITLE
Delete account

### ISSUE THREAD

**Issue by ldexterldesign** [burtonator/polar-bookshelf#1085]
Username: getpolarized.io@ldexterldesign.uk

Hi,

Hope you're well

Thanks for software but I've found something else that better meets my needs and want to delete my account - how do I do this?

Unless I've missed it a "delete account" feature should exist

If you have any issues (e.g. questions/queries) then happy to help

Look forward to reply

Yours faithfully

**Comment by burtonator** [comment]
Great... I"ll take care of it.  This is a feature we're going to add soon as well as purging all your data.

**Comment by ldexterldesign** [comment]
My account is not deleted and I can still login?

Cheers

**Comment by ldexterldesign** [comment]
What's my account status please - when I attempt to login I see a "network error" which isn't very informative?

Thanks

**Comment by ldexterldesign** [comment]
BUMP

**Comment by ldexterldesign** [comment]
BUMP

**Comment by thiswillbeyourgithub** [comment]
I had to create multiple accounts to get rid of a bug and I would appreciate being able to terminate them too. Also can we leave groups ?

**Comment by ldexterldesign** [comment]
BUMP
