### ISSUE TITLE
Checksum for all windows binaries

### ISSUE THREAD

**Issue by linsui** [burtonator/polar-bookshelf#1087]
There is sha512 in latest.yml but only for nsis-1a32, could you please provide checksum for nsis-x64 and portable-x64?

**Comment by burtonator** [comment]
I didn't change anything... did this break anything for you?

**Comment by burtonator** [comment]
And where are you seeing the checksums? I can't find them

**Comment by linsui** [comment]
https://github.com/burtonator/polar-bookshelf/releases/download/v1.32.0/latest.yml

This file contains a sha512 checksum in base64 format, but only for ia32. I'd like to install polar with [scoop](https://github.com/lukesampson/scoop) and it would be great if I can extract checksum from upstream. Thanks anyway!

**Comment by burtonator** [comment]
Gotcha. I won't have a short term fix for this unless I ditch ia32 I think.  The challenge is that the LAST build overwrites this file and for various reasons, I have to build each windows platform individually for now.

**Comment by linsui** [comment]
Thanks anyway! :smile:
