### ISSUE TITLE
This state freezes the document. It is stuck on loading.

### ISSUE THREAD

**Issue by Rumata888** [burtonator/polar-bookshelf#1088]
https://send.firefox.com/download/39124073df69bb94/#2kXiNZ0B4eRLAx4HPZmU0w
This state doesn't allow me to work with the document.

**Comment by burtonator** [comment]
Can you get me the doc (PDF or PHZ) file too?  With those I can fix it easily.

**Comment by Rumata888** [comment]
https://bit.ly/2m6nEQl
Sorry for ads, I can't upload it personally.

**Comment by Rumata888** [comment]
Any luck?

**Comment by Rumata888** [comment]
Actually, it seems I was wrong. It just takes a huge time to load, but eventually it does load.

**Comment by burtonator** [comment]
Is this fixed now?  I'd like to close this issue.

**Comment by Rumata888** [comment]
Yes. It now takes just 15 seconds to load.
