### ISSUE TITLE
Comments are not saved in group document

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [burtonator/polar-bookshelf#1097]
**Describe the bug**
When I am annotating a pdf document on Polar and adding comment to an annotation, it is not saved when closing the winow although new annotations are saved.
I am using online syncing.

It happens in group synced documents as well as personnal documents.

**To Reproduce**
1. Open document
2. choose a new or old annotation
3. add a comment to it
4. close and reopen document
5. notice the comment is gone

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
- Polar version : 1.32.29

Let me know if I can provide any kind of logs. There doesn't seem to be anything of use in the regular logs

**Comment by burtonator** [comment]
In groups?  Groups are still beta but I agree this needs to be fixed.

**Comment by thiswillbeyourgithub** [comment]
I noticed this while reading a doc in groups but it happens too in not grouped

**Comment by burtonator** [comment]
Thaniks. I'm going to do another push and revert a change I recently made.

**Comment by thiswillbeyourgithub** [comment]
This indeed fixed the issue. The comments I added previously now all appear so they were not "not saved" but just not displayed. I'll let you close the issue if you deem it necessary, thanks for the super quick help :)

**Comment by burtonator** [comment]
Great.. thanks for confirmation.  And sorry this bit you. Normally we're more stable than this but both bugs sort of snuck up and we had to get them fixed.
