### ISSUE TITLE
[error] [1.32.29] [PersistenceLayers.js] Unable to sync between source and target:

### ISSUE THREAD

**Issue by jgwill** [burtonator/polar-bookshelf#1098]
**Describe the bug**

Error on loading.  Getting [error] [1.32.29] [PersistenceLayers.js] Unable to sync between source and target:

**To Reproduce**
1. Happened after Polar updated

**Expected behavior**
Normal working condition

**Screenshots**
![image](https://user-images.githubusercontent.com/23141173/65159833-adab8680-da02-11e9-9c44-ed1e78798929.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.32.29

**Additional context**

**Comment by burtonator** [comment]
Thanks. Working on fixing this.  It has nothing to do with Polar but is an issue with our Firebase cloud backend.

We have a quota exceeded issue but we don't have a quota... so trying to debug whats happening here.
