### ISSUE TITLE
Opening a pdf from repo view results in error

### ISSUE THREAD

**Issue by fonol** [burtonator/polar-bookshelf#110]
If I open a document from the repo view, I get an "invalid or damaged file" (translated from german)  error.
'More details' on the error only shows this:
PDF.js Version 2.0.511 (build: 70cad2f0)
Nachricht: Invalid PDF structure

No more errors shown in the console, only "invalid or damaged file".
Tested with three files.
(Windows 10, 64bit)

**Comment by burtonator** [comment]
OK.. great feedback. I'm going to try to fix this ASAP.. I'm also going to implement the crash reporter today to help capture these  in the wild.

It must not be able to load it over HTTP properly.  

Ich sprache Deutsceh auch :)

**Comment by burtonator** [comment]
I actually think this is already fixed .  Bad bug for first experience though bug should be resolved in the next release.
