### ISSUE TITLE
My pdf change it orientation

### ISSUE THREAD

**Issue by LuisReinoso** [burtonator/polar-bookshelf#1112]
**Describe the bug**
I was using polar when I pressed some keys accidentally I don't remember what they were, then my pdf orientation change to horizontal.

**To Reproduce**
Sorry I can't reproduce it again. I pressed some keys accidentally.

**Expected behavior**
I would like to revert to original orientation (vertical)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.32.32

**Additional context**
Is there any shortcut to change the pdf orientation.?
Thanks

**Comment by LuisReinoso** [comment]
Finally I have found the shourtcut 
- rotate the document clockwise: <kbd>r</kbd>
- rotate counterclockwise: <kbd>shift</kbd> + <kbd>r</kbd> 

Related #781

**Comment by vikaskyadav** [comment]
big Thanks @LuisReinoso . :+1:
