### ISSUE TITLE
Importing certain PDFs results in other PDFs auto-opening, import failure

### ISSUE THREAD

**Issue by brp-optics** [burtonator/polar-bookshelf#1123]
Thank you so much for your creation of Polar. It is truly the best way to annotate PDFs.

In the past three days, I have discovered two PDFs that, whether imported via drag-and-drop or via the file menu, both failed to appear in the document repository. 

Instead, an already-imported PDF with a different filename and different content (the last active file?) appears in a new annotation window.

The error still appears if I change the filename, but other PDFs work, so it appears to be due to the specific PDF's content. Printing the PDF in Adobe Reader to a new PDF file (via a non-Adobe  print-to-PDF utility) creates a new PDF file which is then importable.

Printing both problem PDFs to involved a lengthy "flattening" process in Adobe Reader, and the printed files are much larger than the originals. Is Polar perhaps having a problem with heavily layered / compressed PDFs?

1. Click on "Add files from disk"
2. Select one of the two problem PDFs attached.
2. Wait until new window pops up.

Expected behavior:
The PDF should import successfully and appear in the new window, or an error should appear that the PDF import failed, and a new window should not appear. It would be best if the error window had a suggestion for workarounds.

Desktop:
 - OS: Windows 7 SP1
 - Browser: Chrome 77.0.3865.90, but not really relevant to this bug.
 - Polar Version: 1.32.32

Attachments:
((***Links removed***))

**Comment by burtonator** [comment]
... I have a branch that fixes this and will try to fix it soon. In the meantime, you might be able to fix it by printing the PDF to a new PDF file and importing that.

https://github.com/burtonator/polar-bookshelf/issues/1075

https://github.com/burtonator/polar-bookshelf/issues/1010

https://github.com/burtonator/polar-bookshelf/issues/439

**Comment by guttenberger** [comment]
Is there any other workaround for this? I can't select text inside of the printed pdf. I am using Adobe Acrobat Reader DC.

**Comment by burtonator** [comment]
@guttenberger the issue is in Acrobat Reader DC..  It's printing your doc as an image.  

Try with Preview on MacOS or another PDF viewer.
