### ISSUE TITLE
Initial help-walkthrough is bugy

### ISSUE THREAD

**Issue by AnjunaGlobal** [burtonator/polar-bookshelf#1138]
**Describe the bug**
I just downloaded polar and ran it for the first time on macOS. The "walk you through onboarding" seems broken.  I accidentally mis-clicked when it asked me to open the sidebar, then the polar main UI window went blank. I quit and restarted, and this time the highlighting was out of sync with the walk-through.  

**To Reproduce**
1. Do a fresh install of polar on macOS
2. Monkey-click or misclick during on boarding screens

**Screenshots**
[
![Screen Shot 2019-10-17 at 8 49 46 AM](https://user-images.githubusercontent.com/23359753/67010506-c23f7500-f0bb-11e9-8219-2ca80b271b18.png)
](url)

**Desktop (please complete the following information):**
 - OS: macOS

**Comment by burtonator** [comment]
oh jeez... so sorry! Thanks for the help... I'm going to rework the onboarding soon so will take a look at this!

**Comment by AnjunaGlobal** [comment]
Cool.  Also there was a "would you recommend Polar" popup in the desktop app.  Clicking on the buttons had no effect for several clicks. :)
