### ISSUE TITLE
npm install on ubuntu results in polar-content-capture not found

### ISSUE THREAD

**Issue by shubhamjain0594** [burtonator/polar-bookshelf#1140]
I am interested in contributing to Polar. So I tried clone and installing libraries manually. It gave me an error 

```sh
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/polar-content-capture - Not found
npm ERR! 404 
npm ERR! 404  'polar-content-capture@^1.32.53' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'polar-bookshelf'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**To Reproduce**
1. Clone the repo
2. Run npm install

**Expected behavior**
Clean install.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shubhamjain0594** [comment]
Also, proper documentation on how to contribute would help a lot.

**Comment by burtonator** [comment]
@shubhamjain0594 agreed... I'm in the process of refactoring the way we do builds so things will probably be a bit messy for another week. I'll try to fix this shortly.
