### ISSUE TITLE
Next polar tags in Anki

### ISSUE THREAD

**Issue by danielzfranklin** [burtonator/polar-bookshelf#1142]
**Is your feature request related to a problem? Please describe.**
When I look at the tags sidebar in Anki, I see a lot of noise (picture).
<img src="https://user-images.githubusercontent.com/10361846/67124262-bd74e100-f1e1-11e9-9dff-94729277677a.png" height="400px">

**Describe the solution you'd like**
I use an Anki addon called BetterTags that allows hierarchical tags (picture). I would like it if Polar nested the tags it outputs.
<img src="https://user-images.githubusercontent.com/10361846/67124450-0dec3e80-f1e2-11e9-8155-d26f8bed9d71.png" height="350px">

**Describe alternatives you've considered**
Ignoring the noise isn't a huge deal but is non-ideal.

**Additional context**
BetterTags nests on "::", just as vanilla Anki does for Deck names. Specifically, I'd like Polar to output "polar_guid::{guid}" instead of "polar_guid:{guid}," and I'd like Polar to replace "/" with "::" in the Anki tags created from Polar tags so that tags that are hierarchical in Polar are hierarchical in Anki.

Anki users without the addon will see a tiny bit more noise, and users with the addon will have a much better experience.

**Comment by burtonator** [comment]
I think this will be obsolete in the future.  We're going to migrate to a strategy where we don't need to use these tags at all.

**Comment by danielzfranklin** [comment]
Great to hear
