### ISSUE TITLE
Make annotations searchable within annotations sidebar.

### ISSUE THREAD

**Issue by thorgas** [burtonator/polar-bookshelf#1148]
**Is your feature request related to a problem? Please describe.**
When opening a pdf and making annotations, the annotations are not searchable.

**Describe the solution you'd like**
Integrating a kind of search functionality  for annotations, like the search functionality for documents (pdf)

**Comment by burtonator** [comment]
oh.. you mean filtering / searching *within* the annotation sidebar?
