### ISSUE TITLE
Filter the annotations view by type of card or color

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [burtonator/polar-bookshelf#1149]
**Is your feature request related to a problem? Please describe.**
It would be great to be able to speed read only a specific color of a document. So showing only the red highlights for example. It would be useful both in the main view panel as well as the annotation pannel.

**Comment by burtonator** [comment]
ok.. you mean a filter to only show a specific color of annotation?  another user suggested to have a filter in the annotation view of annotation type (comment, flashcards, highlights, etc).

I think filtering in both the annotation sidebar and the main annotation viewer are good ideas.

**Comment by thiswillbeyourgithub** [comment]
Yes, allow for filtering in the annotation sidebar and/or main view + filter by color or type (comment, flashcard etc)
