### ISSUE TITLE
[URGENT/regression ?] annotation sidebar disappeared since last update

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [burtonator/polar-bookshelf#1153]
Hi,
not to sound alarming or anything but ever since the upgrade to 1.40 yesterday I can't see the annotation bar, nor add highlights (selecting text with the mouse cursor doesn't add the color selector).

I don't see anything interesting in the log of the app.

OS : ubuntu 18.04
polar : 1.40.1

**Comment by burtonator** [comment]
Thanks.. this is the bar that you get when you select text ? correct? 

snap or deb build? Are you using cloud sync?  Let me know and I"ll check.. I definitely don't see this issue and I"m on ubuntu.

**Comment by thiswillbeyourgithub** [comment]
> this is the bar that you get when you select text
correct.

snap, using cloud sync. 

The problem is still here. I also don't see anything when right clicking.

**Comment by thiswillbeyourgithub** [comment]
If there is nothing new, I will reinstall in a few days.

**Comment by thiswillbeyourgithub** [comment]
I have reinstalled polar while keeping my snap folder and the issue remains.
I have then tried to open polar after having removed the 'current->75' folder inside snap/polar-bookshelf and it opens a fresh install of polar with the default pdf *and a working annotation bar*.

The diagnostic seems clear : something inside my 'snap/75/' folder is stopping Polar from launching it's annotation bar. What should I do ?

**Comment by thiswillbeyourgithub** [comment]
Fixed. I removed the content of "snap/current", launched Polar to repopulate the folder, then replace the whole ".polar" with a backup from the previous version.
