### ISSUE TITLE
Open source Polar web

### ISSUE THREAD

**Issue by lyz-code** [burtonator/polar-bookshelf#1155]
Hi, first of all thanks for the awesome program.

I was wondering if you plan to open the source of the webserver and document how to install it.

I'd love to self host an instance for my company as for security reasons we can't use external services.

(I've searched through your repositories and docs and found nothing related, sorry if it's there)

**Comment by burtonator** [comment]
It's all based on firebase so by definition it's outside of the firewall.

**Comment by douglasg14b** [comment]
Oh, that's a shame it's trapped in the Firebase ecosystem. Pretty much always guarantees a $$ figure exists to use it.

This would be a great option for self-hosting otherwise.
