### ISSUE TITLE
Add tags to annotations ?

### ISSUE THREAD

**Issue by bepolymathe** [burtonator/polar-bookshelf#1169]
Hello,

I am currently testing in Polar production as part of a new research project. It is an excellent tool to organize your documentation and keep your annotations... but perhaps it could do even more. 

What would you think of the idea of adding the possibility of keywords to the annotations themselves? The interest would be to be able to do the first phase of the work of a QDA software (search by combination of tags). This would allow searches that combine document keywords and annotation keywords.... 
We could even consider then exporting tag connections in an open format (.csv for example). 
What do you think of that?
Regards

**Comment by thiswillbeyourgithub** [comment]
Not the dev but I think it's the reason there are several colors of annotation. Ideally you can : 
* select which color the annotation should be in -> already available
* select which color to display in the main view or annotation bar (= only display the colors of interest) -> I made an issue asking for this
* the ability to export and import annotations -> I made an issue too. This allows to do what you want with the data and explore any connection you want

Or I misread your proposal and then just ignore me

**Comment by bepolymathe** [comment]
Thank you for that reaction. 

This could be a first step in "playing" with color codes. But I think we could go further. Let us give an example.  A sociology student wants to analyze the interviews he conducted as part of his thesis. It can transform interview transcripts into.pdf to annotate them (while waiting for the possibility to import".docx" or".odt"?). He can give each of the files a tag to characterize the person ("woman", "30-40 years old", "employee", etc.). When he reads the interview, he will make annotations according to the interest he finds in the annotated passage. What is important in his research work process is that he can document the reasons why he is interested in this quote. Currently, he can post a comment. To find this comment (when he has 10,000!), he has to search by the "tag" of the document or by the content of the comment (annotation panel)... the problem is that he can't remember who told him that, with which words and what he wrote in the commentary... but if he could have said that this extract had a tag "related to hypothesis 1" or "subpart 2.3"... he might have found it!

So yes, he could imagine the categories of annotation by colors but that would currently mean that he is only allowed 15 categories (number of colors currently available). 

In addition, if he had annotation tags, he could search by "woman" + "related to hypothesis 1" (+ colors why not) to obtain combinations of characteristics that will improve research and analysis.
I don't know if anyone else would be interested?

**Comment by thiswillbeyourgithub** [comment]
A currently working solution could then be to add at the end of each comment a list of keywords.

Example : the woman in the interview is making reference to hypothesis A and is a woman
the comment could be
> whatever
comment over
several lines
#woman #relatedToHypoThesis1

This way he just has to search for "#woman" right ?

**Comment by bepolymathe** [comment]
In the idea it would solve the problem of searching for the citation but not necessarily other uses. 

If the student wants to be able to work on occurrences and relationships in another software, it would be nice if he could export this information to a database (json or sqlite)or spreadsheet (.ods ou .csv) for example. In this case, it seems to me that the annotation tag category should be a separate entry. 

Let's @burtonator react to this discussion maybe?

**Comment by burtonator** [comment]
This is already on the agenda and we have some of the backend changes for this already done.  It has a 'usability' tag which is what I'm using for valuable features you guys suggest that are slated in the short term. 

I'm working on a Polar 2.0 release which improves mobile and implements spaced repetition and this is taking up all my time now but I think this will make it in shortly.  

I want to do 1-2 releases that just focus on usability issues you guys have requested once 2.0 is out.

There is more here:

https://www.reddit.com/r/PolarBookshelf/comments/douepc/feedback_proposal_for_colors_and_icons_for_tags/

**Comment by bepolymathe** [comment]
Well, that's great news !

**Comment by burtonator** [comment]
Make each annotation selectable, navigable, so that I can also have key bindings for this when active.
