### ISSUE TITLE
Zooming long pdf pages past 110% creates unusable lag.

### ISSUE THREAD

**Issue by modemenusource** [burtonator/polar-bookshelf#1174]
**Describe the bug**
Desktop Polar app starts to lag when a long PDF page is zoomed.

**To Reproduce**
Take a PDF with long pages  (I have provided an example below), and zoom in past 110%.

**Expected behavior**
Self explanatory, I want it to not become unusable by zooming in too much.

**Desktop (please complete the following information):**
 - OS: Windows 10 1903

**Additional context**
You can find a test PDF here:
[linearna-2018-11.pdf](https://github.com/burtonator/polar-bookshelf/files/3813888/linearna-2018-11-web_unlocked.pdf)

**Comment by burtonator** [comment]
Interesting... will take a look soon.

**Comment by modemenusource** [comment]
Appears to be fixed, thanks!
