### ISSUE TITLE
Bookshelf View with a progress bar at the bottom of PDF front page

### ISSUE THREAD

**Issue by cricrazy** [burtonator/polar-bookshelf#1175]
**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

https://opencollective.com/polar-bookshelf

**Is your feature request related to a problem? Please describe.**
The interface is very clean and nice. But it is at time difficult to scan through your list, if you have lots of PDF. 

**Describe the solution you'd like**
It would be awesome to have a bookshelf view with the progress bar at the bottom to show your incremental reading status.

**Describe alternatives you've considered**
Apple's iBook bookshelf view provides a quick and easy way to look at all your documents. Something similar would be awesome. 

**Additional context**
See attached screenshot.
![iBook](https://user-images.githubusercontent.com/4622816/68489532-e4d13380-020c-11ea-925d-1b50b7779ac0.jpeg)

**Comment by burtonator** [comment]
It's on the agenda .. .probably 2-4 weeks or so away.
