### ISSUE TITLE
Ability to hide pagemarks

### ISSUE THREAD

**Issue by alum** [burtonator/polar-bookshelf#1183]
**Is your feature request related to a problem? Please describe.**
When studying a textbook I want to keep track of what I've read but I also want to re-read sections and look things up. When re-reading sections which has a "read" pagemark there is a translucent turquoise overlay that annoys me.

**Describe the solution you'd like**
Allow me to hide/show pagemarks by clicking a button / keyboard shortcut.

**Describe alternatives you've considered**
Pagemarks could have custom colors, but it could still be annoying.

**Comment by burtonator** [comment]
Working on it and should/could be in the next version...   I want to be able to better support keyboard bindings first.
