### ISSUE TITLE
Double-click to edit annotation comment

### ISSUE THREAD

**Issue by alum** [burtonator/polar-bookshelf#1188]
**Is your feature request related to a problem? Please describe.**
I want to quickly edit comments. Now I need to click the small edit button which requires too much fine motor skills for my taste :)

**Describe the solution you'd like**
Double-click the text of a comment enables the comment editor.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by burtonator** [comment]
interesting idea... I'll look into this and see what other platforms do...  I'm working on extended key bindings.

**Comment by burtonator** [comment]
implementd for comments and flashcards in the next release
