### ISSUE TITLE
Document Repository bar unavailable on Android chrome

### ISSUE THREAD

**Issue by Rumata888** [burtonator/polar-bookshelf#1193]
**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

https://opencollective.com/polar-bookshelf

**Describe the bug**
It seems polar defaults to annotations, when trying to go to document Repository, when accessing it from chrome on Android

**To Reproduce**
Go to app.polarized.io in chrome on Android. Desktop site feature should be disabled. Try to switch to document Repository

**Expected behavior**
A switch to document list

**Screenshots**
![Screenshot_20191112-231235](https://user-images.githubusercontent.com/4798775/68707405-be135400-05a2-11ea-99fd-9e9f29fedae6.jpg)

 - OS: Android 9
 - Browser chrome
 - Version 78.0. something

**Additional context**

**Comment by burtonator** [comment]
OK... so the problem is that the tabs are enabled. 

The idea, for now, is to disable polar document management on android/iOS until it works properly without any bugs.

**Comment by Rumata888** [comment]
Will I be able to access my documents? Right now I can't do it in chrome.
