### ISSUE TITLE
The windows store app hasn't been updated since v1.16.4

### ISSUE THREAD

**Issue by nimarb** [burtonator/polar-bookshelf#1194]
**Describe the bug**
The windows store version of Polar hasn't been updated beyond v1.16.4

**To Reproduce**
1. Go to the windows store
2. Download Polar
3. Launch it

**Expected behavior**
See a version which is somewhat recent, e.g. 1.4X

**Desktop (please complete the following information):**
 - OS: Windows 10 1903

**Comment by burtonator** [comment]
Thanks... I'll have to do a release there.  Long story but it's a real pain to do a release.  There were only 5 users so I haven't been updating it.
