### ISSUE TITLE
cannot stop sharing : "unable to handle RPC:groupMemberDelete"

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [burtonator/polar-bookshelf#1196]
**Describe the bug**
* I have been trying to make group sharing work for a while now but something appears broken and I'd like to stop sharing the document.

* The current state of the document is that it is not sharing with my friend even though it should be, I get this error every few minutes : "Unable to sync between source and target". It also appears in the log.

* I decided to try to reset the situation by clicking on the bin icon next to the name of my friend in the document view (in the share submenu, top right corner) and I get "unable to handle RPC:groupMemberDelete" which does not appear in the log.

* What should I do ? This has been the case for a few weeks now. I waited for a few updates hoping it would be fixed eventually.

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04
 - Version : 1.50.10

Additional infos : I wanted to log on the webapp to see if that could make a difference. I then saw that my pdf had not been synced for a long time, while other had been synced fine. There was a kind of duplicate of my pdf (called a.pdf, that I think got created when I tried to use groups a while back) that I then deleted on the web app. I then propagated to my snap app where my actual annotated pdf was deleted, so I restored it manually from a backup and resyced. I am waiting for it to propagate on the webapp because so far it has not reappeared. My snap app still has the issue with stopping the sharing.

**Comment by burtonator** [comment]
Ah.. you're right.  Thanks for reporting this.  We should have a fix for this shortly.

We're going to back out groups until it's very solid and instead make it a preview feature which will have to be enabled by users.

I want the existing feature set to be very solid for 2.0

**Comment by burtonator** [comment]
k... I think I have a fix for this and will try to push it soon.

**Comment by thiswillbeyourgithub** [comment]
Great, thanks ! Will try to report sooner next time :)

In the meantine, before fixing the group function I still think that allowing for importing the exported annotations would be a good workaround for some people (including me) :) It looks orders of magnitude easier to add than to fix groups if you ask me ^^

Anyway thanks a lot for the terrific job ! So excited for this release !

**Comment by burtonator** [comment]
Oh.. you mean when you manually export your annotations via the annotation sidebar?  There's already a bug for this noting that it's kind of confusing.  

I'm going to work on 'backups' and external snapshots for "just in case" situations and the ability to re-import but it will be slightly different.

**Comment by thiswillbeyourgithub** [comment]
Is it planned to add a "force syncing one way next time" like in anki ? I feel it can be useful when people use Polar across multiple devices and messed up at some point.
