### ISSUE TITLE
ability to delete flashcards/annotations from the annotation "window"

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [burtonator/polar-bookshelf#1197]
**Is your feature request related to a problem? Please describe.**
I have annotations, flashcards and empty comments that do not appear in the annotation panel (inside the document window), so I can't delete them.

**Describe the solution you'd like**
I think it would be great to allow deleting this things from the annotation window (when you click annotations on top, not when reading the doc) and it would allow me to remove my problematic one too.

**Describe alternatives you've considered**
Nothing seems possible

**Additional context**
Also, why clicking on the document's name in the annotation window opens the doc but is not already scrolled into view ? That would seem more intuitive to me.

**Comment by burtonator** [comment]
> I have annotations, flashcards and empty comments that do not appear in the annotation panel (inside the document window), so I can't delete them.

They're associated with the document but you don't see them on the document? That's a bug in and of itself.

> I think it would be great to allow deleting this things from the annotation window (when you click annotations on top, not when reading the doc) and it would allow me to remove my problematic one too.

Deleting, editing, etc will be coming soon.  Same for making changes while reviewing flashcards.

> Also, why clicking on the document's name in the annotation window opens the doc but is not already scrolled into view? That would seem more intuitive to me.

Yes... this is another bug/feature that we should be fixing.  I think we might already have a fix for this and will investigate.  The challenge though is that we should be improving the UI for this so it's more clear that you're scrolling and selecting a specific annotation.
