### ISSUE TITLE
Expand/collapse folders doesn't update display

### ISSUE THREAD

**Issue by sopoforic** [burtonator/polar-bookshelf#1210]
On Windows 10, Polar v1.50.10, expanding and collapsing folders does not update the display. However, the expand/collapse action *is* taking effect behind the scenes, because selecting a folder as a filter causes the display to update and show the changed collapse state. A demonstration of the effect:

![2019-11-17_12-17-44](https://user-images.githubusercontent.com/78205/69011106-ccf85e80-0934-11ea-9add-22153ad673bb.gif)

**Comment by burtonator** [comment]
Thanks... Will try to fix this soon.  These types of bugs I try to prioritize.
