### ISSUE TITLE
Annotation sorting by color

### ISSUE THREAD

**Issue by jgwill** [burtonator/polar-bookshelf#1216]
**Is your feature request related to a problem? Please describe.**
I want to choose specific meaning for colors and now all of them at the same time in the viewer mean nothing.

**Describe the solution you'd like**
Ability to sort and view one color by choosing it from a top menu in Annotation.

**Describe alternatives you've considered**
From a color label you have an submenu "View all from this color"

**Additional context**
Building a research reading annotation that mean something :)

**Comment by thiswillbeyourgithub** [comment]
For the record, this seems to be what I suggested in #1149, it looks very useful to me

**Comment by jgwill** [comment]
Indeed #1149  sounds you got one more element than I for the feature request :)    I guess it means this could be closed as it is a duplicate feature request ;)
