### ISSUE TITLE
Export all annotations at once

### ISSUE THREAD

**Issue by ucn** [burtonator/polar-bookshelf#1224]
It would be quite a nice feature to export all annotations at once instead of having to open every pdf file, clicking “Export“ and then choosing a destination for a file. Add a button at the annotations tab like “Export all“, then having to choose a destination for the files and all exports would be done at once.

**Comment by burtonator** [comment]
What's the desired goal? Backup, sharing with other people ?

**Comment by ucn** [comment]
Yes, Backup as well. But my use case is that I use Polar as kind of a citation manager. I highlight the text that may be important enough to quote in my paper. As I have more than 50 pdfs and in each one of them I have ten or more highlights, searching through them by using the Polar Annotation tab is possible but quite unhandy. Therefore I want to export the highlights and search through them in my text editor or even print them to look through them.

**Comment by burtonator** [comment]
You can export to markdown.  The export framework is super simple if you wanted to add a new format or extend one.

What features did you need in the annotation repo to make it usable for searching?

**Comment by burtonator** [comment]
Oh... you just want them ALL exportable at once... meaning everything in the current annotation repository view? AKA not just on a per-document basis.

**Comment by ucn** [comment]
> Oh... you just want them ALL exportable at once... meaning everything in the current annotation repository view? AKA not just on a per-document basis.

Yes exactly this!
Clicking through 50 and more files to export the annotations would be a hassle. I would appreciate it if there would be an “export all“-button in the annotation tab which would deliver me the exported annotations for all documents.

**Comment by burtonator** [comment]
Might be in the next release but no promises ;)

**Comment by burtonator** [comment]
Will ship in the next release

**Comment by ucn** [comment]
Thank you very much! Keep going, I use Polar a lot and I appreciate all the work you’ve done!
