### ISSUE TITLE
can't access logs on the web app

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [burtonator/polar-bookshelf#1225]
**Describe the bug**
As my web app has not been working well for the past 13 days (annotations and documents are still not imported) I tried to access the logs on the web app.

It looks like this on a fresh install of firefox :
![Screenshot from 2019-11-26 14-14-59](https://user-images.githubusercontent.com/26625900/69636628-edb86680-104e-11ea-9f55-3ebc6b9995c4.png)

Clicking on "copy to clipboard" copies this string : 'bracketed-paste-magic:zle:47: not enough arguments for -U'. I don't know if it's relevant.

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04
 - Browser Firefox
 - Version 70.0.1

**Comment by burtonator** [comment]
"As my web app has not been working well for the past 13 days (annotations and documents are still not imported)" . 

... you mean app.getpolarized.io ?  

What do you mean they are not imported?  Can you explain in more detail?

**Comment by thiswillbeyourgithub** [comment]
I already sent you an email asking you if you could delete all remote data of my account as I think it could solve a lot of issues I had. Do you want to continue via email or github ?
