### ISSUE TITLE
Document rotated

### ISSUE THREAD

**Issue by LowellChristie** [burtonator/polar-bookshelf#1226]
One of my documents suddenly rotated 90 degrees and became unusable in the Windows 10 desktop application.   I've deleted and reloaded the pdf file, uninstalled and re-installed Polar, looked through help screens and tried all of the possible menu items. I can't seem to reverse whatever happened. The file loads correctly in Acrobat reader, AND can be loaded correctly in the Chrome web version of Polar.  An error message appears in the desktop version saying "An Internal Error has occurred."
Just started using the program this week and would like to continue, but not unless this can be solved.  (Image below)
Lowell Christie
lowell.christie@gmail.com
![Polar Problem](https://user-images.githubusercontent.com/58231947/69672566-3a02a700-104d-11ea-9d43-858cb1907c92.png)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by thiswillbeyourgithub** [comment]
related to issue #1112

**Comment by burtonator** [comment]
Sorry... hit 'r' in the document viewer.  I agree it's annoying.  I'll try to see if I can implement a workaround...

**Comment by burtonator** [comment]
This is an effective fix:

```javascript
document.getElementById("outerContainer").addEventListener("keydown", event => {
    if (event.key === 'r') {
        event.stopPropagation();
        return false;
    }
});


```

... I will add this to the next release.

**Comment by thiswillbeyourgithub** [comment]
I think it might be useful to allow rotating. 

What do you think of this : adding a button in the system menu to rotate

This solution would still allow : 
* people to rotate the document if need be
* it would also not force you to edit the doc to remove all mentions of the rotation
* people who accidentaly rotated their document will probably check first in the system menu so they could fix their problem

maybe remove 'r' shortcut and adding this option in the system menu would be even better ?

**Comment by LowellChristie** [comment]
I knew it would be simple when I finally learned it.  Adding a menu item
(R=Rotate) would probably be the easiest fix..Really liking the program.

**Comment by burtonator** [comment]
The issue with keeping rotation (for now) is that all annotations would break.  

Just disabling this is probably the best bet for now.

**Comment by burtonator** [comment]
Will be fixed as per the next release.  Thanks!
