### ISSUE TITLE
unable to sync between source and target

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [burtonator/polar-bookshelf#1229]
**Describe the bug**
My most important pdf has been very buggy for a while for reasons I can't recall probably related to the alpha version of groups. I exchanged a few times with you for problems maybe remotely connected.

I have a file : "deep learning with python" that's awesome. I have been reading and annotating it on my computer but the sync with the webapp appears to have been broken. It's been weeks or maybye month.

I tried multiple things today to try to remove the pdf from the webapp and my local app and then readd it and manually import the annotations file (state.json) but it has not worked so far, every time I get the same error in the logs that I don't understand (pasted below). 

Also, state.json weighs 3.1Mb, could that be related to #977 ?

>  {
    "sourceSyncDoc": {
      "fingerprint": "486b5d3f2882a5de297240c210bd5e64",
      "title": "DLP Deep Learning with Python by Francois Chollet.pdf",
      "docMetaFileRef": {
        "fingerprint": "486b5d3f2882a5de297240c210bd5e64",
        "docFile": {
          "name": "1ehexuAX6G-[Chollet]-Deep_Learning_with_Python.pdf",
          "hashcode": {
            "alg": "keccak256",
            "data": "1ehexuAX6GZhvpYigu5RPtytcoQ34cBBi2m9SqJnTsEeJE9mGM",
            "enc": "base58check"
          }
        },
        "docInfo": {
          "progress": 33,
          "pagemarkType": "SINGLE_COLUMN",
          "properties": {},
          "archived": false,
          "flagged": false,
          "tags": {
            "/priority": {
              "id": "/priority",
              "label": "/priority"
            },
            "/pro": {
              "id": "/pro",
              "label": "/pro"
            },
            "ComputerScience": {
              "id": "ComputerScience",
              "label": "ComputerScience"
            },
            "perso": {
              "id": "perso",
              "label": "perso"
            },
            "pro": {
              "id": "pro",
              "label": "pro"
            },
            "/ia/DLP": {
              "id": "/ia/DLP",
              "label": "/ia/DLP"
            }
          },
          "attachments": {
            "122jLgjRAazhkZEsBRtq": {
              "fileRef": {
                "backend": "image",
                "name": "122jLgjRAazhkZEsBRtq.png"
              }
            },
            "123a3opjiPZcxBp1BB94": {
              "fileRef": {
                "backend": "image",
                "name": "123a3opjiPZcxBp1BB94.png"
              }
            },
            "124ZfS3HJRPvddztSDX9": {
              "fileRef": {
                "backend": "image",
                "name": "124ZfS3HJRPvddztSDX9.png"
              }
            },
            "12F4gz4YATN1gH9xVz96": {
              "fileRef": {
                "backend": "image",
                "name": "12F4gz4YATN1gH9xVz96.png"
              }
            },
            "12H9KR5kYA1TFACgoeU5": {
              "fileRef": {
                "backend": "image",
                "name": "12H9KR5kYA1TFACgoeU5.png"
              }
            },
            "12KARNGTZDfGj3SLC5Rp": {
              "fileRef": {
                "backend": "image",
                "name": "12KARNGTZDfGj3SLC5Rp.png"
              }
            },
            "12NCcBUPy8LRNzevC5vy": {
              "fileRef": {
                "backend": "image",
                "name": "12NCcBUPy8LRNzevC5vy.png"
              }
            },
            "12eG2jJrjTmtmgF2zKC3": {
              "fileRef": {
                "backend": "image",
                "name": "12eG2jJrjTmtmgF2zKC3.png"
              }
            },
            "12pAx3evDzd3QqQCu56Y": {
              "fileRef": {
                "backend": "image",
                "name": "12pAx3evDzd3QqQCu56Y.png"
              }
            },
            "15fTUuNBGxVE9Edny5BU": {
              "fileRef": {
                "backend": "image",
                "name": "15fTUuNBGxVE9Edny5BU.png"
              }
            },
            "19wNL6v2RRACQu9URtZA": {
              "fileRef": {
                "backend": "image",
                "name": "19wNL6v2RRACQu9URtZA.png"
              }
            },
            "1MRQneCEMNzEocZR71PP": {
              "fileRef": {
                "backend": "image",
                "name": "1MRQneCEMNzEocZR71PP.png"
              }
            },
            "1gPcdQpm4dvYXQJU2ktP": {
              "fileRef": {
                "backend": "image",
                "name": "1gPcdQpm4dvYXQJU2ktP.png"
              }
            },
            "1h1KhpdCpaRH3oWyar8t": {
              "fileRef": {
                "backend": "image",
                "name": "1h1KhpdCpaRH3oWyar8t.png"
              }
            },
            "1eHYwTY1KYudsxac5Vfs": {
              "fileRef": {
                "backend": "image",
                "name": "1eHYwTY1KYudsxac5Vfs.png"
              }
            },
            "12AzKATk1WXqXegaRLNY": {
              "fileRef": {
                "backend": "image",
                "name": "12AzKATk1WXqXegaRLNY.png"
              }
            },
            "12QKvhQcw9BvLR6dSgDs": {
              "fileRef": {
                "backend": "image",
                "name": "12QKvhQcw9BvLR6dSgDs.png"
              }
            },
            "1YceruG9LZD1TZwg6mtZ": {
              "fileRef": {
                "backend": "image",
                "name": "1YceruG9LZD1TZwg6mtZ.png"
              }
            },
            "1HSCsyYLbPnc2j1VJPj2": {
              "fileRef": {
                "backend": "image",
                "name": "1HSCsyYLbPnc2j1VJPj2.png"
              }
            }
          },
          "nrPages": 373,
          "fingerprint": "486b5d3f2882a5de297240c210bd5e64",
          "added": "2019-07-09T00:30:07.325Z",
          "filename": "1ehexuAX6G-[Chollet]-Deep_Learning_with_Python.pdf",
          "hashcode": {
            "alg": "keccak256",
            "data": "1ehexuAX6GZhvpYigu5RPtytcoQ34cBBi2m9SqJnTsEeJE9mGM",
            "enc": "base58check"
          },
          "lastUpdated": "2019-11-28T18:35:34.176Z",
          "nrAnnotations": 443,
          "nrAreaHighlights": 18,
          "nrComments": 32,
          "nrFlashcards": 1,
          "nrNotes": 0,
          "nrTextHighlights": 392,
          "readingPerDay": {
            "2019-07-18": 16.59,
            "2019-09-17": 2.71,
            "2019-09-18": 7.7700000000000005,
            "2019-09-19": 1.51,
            "2019-09-20": 11.5,
            "2019-09-21": 6.99,
            "2019-09-23": 8.57,
            "2019-11-13": 0,
            "2019-09-24": 18.129999999999995,
            "2019-10-01": 2.8499999999999996,
            "2019-09-26": 1.69,
            "2019-09-27": 11.07,
            "2019-10-03": 3.0100000000000002,
            "2019-10-06": 1.71,
            "2019-10-20": 4.42,
            "2019-10-21": 0.55,
            "2019-10-22": 25.12
          },
          "title": "DLP Deep Learning with Python by Francois Chollet.pdf",
          "uuid": "z2019-11-28T18:35:34.177Z+000001-097957860976"
        }
      },
      "mutationType": "created",
      "uuid": "z2019-11-28T18:35:34.177Z+000001-097957860976",
      "files": [
        {
          "backend": "stash",
          "name": "1ehexuAX6G-[Chollet]-Deep_Learning_with_Python.pdf",
          "hashcode": {
            "alg": "keccak256",
            "data": "1ehexuAX6GZhvpYigu5RPtytcoQ34cBBi2m9SqJnTsEeJE9mGM",
            "enc": "base58check"
          }
        },
        {
          "backend": "image",
          "name": "122jLgjRAazhkZEsBRtq.png"
        },
        {
          "backend": "image",
          "name": "123a3opjiPZcxBp1BB94.png"
        },
        {
          "backend": "image",
          "name": "124ZfS3HJRPvddztSDX9.png"
        },
        {
          "backend": "image",
          "name": "12F4gz4YATN1gH9xVz96.png"
        },
        {
          "backend": "image",
          "name": "12H9KR5kYA1TFACgoeU5.png"
        },
        {
          "backend": "image",
          "name": "12KARNGTZDfGj3SLC5Rp.png"
        },
        {
          "backend": "image",
          "name": "12NCcBUPy8LRNzevC5vy.png"
        },
        {
          "backend": "image",
          "name": "12eG2jJrjTmtmgF2zKC3.png"
        },
        {
          "backend": "image",
          "name": "12pAx3evDzd3QqQCu56Y.png"
        },
        {
          "backend": "image",
          "name": "15fTUuNBGxVE9Edny5BU.png"
        },
        {
          "backend": "image",
          "name": "19wNL6v2RRACQu9URtZA.png"
        },
        {
          "backend": "image",
          "name": "1MRQneCEMNzEocZR71PP.png"
        },
        {
          "backend": "image",
          "name": "1gPcdQpm4dvYXQJU2ktP.png"
        },
        {
          "backend": "image",
          "name": "1h1KhpdCpaRH3oWyar8t.png"
        },
        {
          "backend": "image",
          "name": "1eHYwTY1KYudsxac5Vfs.png"
        },
        {
          "backend": "image",
          "name": "12AzKATk1WXqXegaRLNY.png"
        },
        {
          "backend": "image",
          "name": "12QKvhQcw9BvLR6dSgDs.png"
        },
        {
          "backend": "image",
          "name": "1YceruG9LZD1TZwg6mtZ.png"
        },
        {
          "backend": "image",
          "name": "1HSCsyYLbPnc2j1VJPj2.png"
        }
      ]
    },
    "targetSyncDoc": {
      "fingerprint": "486b5d3f2882a5de297240c210bd5e64",
      "title": "DLP Deep Learning with Python by Francois Chollet.pdf",
      "docMetaFileRef": {
        "fingerprint": "486b5d3f2882a5de297240c210bd5e64",
        "docFile": {
          "name": "1ehexuAX6G-[Chollet]-Deep_Learning_with_Python.pdf",
          "hashcode": {
            "alg": "keccak256",
            "data": "1ehexuAX6GZhvpYigu5RPtytcoQ34cBBi2m9SqJnTsEeJE9mGM",
            "enc": "base58check"
          }
        },
        "docInfo": {
          "added": "2019-11-28T18:33:11.499Z",
          "archived": false,
          "attachments": {},
          "filename": "1ehexuAX6G-[Chollet]-Deep_Learning_with_Python.pdf",
          "fingerprint": "486b5d3f2882a5de297240c210bd5e64",
          "flagged": false,
          "hashcode": {
            "alg": "keccak256",
            "data": "1ehexuAX6GZhvpYigu5RPtytcoQ34cBBi2m9SqJnTsEeJE9mGM",
            "enc": "base58check"
          },
          "lastUpdated": "2019-11-28T18:34:19.054Z",
          "nrAnnotations": 0,
          "nrAreaHighlights": 0,
          "nrComments": 0,
          "nrFlashcards": 0,
          "nrNotes": 0,
          "nrPages": 373,
          "nrTextHighlights": 0,
          "pagemarkType": "SINGLE_COLUMN",
          "progress": 0,
          "properties": {},
          "tags": {},
          "title": "DLP Deep Learning with Python by Francois Chollet.pdf",
          "uuid": "z2019-11-28T18:34:19.056Z+000002-158387330972"
        }
      },
      "mutationType": "created",
      "uuid": "z2019-11-28T18:34:19.056Z+000002-158387330972",
      "files": [
        {
          "backend": "stash",
          "name": "1ehexuAX6G-[Chollet]-Deep_Learning_with_Python.pdf",
          "hashcode": {
            "alg": "keccak256",
            "data": "1ehexuAX6GZhvpYigu5RPtytcoQ34cBBi2m9SqJnTsEeJE9mGM",
            "enc": "base58check"
          }
        }
      ]
    }
  },
  {
    "code": "invalid-argument",
    "name": "FirebaseError"
  }
]`

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version 1.60.11

**Comment by burtonator** [comment]
OK. I'll check this out soon. You're on the latest version which has enhanced exception handling code so should be easier to track down. Sorry about the inconvenience

**Comment by thiswillbeyourgithub** [comment]
Bug is still here as of Polar 1.80.3

Nice update though btw

**Comment by thiswillbeyourgithub** [comment]
Still present as of 1.90.15
