### ISSUE TITLE
How to create new folders?

### ISSUE THREAD

**Issue by nikhilmjn** [burtonator/polar-bookshelf#1230]
I am unable to create new folders after deleting the default files and folders loaded during installation. Please guide me how to create new folder?

Thank you

**Comment by burtonator** [comment]
You create them via tags but in the next version of Polar you can just create them directly in the UI.

https://getpolarized.io/docs/folders.html

> Creating folders
Folders are just tags that have a path. For example linux would be a regular tag. But ‘/tech/linux’ would be a folder.

A document can be stored in multiple folders just like a document can have multiple tags.

**Comment by nikhilmjn** [comment]
thank you!
looking forward to the update!!
