### ISSUE TITLE
Deleting an annotation does not delete associated flashcards.

### ISSUE THREAD

**Issue by cssm** [burtonator/polar-bookshelf#1231]
**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

https://opencollective.com/polar-bookshelf

**Description of the bug**
If I delete an annotation that I've created a flashcard for in the annotation sidebar, when I sync Polar with Anki the flashcards for the deleted annotation still show up in my deck. I have no way of deleting the flashcard afterward in Polar without deleting the PDF itself. 

**To Reproduce**
1. Open any PDF.
2. Click on View and Toggle the Annotation Sidebar.
3. Highlight any sentence in your open PDF to create an Annotation.
4. Click the lightning bolt in the annotation sidebar and create a quick cloze flashcard.
5. Delete the annotation w/o deleting the flashcard you just made.
6. Exit the PDF viewer.
7. Open the Anki application.
8. In the Document Repository of Polar, click Tools and Sync Flashcards to Anki.
9. You will notice a new card is added to the Default deck. If you Browse the deck, the card will be the flashcard you made from the deleted annotation.

**Expected behavior**
The behavior I expected when I deleted the annotation was the associated flashcard would be deleted as well.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by burtonator** [comment]
They're deleted after you restart?  Can you confirm?  

I think you might be right as if they're still being sync'd to Anki that would hint that they aren't being removed.

**Comment by cssm** [comment]
I restarted Polar and the flashcard is still there when I look at the Annotations tab in the Document Repository.
