### ISSUE TITLE
Right-click on ChromeOS fails to work

### ISSUE THREAD

**Issue by jworsef** [burtonator/polar-bookshelf#1242]
**Describe the bug**
Using Chrome on ChromeOS opens the Chrome context menu, instead of Polar's, in the document viewer.

**To Reproduce**
1. Open a document
2. Right click
3. Observe Chrome context menu

**Expected behavior**
Polar's context menu displays 

**Screenshots**
![image](https://user-images.githubusercontent.com/31925386/70167544-dc123700-16be-11ea-8d38-492633b02136.png)
![image](https://user-images.githubusercontent.com/31925386/70167883-9013c200-16bf-11ea-9f43-f7aa8d23f664.png)

- OS: ChromeOS
- Browser: Chrome
- Version: 78.0.3904.106 (Official Build) (64-bit

**Additional context**
Only occurs on documents, not repository view, does not occur in Linux version of Firefox running on ChromeOS

**Comment by burtonator** [comment]
this should be fixed in the next release FYI but I'm going to keep this bug open.

**Comment by burtonator** [comment]
Can you give me your user agent ... 

https://www.whatsmyua.info/

That will tell you...

**Comment by jworsef** [comment]
Mozilla/5.0 (X11; CrOS x86_64 12607.56.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.83 Safari/537.36
Thanks!
