### ISSUE TITLE
Remove 'electron' in user agent

### ISSUE THREAD

**Issue by burtonator** [burtonator/polar-bookshelf#1246]
Right now it's ""Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) polar-bookshelf/1.60.14 Chrome/73.0.3683.121 Electron/5.0.11 Safari/537.36""

some users are receiving errors:

![image](https://user-images.githubusercontent.com/45447/70386491-ebf37a80-194d-11ea-89a0-b11d1727148a.png)
... 

Sriram Muthukrishnan reported it so I can reach out to see if it's been fixed.

**Comment by burtonator** [comment]
https://stackoverflow.com/questions/35672602/how-to-set-electron-useragent

remove via onBeforeSendHeaders

**Comment by Pugio** [comment]
Using 1.60.11 on OS X (10.13.6): can confirm that same error screen when attempting login.

**Comment by burtonator** [comment]
this will be fixed in 1.70..which is going out today /soon
