### ISSUE TITLE
webapp 'deletes' comments when you edit one?

### ISSUE THREAD

**Issue by burtonator** [burtonator/polar-bookshelf#1249]
A user said this but I think it's incorrect:

"And I find something wrong. In the online version , when you edit a comment, all notes that you had to this comment are automatically deleted, it's a pity.  Otherwise all are very good, thanks a lot for your work
"
.. just verify

**Comment by johnfuller** [comment]
I can reproduce this one the desktop app, assuming we're using the same vocabulary.

Editing an existing annotation results in the changes being saved to the annotation, but the comment for that annotation disappears.

**Comment by burtonator** [comment]
``
