### ISSUE TITLE
Annotation tab

### ISSUE THREAD

**Issue by ankinoob** [burtonator/polar-bookshelf#1276]
**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

https://opencollective.com/polar-bookshelf

**Is your feature request related to a problem? Please describe.**
Not really, but I think it's an improvement. Currently, when i go to the annotation tab, I have to go through different pages when i look through my annotation (not everything shows up in 1 page)

**Describe the solution you'd like**
Having an option so you can choose to have all your annotation in a page so you don't have to click next continuously

**Describe alternatives you've considered**
An alternative would be having an option that the tab shows 100/200/500 of the total annotations

**Additional context**

**Comment by burtonator** [comment]
Hm.. why do you want to see that many annotations at once?  I think this is an anti-pattern but I might be wrong. Curious if there's some other feature we need for this so wanted to know what you're trying to accomplish.  maybe we need a different plan.

**Comment by ankinoob** [comment]
I will try to explain it a bit clearer and if it still doesn't make sense, that's ok.

When I go to annotations tab (I usually want to search for a specific annotations that I have in mind usually) and I scroll down to the end, there will be a next and previous button. I just think if there is an option to put all the annotations on page 1, then I don't have to click "next" and scroll up again to then scroll down


https://imgur.com/lzmxgjj

**Comment by thiswillbeyourgithub** [comment]
I think he means he want to see all the annotations in one column instead of having to go through pages.

I think I agree with him, I don't see the benefit of displaying across several pages. It adds extra clicks to get near the and and it breaks continuous reading : the purpose of the annotation panel is to see annotations side by side but some of them will be on the other page so you can't see them at the same time.

**Comment by ankinoob** [comment]
> 
> 
> I think he means he want to see all the annotations in one column instead of having to go through pages.
> 
I think this is a better explanation.
