### ISSUE TITLE
Area Highlight

### ISSUE THREAD

**Issue by ankinoob** [burtonator/polar-bookshelf#1277]
**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

https://opencollective.com/polar-bookshelf

**Describe the bug**
Whenever i try to enlarge the area highlight, it shows a message and I have to redo again in order for it to work (this doesn't happen every time but often enough).  The area highlight also seems to lag a bit more but this might be because of my laptop

**To Reproduce**
1. Create an area highlight
2. Try to enlarge it and it might show the message (I will attach a link for picture)

**Expected behavior**

**Screenshots**
https://imgur.com/EE5Vrph

**Desktop (please complete the following information):**
 - OS: windows 10
 - I use the app
 - Version: 1.8

**Smartphone (please complete the following information):**

**Additional context**

**Comment by thiswillbeyourgithub** [comment]
For me I often have the error "object is not within DOM" or something like that when enlarging a yellow area as soon as it was created. If I wait just a fraction of a second it seems to not happen. It doen't always happen though and I have not been able to reproduce it effectively.

This has been happening for at least 6 months.

**Comment by ankinoob** [comment]
https://imgur.com/bN0rDi9

This is another error message while I use area highlight. This forces me to forced close the application and re-start it

**Comment by burtonator** [comment]
n/a in 2.0
