### ISSUE TITLE
Folders/Tags in mobile app

### ISSUE THREAD

**Issue by ronved** [burtonator/polar-bookshelf#1309]
**Is your feature request related to a problem? 
I can' select a folder/tag to start review.

**Describe the solution you'd like**
Start review icon when clicked can show list of folders/tags?

**Comment by burtonator** [comment]
It's coming somewhat soon. I needed to implement better support for gestures and flyout sidebars for the folders.  Probably 1-2 weeks.

**Comment by burtonator** [comment]
Should be in 1.90 now... you might need to clear your browser cache on mobile though.
