### ISSUE TITLE
found a bug with double scrolling bars

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [burtonator/polar-bookshelf#1313]
**Describe the bug**
A new scroll bar appears on the right of the document window in specific conditions.

**To Reproduce**
1. Am reading a document as usual. The scroll bar is as shown :
![Screenshot from 2020-01-09 12-49-54](https://user-images.githubusercontent.com/26625900/72065574-7543f700-32d6-11ea-962b-ca55b9cacd4c.png)

2. I open a terminal window on the right (I'm on i3, a tiling window manager), this automatically resized polar's document window but adds a scrollbar too, see : 
![Screenshot from 2020-01-09 12-50-22](https://user-images.githubusercontent.com/26625900/72065619-90166b80-32d6-11ea-846a-9bc1c21e59ea.png)

3. this wastes space but an actual problem comes when actually using this bar : it scrolls down *the window itself* : 
![Screenshot from 2020-01-09 12-50-38](https://user-images.githubusercontent.com/26625900/72065674-ade3d080-32d6-11ea-97fc-116e12a58d91.png)

4. when I scroll almost to the end it becomes unusable (full window) : 
![Screenshot from 2020-01-09 12-55-07](https://user-images.githubusercontent.com/26625900/72065812-ff8c5b00-32d6-11ea-8088-ad6b252bf38f.png)

5. To solve this I can toggle on and then off the sidebar and the windows returns to normal.

**Expected behavior**
One scrollbar.

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04 on i3
 - Version Polar 1.80.10

**Comment by or-dodson** [comment]
I have this issue as well and it seems to appear semi-radomly on opening or after just a long period of time reading a pdf.

**Desktop**

* OS: Windows 10
* Polar 1.90

**Comment by thiswillbeyourgithub** [comment]
I agree that it sometimes happens for no discernable reasons too

**Comment by thiswillbeyourgithub** [comment]
I just found out how to get rid of it temporarily : you have to scroll down the useless bar (so you see only half of the viewer for example). You can then see a draggable border on the middle of the left side. Trying to drag this instantly removed the useless scroll and put the viewer in the center of the window as expected.

I don't know if this works everytime though

**Comment by burtonator** [comment]
n/a in 2.0
