### ISSUE TITLE
not building

### ISSUE THREAD

**Issue by scottschafer** [burtonator/polar-bookshelf#1314]
I'm thinking this is an issue with package.json or package-lock.json, but anyway, these steps fail to build:
$ git clone https://github.com/burtonator/polar-bookshelf
$ cd polar-bookshelf
$ npm install && npm run-script compile && npm start

I'm on OS X using node v12.14.1.

It's failing on `npm run-script compile` with Typescript errors like this:

```
> tsc

node_modules/@types/express/index.d.ts:90:50 - error TS2694: Namespace '"/Users/sschafer/projhome/active/artifex/polar-bookshelf/node_modules/@types/express-serve-static-core/index"' has no exported member 'Params'.

90     interface ErrorRequestHandler<P extends core.Params = core.ParamsDictionary> extends core.ErrorRequestHandler<P> { }
```

**Comment by burtonator** [comment]
Could you do this... try to checkout at /tmp and then compile again?  I actually don't think that will fix it but it's just a hunch.  

Could you also have a global typescript installed?

That error is some weird error regarding express library conflicts.  I'm building now and it's working just fine... sorry this bit you but not sure what's causing it. 

I'll keep this open if you have any feedback.

**Comment by scottschafer** [comment]
I tried that. Also tried using v13.6.0.

So weirdly, I get errors when I run `npm run-script compile`. But then `npm start` does run the application.

I just can't run with `npm install && npm run-script compile && npm start`, because the compile error prevents `npm start`.

Anyway, the app looks great. Not sure what's happening, though I'm sure it's not in your code.

**Comment by scottschafer** [comment]
Seems like this fixes it:
```
  "devDependencies": {
    "@types/express": "4.17.0",
```
Found the answer here:
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/40138

Still not sure why it's erroring during the build for me and working for everyone else!

**Comment by burtonator** [comment]
n/a in 2.0
