### ISSUE TITLE
Add "Start pagemark from this point"

### ISSUE THREAD

**Issue by or-dodson** [burtonator/polar-bookshelf#1316]
From my experience, the pagemark box is just too buggy to be practical at all. I would like to use the "create pagemark to this point" since it is a whole lot less buggy. In addition, this would help with creating long pagemarks in large articles, such as textbooks.

**Comment by burtonator** [comment]
Ah... you read my mind. Yes.  The resize box pagemark functionality is buggy and I want to gut it and rework it.  The plan is to also add some new features as part of the process.  

Hopefully on the short term ETA rather than long term.

**Comment by 99887** [comment]
In this vein, if a pdf has bookmarks, would it be possible to add a "Pagemark this bookmark"
Which extends from the start of the bookmark to the start of the next bookmark within the document. (And if a parent bookmark, include all children bookmarks in the pagemark.
