### ISSUE TITLE
Mailchimp failed request: 500 at startup

### ISSUE THREAD

**Issue by klausondrag** [burtonator/polar-bookshelf#1327]
**Describe the bug**
Everytime I start the application, when the main view with the list is loaded, I receive an error message at the top right corner, stating:
"[error] [1.90.0] Error: Mailchimp failed request: 500:". In the development tools, I can see the following:
```
Failed to load resource: the server responded with a status of 500 ()
https://us-central1-polar-cors.cloudfunctions.net/mailinglist/
/snap/polar-bookshelf/82/resources/app.asar/node_modules/polar-shared/src/logger/ConsoleLogger.js:26
```
```
[error] [1.90.0] Error: Mailchimp failed request: 500: 
error @ /snap/polar-bookshelf/82/resources/app.asar/node_modules/polar-shared/src/logger/ConsoleLogger.js:26
```

**To Reproduce**
1. Start the application
2. See the error

**Expected behavior**
No error should occur.

**Screenshots**
Not needed

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Additional context**
This is a fresh ubuntu install with a new snap install. It also happened at my old installation with I believe the .deb package. Therefore, I would think that it has something to do with my account specifically. I've also had this error appear in various networks and locations, so it shouldn't be related to any specific network settings like firewall.

**Comment by burtonator** [comment]
This should be fixed long long long ago.  What version of Polar are you on?
