### ISSUE TITLE
build broken in dde157 commit

### ISSUE THREAD

**Issue by scottschafer** [burtonator/polar-bookshelf#1342]
In the latest code going back to dde157 (Sun Jan 26 12:44:04 2020), I get the following errors when running `npm run-script compile`:
```
web/js/metadata/Pagemarks.ts:8:9 - error TS2724: Module '"../../../../../../Users/sschafer/polar-bookshelf/node_modules/polar-shared/src/util/Percentages"' has no exported member 'Percentage100'. Did you mean 'Percentages'?

8 import {Percentage100, Percentages, round} from 'polar-shared/src/util/Percentages';
          ~~~~~~~~~~~~~

  node_modules/polar-shared/src/util/Percentages.d.ts:1:22
    1 export declare class Percentages {
```

These errors do not happen in the commit just prior (207096).

**Comment by burtonator** [comment]
Thanks... I'm refactoring the build / repo to prevent this from happening in the future.  It will take about another week though.

**Comment by scottschafer** [comment]
Thanks for the update. This is a little off-topic, but speaking of build systems, I'm confused by what I'm seeing in polar-bookshelf/pdfviewer/web/viewer.js. Was this the original source file, or is it build output? I'm not sure what to make of code like `__webpack_require__(9);`.

What I'm working on is a pdf.js-compatible API that uses a different (and superior!) underlying technology. If there's a source for viewer.js that's easier to work with, my job would be easier. Thanks for your help!
