### ISSUE TITLE
lost all data!

### ISSUE THREAD

**Issue by nikhilmjn** [burtonator/polar-bookshelf#1346]
After a 5 hour reading session, i closed the document and it said 'Internal error'. Then I quit the app and restarted. All the data was gone (no documents in the repository). Now it seems it's trying to retrieve my data from the cloud. But i am worried all the work of the last session would be gone! The data must be locally stored somewhere too. Can the app load that? What should I do in this situation?

**Comment by burtonator** [comment]
Wow... that's really upsetting.  

Can you go to ```Help | About?``` It will show you a file path on disk.  Do you get any errors on startup?

**Comment by nikhilmjn** [comment]
It did show an error on startup once, and was stuck on the loading screen. But i quit and relaunched, no error then.
The folders are all there. The stash contains all the documents, but the .meta of files is all empty. is that how it should be?

**Comment by nikhilmjn** [comment]
I tried deleting and reinstalling from the dmg. I added a pdf, but no annotation tool shows up when i select a text. I quit and relaunched, and it won't show the pdf i added earlier.
The .polar folder has the pdf in the stash. Error logs are empty.
I just want a do-over at this point. Been stuck with my reading for 2 days. Please help!

**Comment by nikhilmjn** [comment]
System details: MacOS10.15.1, Polar1.90

**Comment by nikhilmjn** [comment]
Update: I logged out of my polar account, and now it seems to be working fine.
I have a slow internet connection. Could the time taken for sync be causing all these issues?
System: MacOS10.15.1, Polar1.90

**Comment by burtonator** [comment]
> Could the time taken for sync be causing all these issues?
System: MacOS10.15.1, Polar1.90

YES... that's exactly it I imagine.  How many documents?  One issue is that Firebase doesn't (right now) give me progress listeners on snapshots like I would like so I'm unable to determine how much data is being fetched. I'm trying to work around that.
