### ISSUE TITLE
Lag on chrome and desktop app when working on a large PDF file

### ISSUE THREAD

**Issue by jon-ben** [burtonator/polar-bookshelf#1356]
**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

https://opencollective.com/polar-bookshelf

Hi,
I'm having a lot of lags when I'm trying to work on a large PDF file (1300 pages, 40mb file). 
Scrolling through the file isn't smooth at all, it can pause for a couple of seconds before scrolling again.
The area highlight feature is unusable because of the lag: when I try to drag the box to resize it, there is a 3 second lag before it happens on my screen.
When using the webapp on firefox, everything is smooth and I don't have any lags, whatsoever.

**To Reproduce**
Try to work on a large pdf file. If you don't have one, I can post mine.

**Expected behavior**
Smooth performance and no lag.

**Screenshots**
https://streamable.com/s4ehw this is a record from the desktop app. You can see the lag at the 5 sec mark when it stops scrolling. At the 16 second mark I'm trying to drag the area highlight box to resize it, you can see the lag too.
Same pdf using the webapp on firefox:
https://streamable.com/wzv2c no pauses when scrolling, the area highlight feature is much more responsive.

**Desktop (please complete the following information):**
 - OS: win 10
 - Browser Chrome
 - Version latest version

**Comment by thiswillbeyourgithub** [comment]
Same for me but on linux 18.04. The desktop version has become way slower for me

**Comment by Marinus88** [comment]
I had the same problem. I tried to split the document into different files and import them one by one. When I try to import documents, although I named them differently, Polar always overwrites the same document, despite the fact that the name is completly different.

**Comment by FilipBB** [comment]
I am also seeing a lot of lag in the flash card creation dialog. I have about 500 flash cards created and with the desktop app the input lag in the card creation textbox is really high. It doesn't display what I type until 3-5 seconds after I've stopped typing.

**Comment by burtonator** [comment]
should be n/a on 2.0
