### ISSUE TITLE
When you move an area highlight, it loses all the comments and flash cards associated with it

### ISSUE THREAD

**Issue by ramesh-tr** [burtonator/polar-bookshelf#1366]
When you move an area highlight, it loses the comments and flashcards associated with it.

STR (Desktop)
---------------
1. Login to https://app.getpolarized.io/
2. Open a document
3. Right click and "Add area hightlight"
4. Add a comment using the annotation bar
5. Move the area hightlight slightly to adjust the posiotion

Expected: Comments are not deleted
Actual: Comments along with the flashcards are disappeared from the annotation bar

**Comment by burtonator** [comment]
should be n/a on 2.0
