### ISSUE TITLE
sort by number and not digits

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [burtonator/polar-bookshelf#1371]
**Is your feature request related to a problem? Please describe.**
Hi,
Currently sorting the pdf by title puts `lesson 10` before `lesson 9` but it reverses when the name is `lesson 09`. Is it possible to sort by overall number instead of just digits ?

**Describe the solution you'd like**
Sort by number.

**Describe alternatives you've considered**
Renaming everything one by one :(

**Comment by burtonator** [comment]
No... the titles aren't meant to be parsed this way.  If you want sorting via numbers put a zero prefix before everything.  Lesson01 ... Lesson10 .. .should work.  Does it not?

**Comment by sopoforic** [comment]
Even if that's not how you originally envisioned sorting working, it's a very reasonable thing to desire. A natural sort like natsort for python (https://pypi.org/project/natsort/, and it looks like there's a JS thing inspired by it at https://www.npmjs.com/package/natsort) fits in well with users' expectations, and it would be rare that you would really want a document title sorted strictly lexically, instead.

Please consider fulfilling this request.

**Comment by thiswillbeyourgithub** [comment]
Thank you @sopoforic

Putting a 0 before everything is really tedious especially while there are no shortcuts. And lots of times when you add pdf you don't know how many lessons of something you're going to have.
