### ISSUE TITLE
Polar Extension says page was saved, but does not show online or on desktop app

### ISSUE THREAD

**Issue by keithcdodd** [burtonator/polar-bookshelf#1373]
**Describe the bug**
Polar Chrome Extension says page/pdf is saved to Polar, but page does not show in polar online or on desktop.

**To Reproduce**
1. Download pdf
2. Open pdf in chrome
3. Click polar extension -> says successfully saved
4. check on desktop version and online and do not see document

**Expected behavior**
Document exists like it says

**Desktop (please complete the following information):**
 - OS: Chrome, but with Debian Linux Beta
 - Browser Chrome
 - Version 79

**Additional context**
It is cumbersome to upload the pdf instead because I use a chromebook. So the download of the pdf does not go directly to my linux files to upload. Long story short, it would be very convenient if the chrome extension worked with this for me. I have confirmed I am logged into the same account for both the extension and Polar.

**Comment by bepolymathe** [comment]
Same situation here.

**Comment by burtonator** [comment]
should be n/a on 2.0
