### ISSUE TITLE
Highlighting Text Misses Every "f"

### ISSUE THREAD

**Issue by keithcdodd** [burtonator/polar-bookshelf#1377]
**Describe the bug**
When highlighting text in Polar Online in Chrome, the created note misses every letter "f".

**To Reproduce**
1. Open pdf in Polar Online in Chrome
2. Highlight Text
3. Saved note is missing every "f"

**Expected behavior**
The created note reads the same as the highlight and is not missing "f"s. This should be easy for it to read? The font is normal, and it does not miss any other letters

**Screenshots**
![image](https://user-images.githubusercontent.com/61259563/76779164-8561d200-6770-11ea-9bfe-a814a0d63912.png)

**Desktop (please complete the following information):**
 - OS: Chromebook
 - Browser chrome
 - Version 80

**Comment by burtonator** [comment]
Does it do this for ALL your PDFs or just one or two?  MUST be something weird with the PDF I think... the 'f' might be a glyph or something weird to do with fonts. Agree that is super annoying.  Might need you to share the PDF if it's isolated to this PDF

**Comment by keithcdodd** [comment]
Hi, you're right. I just ran into the same problem copy and pasting from the same pdf into a google document. It's just weird because it is a full medical online textbook so I would think it shouldn't have such an issue. But, it does.
