### ISSUE TITLE
throw error when run npm install

### ISSUE THREAD

**Issue by tim-hub** [burtonator/polar-bookshelf#1381]
**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

https://opencollective.com/polar-bookshelf

**Describe the bug**
```
 No matching version found for polar-accounts@^1.100.4.
```
when run npm insta;;

**To Reproduce**
1. `npm i`

**Expected behavior**
no error

**Additional context**
for development locally

**Comment by burtonator** [comment]
Thanks.. working on a fix for this and refactoring our version control system.
