### ISSUE TITLE
StackOverflow capture modal overlay blocks highlighting

### ISSUE THREAD

**Issue by willlma** [burtonator/polar-bookshelf#1382]
**Describe the bug**
Capturing StackOverflow results in a modal overlaying the captured view. 

**To Reproduce**
1. Click 'Capture web page' in the desktop app
2. Paste https://stackoverflow.com/questions/18500016/undo-a-git-rerere-resolution-that-was-done-in-a-rebase into the address bar and press enter
3. Choose Chrome on Desktop as the browser and click download
4. The viewer opens, but looks different than it did in the preview and text is not selectable

**Expected behavior**
I expected the page to look like the preview before I pressed download. 

**Screenshots**
![image](https://user-images.githubusercontent.com/4404401/77597050-e8630f80-6eba-11ea-985d-721b28a1a9ed.png)

**Desktop (please complete the following information):**
 - OS: OSX 10.13.6
 - Browser Desktop/Electron
 - Version 1.90.18

**Additional context**
I can get around this by using the Samsung renderer

**Comment by burtonator** [comment]
Our new highlight / capture system will solve this.
