### ISSUE TITLE
Delete account

### ISSUE THREAD

**Issue by stndrs** [burtonator/polar-bookshelf#1383]
Hey, I can't find anywhere in the web app to delete my account. If someone could help me out and delete my data that would be great.

**Comment by burtonator** [comment]
I'll take care of it.. can you email support with your email address so I can delete it?

**Comment by stndrs** [comment]
Can I assume the correct email is support@getpolarized.io ?

**Comment by burtonator** [comment]
@stndrs yes... sorry.  We're moving to a new support system and in between that now.

Also, should have self-service account delete soon.  I was hoping it would go into the last release.
