### ISSUE TITLE
Anki sync - Images break

### ISSUE THREAD

**Issue by irasanchez** [burtonator/polar-bookshelf#1388]
**Describe the bug**

**To Reproduce**
I made flash cards in Polar that include images.
The images were pasted in, not uploaded.
Then, I synced with Anki via Polar's tools menu.
Images in Anki in polar cards appear as broken image icon instead

**Expected behavior**
I expected to see the images that I could see in Polar

**Screenshots**

Anki:
![image](https://user-images.githubusercontent.com/14080134/78461261-48f10a00-767c-11ea-876e-f42601f0651a.png)

Polar:
![image](https://user-images.githubusercontent.com/14080134/78461293-89508800-767c-11ea-82ab-c9b2a7bfbf3c.png)

**Desktop (please complete the following information):**
Windows 10 
Polar 1.100.13

When I sync, no errors are listed.

**Comment by DANCOSTA-myname** [comment]
Hi, i don´t really know if this can help. However i noticed that if you add image as png instead of jpg seems to work....
i think that when image is automatically pasted in, it is saved as jpg by default

Best regards

**Comment by burtonator** [comment]
I just confirmed and this works. You might be right that it breaks on jpg but when I past it is as png... I wonder if this is a platform issue. Maybe Windows pastes as jpg ?
