### ISSUE TITLE
Editing an annotation deletes any attached flashcards

### ISSUE THREAD

**Issue by amill676** [burtonator/polar-bookshelf#1393]
**Describe the bug**
Editing an annotation that has an attached flashcard will cause the flashcard to be deleted

**To Reproduce**
1. Open a pdf for viewing
2. Highlight some text to create an annotation
3. In the annotation sidebar, locate the annotation and click on the ... icon to the far right.
4. In the dropdown, click create flashcard
5. Click "Create" to save the flashcard
6. Click the pencil icon under the annotation (not the flashcard) to edit the annotation
7. Click "Change"
8. The flashcard will now have been deleted. Moreover, reverting the change to the annotation does not seem to bring the flashcard back

**Expected behavior**
Expected flashcard not to have been modified if the text of the annotation is modified

**Screenshots**

**Desktop (please complete the following information):**
 - OS: mac OS High Sierra 10.13.3
 - Browser: Using Polar desktop application
 - Version:  1.100.13

**Smartphone (please complete the following information):**

**Additional context**
Resulted in losing a flashcard that took a while to create without any way of getting it back. Could prevent users from relying on Polar as a source of truth for flashcards

**Comment by burtonator** [comment]
should be n/a on 2.0
