### ISSUE TITLE
Unable to build project "No matching version found for polar-google-fonts@^1.100.14."

### ISSUE THREAD

**Issue by mdm508** [burtonator/polar-bookshelf#1394]
**Describe the bug**
Tried to run `npm install`

**To Reproduce**
master is at `ff81f902e36cafab5e907171eb870303aa1decc0`

I tried to build the repo using `npm install` 

and received 

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for polar-google-fonts@^1.100.14.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'polar-bookshelf'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/f/.npm/_logs/2020-04-13T00_03_55_569Z-debug.log

```
**Desktop (please complete the following information):**
 - OS: Catalina 10.15.14

[log.log](https://github.com/burtonator/polar-bookshelf/files/4467420/log.log)

**Comment by ChristofferGreen** [comment]
I have the same issue running raspbian on a raspberry pi 4.

**Comment by KuffDeSchmull** [comment]
same issue mac os

**Comment by topiux** [comment]
same issue, macOS 10.14.6 (Mojave)

**Comment by burtonator** [comment]
should be n/a on 2.0
