### ISSUE TITLE
Show comments with annotations

### ISSUE THREAD

**Issue by jonaskoeppel** [burtonator/polar-bookshelf#1396]
Dear Polar team,
I've been checking out your great application. Love the simplicity of things! One thing I've kept wondering: In reader mode I can add comments to annotations. When showing them in the "Annotation" tab, however, the connection to the annotation is lost - it's just presented as a "loose" comment. Wouldn't it make more sense to maintain this connection, showing comments together with the annotation they are attached to? This could be done, for example, in the right panel of the "Annotations" view, which would allow to show the comment at the same time as a "loose" one in the list on the left.
Thanks!
Jonas

**Comment by burtonator** [comment]
This is added in 2.0 which is in late beta now...
