### ISSUE TITLE
Resizing pagemarks breaks at higher zoom levels.

### ISSUE THREAD

**Issue by modemenusource** [burtonator/polar-bookshelf#1402]
**Describe the bug**
Pagemarks either spazz out or stop moving completely when trying to resize them at higher zoom levels, doing so also breaks them at default zoom levels and a CTRL+R is required.

**To Reproduce**
1. Zoom in to say, 150%
2. Find a pagemark
3. Try to resize it

**Expected behavior**
I expected the pagemark to resize.

**Desktop (please complete the following information):**
 - OS: Windows 10 1903

**Comment by burtonator** [comment]
n/a on 2.0
