### ISSUE TITLE
Documents not Fully Loading in Desktop

### ISSUE THREAD

**Issue by Dranion** [burtonator/polar-bookshelf#1403]
**Describe the bug**
Currently, my documents are **inconsistently loading** on the desktop. I'll start polar bookshelf and be missing a variable amount of documents, with no loading bar. These documents remain missing even if I wait 15-20 minutes. Currently I have 264 documents in my repository, and anywhere from 22-the full amount are loading. 

**To Reproduce**
Upon reloading (CTRL+R), a different set of documents will be missing. May be less or more. Fully restarting polar-bookshelf results in the same behavior. _Occasionally the correct number of documents **will** be loaded, but not usually._ Differences in successful vs. unsuccessful runs presented below. 

**Expected behavior**
I expect the documents being loaded in the Desktop to match the documents being loaded in the browser version, and to be consistent with every load. 

**Desktop (please complete the following information):**
 - OS: Manjaro Linux 20.0 Lysia with a custom kernel (5.6.5-arch-1-1-surface) 
 - Version: per command line: 
> Running with Node version: v12.8.1
> Running with Electron version: 7.1.2
> Running with Polar version: 1.100.13

**On a 'functional' run** 
Replicated twice, same output. 
The command line will represent: 
> Allowing pre-releases for auto-updates: false
> Auto updates disabled.
> Running with CWD: /home/dranion
> Running with Node version: v12.8.1
> Running with Electron version: 7.1.2
> Running with Polar version: 1.100.13
> Running with app version: 1.100.13
> Loaded prefs from: /home/dranion/.polar/config/prefs.json
> body-parser deprecated undefined extended: provide extended option ../../usr/lib/polar-bookshelf/resources/app.asar/node_modules/polar-shared-webserver/src/webserver/Webserver.js:89:35
> [notice] [1.100.13] External navigation block enabled: true

and the developer console shows [this](https://gist.github.com/Dranion/42f54118cfcafb82c5a321c62a93a6ec) 

**On a run with loss files**
The command line presents the same, but the console is [different](https://gist.github.com/Dranion/943349966101cedf4baacfa6278f6b58). Ironically, it's missing errors and "ERR_FILE_NOT_FOUND" which the successful runs have. 

Bug fairly annoying but not critical. I reload until I get a complete load, which can take 5-10 tries. Might be pinging your servers unnecessarily, though.

**Comment by burtonator** [comment]
should be n/a on 2.0
