### ISSUE TITLE
Shifting Text Highlight on HTML docs

### ISSUE THREAD

**Issue by mmcarli** [burtonator/polar-bookshelf#1405]
**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

https://opencollective.com/polar-bookshelf

**Describe the bug**
I highlight some lines of text in a HTML document. Later, usually after closing my Polar session and starting a new one, the highlight has shifted so that it no longer covers the text it should, but instead covers a random location on the doc.

**To Reproduce**
1. Highlight text
2. Close Polar
3. Re-open Polar, sometimes it does not happen immediately however.
4. Jump to context for the highlight, it does not cover the text found in the annotation.

**Expected behavior**
I highlight some lines in a HTML document and they persist in that location over time. 
**Screenshots**
![Screenshot from 2020-04-25 13-11-46](https://user-images.githubusercontent.com/51248095/80285940-669f1580-86f6-11ea-8c55-3c9ba1d75883.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.4
 - Browser: Chrome
 - Version 1.100.13

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by cameronj86** [comment]
I'm experiencing the same issue: 
https://imgur.com/M73ZOwr

The notes in the the sidebar stay constant fwiw but not very pleasing visually

**Comment by burtonator** [comment]
should be n/a on 2.0
