### ISSUE TITLE
Custom Columns (Feature Request)

### ISSUE THREAD

**Issue by psygo** [burtonator/polar-bookshelf#1406]
## 1. Is your feature request related to a problem?

As was mentioned in the related issue #671, many users miss an author column, as do I &mdash; and that should have a higher priority than this issue. But, thinking about it, what would solve this issue, albeit in a manner that would need much more work, is a way for the user to create a custom column.

This solution would solve any future feature requests for new columns and would give the user much more freedom.

## 2. Describe the solution you'd like

A popup similar to the one when you're creating a new tag or altering the name of the file would be enough, I think.

## 3. Additional context

This might seem too generic and something that would not have any context or little use.

However, for example, say you're an accountant. It's not unusual at all to want your files filtered by clients (example of new column). If there were a column for this, it would be really nice. Of course, you could create a tag for each client or a tag with internal metadata like `client: X`, but a column seems to be more intuitive here.

## 4. Alternative Solution

An alternative solution could be to have folders for the tags or a similar hierarchy. For example, in the same accountant example. I could have a `client` tag alongside many tags for each client. Making this possible would help the user to better organize the potentially hundreds of tags she has.

If Polar allowed for tag nesting, we could tie new columns to these super tags and, then, each shown column instance for each file would be the assigned tag inside the super tag for the specific file.

On its Windows version, Evernote makes most of this available &mdash; it isn't available in any of its other supported platforms &mdash; and I find it very helpful.

I'm hoping to hear more from the developer(s), this was supposed to be part feature request, part discussion.

**Comment by thiswillbeyourgithub** [comment]
To me, this is related to #682  

It would be great to add a note per document (as suggested in #682) and below it to add optionnal fields like author, genre, year, whatever else for maximum flexibility. 

Then we could just right click on the sorting bar, select the field and sort by it.

Of course sorting would be better by numbers than digits as I said in #1371

**Comment by burtonator** [comment]
A lot of the foundation has been laid for this and we will have more functionality for this in 2.0...

The metadata support author data and when we ship 2.0 I'm going to have more flexibility in adding features like this.

... so 2.0 will come out first then we will be releasing more rapid releases with features like this once we're done.

**Comment by burtonator** [comment]
Implemented now 👍
