### ISSUE TITLE
Try to determine why startup time is so slow.

### ISSUE THREAD

**Issue by burtonator** [burtonator/polar-bookshelf#1410]
Our startup time is VERY slow for loading the electron app.  It's about 4000ms on my machine..

Once Polar 2.0 is up it's SUPER fast.  

IT might be that once we ditch bootstrap that this goes away so maybe we delay investigating this until this is resolved.  

One idea could be to "monkey patch" the require method and add timing to it directly.  this way we can see which scripts are taking the most time to load.

**Comment by burtonator** [comment]
only ONE require was called and it was for entry.js and took the entire duration... so that won't work.

**Comment by burtonator** [comment]
it looks like the newly imported module has an updated require for some reason... it should be globally patched but for some reason node is rrestoring it.

**Comment by thiswillbeyourgithub** [comment]
didn't want to start an issue for this but is there a reason why when I display strace of `polar-bookshelf.bin --no-sandbox` I have a very fast flow of the following line/error : 
(I couldn't copy so here's a picture)

![screenshot](https://user-images.githubusercontent.com/26625900/81595663-610e2480-93b2-11ea-8036-8f03209cdc0c.png)

Polar is sometimes using most of my cpu for no apparent reason
