### ISSUE TITLE
Crazy progress bar

### ISSUE THREAD

**Issue by jaumzera** [burtonator/polar-bookshelf#1417]
**Describe the bug**
Progress bar under main menu seems crazy

**To Reproduce**
1. Open Polar and search for a file.

**Expected behavior**
Show the file if found.

**Screenshots**
Vídeo on Youtube: https://youtu.be/sTuk83nW9Y0

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Ubuntu 18.04
 - Browser: N/A
 - Version 1.100.13

**Comment by burtonator** [comment]
Ah.. yes. There are multiple sync's in progress on that one.  2.0 will have a new framework to fix this.
