### ISSUE TITLE
@polar-app-types/pdfjs-dist@^2.0.0-beta.5 is not in the npm registry

### ISSUE THREAD

**Issue by UmarAbdullahi** [burtonator/polar-bookshelf#1423]
@polar-app-types/pdfjs-dist@^2.0.0-beta.5' is not in the npm registry

After cloning the package npm install gives the error above
 - OS: Windows 10

**Comment by thiswillbeyourgithub** [comment]
same here, ubuntu 18.

Shame, I really want to use this beta fast, polar is barely usable for me right now

**Comment by UmarAbdullahi** [comment]
> same here, ubuntu 18.
> 
> Shame, I really want to use this beta fast, polar is barely usable for me right now

If I remove the polar-app-types from the package.json I get a ton of compile error.
Incase you come across a solution come back here to share.

**Comment by thiswillbeyourgithub** [comment]
I don't have the time to look for a fix.

possibly related #578

**Comment by thraizz** [comment]
The package is published [here](https://github.com/burtonator/polar-app-public/packages/251550).
Download the tarball, create a subfolder, remove the package from `package.json` (line 75 in `dev-dependencies`), install and add the downloaded package to dependencies and build your app.
Note: I also had to install typescript globally with `npm install typescript -g`

Everything in commands:
```
git clone https://github.com/burtonator/polar-bookshelf.git
cd polar-bookshelf
mkdir package
# Download the @polarapp-types/pdfjs-dist package from https://github.com/burtonator/polar-app-public/packages/ into ./package
npm install --save package/@polarapp-types_pdfjs-dist-2.0.0-beta.3-npm.tgz
sudo npm install typescript -g
npm install && npm run-script compile && npm start
```

**Comment by burtonator** [comment]
Sorry for the inconvenience.  I'm reworking our build into a multi-repo build....
