### ISSUE TITLE
polar's electron app and web version have not been in sync for at least a month

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [burtonator/polar-bookshelf#1429]
**Describe the bug**
I have been having lots of bugs for some time with Polar, so I decided to try if the web version was somehow better and I saw that my documents had not been synced for more than a month. No documents I added had been synced.

**Desktop (please complete the following information):**
 - Version 1.100.13

I double checked and the account is the same, paid an all. Is this a known bug during the transition to 2.0?

edit : it seems that adding a document on the web version send it to the app but not the other way around.

**Comment by burtonator** [comment]
This bug should be fixed in 2.0 as we're migrating to a unified cloud model so there's no 'sync' anymore.

We're working on getting 2.0 released ASAP and will have a documented plan for users to upgrade.
