### ISSUE TITLE
Capture webpage doesn't work for web.archive links

### ISSUE THREAD

**Issue by CrispyDrone** [burtonator/polar-bookshelf#1430]
**Describe the bug**

Capture web page doesn't work for web.archive pages. I have attempted 3 different web.archive links so far, none of them succeeded. Other pages are being captured just fine.

**To Reproduce**
1. Click on capture web page
2. Go to `https://web.archive.org/web/20160304045715/http://permalink.gmane.org/gmane.comp.version-control.git/217` or `https://web.archive.org/web/20191102163024/http://www.cs.umd.edu/~pugh/java/memoryModel/DoubleCheckedLocking.html` or `http://web.archive.org/web/20160322095243/https://blogs.msdn.com/b/pfxteam/archive/2011/10/24/10229468.aspx`
3. Wait for the page to finish loading and capture it
4. An empty window is shown with sporadically an EPERM exception message

**Expected behavior**
The web page is captured properly. I am able to reopen the web page later.

**Screenshots**
1. Page loads fine:

![image](https://user-images.githubusercontent.com/37639058/86397863-ecb27c00-bca4-11ea-84dc-7502b6fbc15f.png)

2. Capturing results in empty document with sporadically (?) the EPERM exception message

![image](https://user-images.githubusercontent.com/37639058/86397936-123f8580-bca5-11ea-830e-76f7b1c37387.png)

**Desktop:**
 - OS: Windows 10 version 1903
 - Browser: Chrome  83.0.4103.116 (Official Build) (64-bit)
 - Polar version: 1.100.13

**Comment by burtonator** [comment]
should be n/a on 2.0
