### ISSUE TITLE
Polar 2.0.0 beta 7 produces error on trying to start

### ISSUE THREAD

**Issue by hedonia** [burtonator/polar-bookshelf#1431]
This is on the latest version of macOS. Produces following error and won't start:

Error: ENOENT: no such file or directory, open '/var/folders/6p/9q2glhd54gq_qbtps6ncg4m00000gn/T/.io.inputneuronpolar.zXzpOJ'

**Comment by burtonator** [comment]
Will fe fixed in beta 9 I think.
