### ISSUE TITLE
Create pagemark to point results in assertion error when too close to page's bottom edge

### ISSUE THREAD

**Issue by CrispyDrone** [burtonator/polar-bookshelf#1435]
**Describe the bug**
An exception message is shown when trying to create a pagemark inside a page's footer, apparently too close to the lower edge of the page. The same problem does not exist for the header of the page.

**To Reproduce**
1. Open a pdf
2. Scroll down to the end of a page
3. Right click close to the edge of the page and try to create a pagemark to this point
4. Observe error

**Expected behavior**
A pagemark is created for the full page.

**Screenshots**
![image](https://user-images.githubusercontent.com/37639058/87590146-a4547e80-c6e6-11ea-88dd-92d39f5241ab.png)

**Desktop:**
- OS: Windows 10 version 1903
- Polar version: 1.100.13

**Comment by burtonator** [comment]
should be n/a on 2.0
