### ISSUE TITLE
Right clicking on a folder or tag also results in its selection

### ISSUE THREAD

**Issue by CrispyDrone** [burtonator/polar-bookshelf#1436]
**Describe the bug**
Right clicking on a folder or tag results in its selection.

**To Reproduce**
1. Go to the document repository
2. Right click on a folder or tag 
3. Context menu allows you to create or delete a tag
4. However, the tag or folder is also selected.

**Expected behavior**
Only the context menu should be shown, the tag or folder should not be selected.

**Screenshots**
1. ![image](https://user-images.githubusercontent.com/37639058/87590734-90f5e300-c6e7-11ea-91d2-30522a3bacfb.png)
2. ![image](https://user-images.githubusercontent.com/37639058/87590766-9c490e80-c6e7-11ea-9bfd-6566cf7ccd00.png)

**Desktop:**
- OS: Windows 10 version 1903
- Polar version: 1.100.13

**Comment by burtonator** [comment]
should be n/a on 2.0
