### ISSUE TITLE
Delete tag doesn't take effect until after a restart

### ISSUE THREAD

**Issue by CrispyDrone** [burtonator/polar-bookshelf#1437]
**Describe the bug**
Deleting a tag doesn't take effect until after a restart.

**To Reproduce**
1. Go to document repository
2. Assign a new or existing tag to a document
3. Right click the tag, and press delete
4. Confirm the deletion
5. Observe that the tag is still there, and that clicking on it still filters the document list
6. Redeleting the tag doesn't issue a warning.

**Expected behavior**
The tag should immediately be deleted i.e. removed from the list.

**Screenshots**
1. ![image](https://user-images.githubusercontent.com/37639058/87591092-1d080a80-c6e8-11ea-9d76-5cb7268e6dff.png)
2. ![image](https://user-images.githubusercontent.com/37639058/87591118-26917280-c6e8-11ea-848c-92ae6c2b0f49.png)

**Desktop:**

- OS: Windows 10 version 1903
- Polar version: 1.100.13

**Comment by burtonator** [comment]
Fixed in 2.0
