### ISSUE TITLE
EPUB links do not update nav interface

### ISSUE THREAD

**Issue by sopoforic** [burtonator/polar-bookshelf#1444]
Clicking a link (e.g. from the TOC) in an EPUB correctly navigates to the link target. However, it does not update the navigation interface at the top of the window.

# Reproduce

1. Get the [EPUB with images](http://www.gutenberg.org/ebooks/8086) of this book from project gutenberg, and import it into polar.
2. Click the down arrow to get to the section with the TOC.
3. Notice that the nav element correctly reads "2 of 14".
4. Click the link to Chapter 3 from the TOC.
5. Chapter 3 is displayed.
6. The nav element still incorrectly reads "2 of 14".
7. Clicking the down arrow now incorrectly leads to the prologue, which is "3 of 14".

# Details

This affects 2.0 beta 13, both desktop (windows x64) and web.

**Comment by sopoforic** [comment]
On a related note, it'd be good to push state when clicking a link, so the browser's back/forward buttons could be used to navigate, e.g. to return from a footnote.

**Comment by burtonator** [comment]
Gotcha.. yes.  I agree and we're trying to push state more and I'm working on a change there.

**Comment by sopoforic** [comment]
This has been fixed.
