### ISSUE TITLE
Inconsistent interface behavior

### ISSUE THREAD

**Issue by sopoforic** [burtonator/polar-bookshelf#1449]
In 2.0 beta 13, there are three icons at the top right: the user icon, the settings gear, and the vertical ellipsis. Their behavior is not consistent with one another.

Clicking the user icon opens a dropdown with information on the user's plan. Clicking any other interface element *does not* remove this dropdown.

Clicking the gear changes pages.

Clicking the ellipsis opens a menu. Clicking any other interface element (or empty space) *does* remove this dropdown.

**Comment by burtonator** [comment]
> Clicking the user icon opens a dropdown with information on the user's plan. Clicking any other interface element does not remove this dropdown.

Yes. That's definitely a bug.

> Clicking the ellipsis opens a menu. Clicking any other interface element (or empty space) does remove this dropdown.

That works for me...

**Comment by burtonator** [comment]
Closing this one as I fixed the dropdown issue.

**Comment by sopoforic** [comment]
> That works for me...

Just to clarify for the record: it works for me, too. I just listed the current behavior of all three to indicate that they all behaved differently from one another.
