### ISSUE TITLE
Attempting to load invalid document URL should give feedback

### ISSUE THREAD

**Issue by sopoforic** [burtonator/polar-bookshelf#1453]
In 2.0 beta 15, attempting to load a bad document ID (e.g. https://beta.getpolarized.io/doc/DEADBEEF, or realistically the URL of a document which has been deleted) just gives a loading spinner forever. A user-friendly error message should instead be presented--probably, a message that does not reveal whether there is or has ever been a document at that address, for improved privacy.

**Comment by burtonator** [comment]
I think this is valid and there's a FIXME in the code for this.  Right now we don't know why a document is 'undefined' and it could be for any reason.  I think the FIRST undefined should indicate that the document is missing and if we get one AFTER it was defined in the past, that means the document was deleted.  

I tagged this for the 2.0 series so I can fix it in 2.0 or 2.0.1
