### ISSUE TITLE
Certain pagemark changes lost on window resize

### ISSUE THREAD

**Issue by sopoforic** [burtonator/polar-bookshelf#1462]
In beta 16, on chrome 84:

1. Capture [this wikipedia page](https://en.wikipedia.org/wiki/Sorcerous_Stabber_Orphen).
2. Right click and make a pagemark somewhere.
3. Drag the pagemark down a bit.
4. Resize the browser window
5. Observe that the pagemark snaps back to its former location.

Only changes in position caused by right-clicking and selecting "Create Pagemark to Point" survive resizing.

However, dragging the pagemark, then closing the tab and reopening it *does* result in the pagemark staying where I put it, so the change is being persisted properly.

**Comment by burtonator** [comment]
Good catch. I just fixed it and will be out soon. I'm going to try to do more incremental releases from here on out.

**Comment by sopoforic** [comment]
Confirmed. This works in beta 17.
