### ISSUE TITLE
Not building, no matching version for epubjs

### ISSUE THREAD

**Issue by marecabo** [burtonator/polar-bookshelf#1464]
**Describe the bug**
`npm install` fails with `No matching version found for epubjs@0.3.89-polar.12.`.

```log
npm ERR! code ETARGET
npm ERR! notarget No matching version found for epubjs@0.3.89-polar.12.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'polar-bookshelf'
npm ERR! notarget
```

**To Reproduce**
1. Have Node and NPM installed and their binaries in your `PATH`.
2. Clone repository with `git clone https://github.com/burtonator/polar-bookshelf.git`
3. run `npm install` in cloned directory

**Expected behavior**
`npm install` should succeed without errors.

**Desktop:**
 - OS: Windows 10 2004 x64
 - Node: 12.18.3
 - NPM: 6.14.6

**Comment by burtonator** [comment]
Yes... we're not able to have 3rd parties build it right now due to our repo configuration.  It's really annoying I agree and we're working on trying to fix it.  We're focused on 2.0 release now but will try to find an alternative for this in the future.

**Comment by marecabo** [comment]
Thanks for your response and your work on Polar. I'll then wait for after the next release and am looking forward for working build instructions.
