### ISSUE TITLE
Reading reviews should not elide annotation text

### ISSUE THREAD

**Issue by sopoforic** [burtonator/polar-bookshelf#1467]
2.0 beta 20 on Chrome 84.

If a long annotation appears in a reading review, it is elided. For example, I have a highlight:

> The General Hospital plot that my grandmother was most proud of involved a plot point, that, granted, might strain credulity, but illustrates the narrative impact that can only come from placing your characters under as much duress as you can fathom. One father, after his young daughter was rendered brain-dead in a tragic car accident, makes the decision to take her off life support so that her heart could transplanted into the body of her ailing cousin, saving the second life. Some clips from this plotline are up on Youtube. It’s devastating stuff, even if you haven’t been following the characters for years. But what my grandmother was most proud of was that after the story aired, there was an appreciable increase nation-wide in organ donation sign-ups.

In a reading review, I see:

![chrome_sprs6v2ufx](https://user-images.githubusercontent.com/78205/92347728-fc807f00-f09e-11ea-9d21-fb44da8ae35f.png)

Obviously, this is not ideal. The full annotation should be displayed.

**Comment by burtonator** [comment]
Agreed.. going to revisit this soon.

**Comment by sopoforic** [comment]
I cannot use (or test!) reading reviews until this bug is fixed. It would be nice if it could be fixed sooner rather than later.

**Comment by burtonator** [comment]
Will be fixed in next release.
