### ISSUE TITLE
Ctrl+Shift+C to create cloze opens inspector 

### ISSUE THREAD

**Issue by sopoforic** [burtonator/polar-bookshelf#1471]
2.0 beta 20 on Chrome 84.

When attempting to create a cloze card, I highlighted text and pressed `Ctrl+Shift+C`. This correctly changed the text to create the cloze, but it also opened the inspector. Once the inspector fully opened, the text was reverted, removing the cloze. Selecting the text and pressing `Ctrl+Shift+C` again correctly creates the cloze, which now is number `c2`. Finally, closing the inspector once again reverts the text, removing the cloze.

**Comment by burtonator** [comment]
k.. def need to fix this as part of 2.0

**Comment by burtonator** [comment]
This is the DOM inspector?

**Comment by sopoforic** [comment]
Yes.
