### ISSUE TITLE
Flashcard creation out of sync

### ISSUE THREAD

**Issue by sopoforic** [burtonator/polar-bookshelf#1472]
2.0 beta 20 on Chrome 84.

Creation of flashcards does not seem to 'commit' until an additional new card is created.

# Steps to reproduce

1. Create a highlight and click the lightning bolt to create a card.
2. Write on front and back "Card 1".
3. Press "Create".
4. The card vanishes--the interface disappears but no card annotation appears in the sidebar.
5. Press the lightning bolt to create another card.
6. Write on the front and back "Card 2".
7. Press "Create".
8. Now the card "Card 1" shows up in the sidebar. "Card 2" is not shown.
9. Repeat to create a "Card 3".
10. Now both "Card 1" and Card 2" are shown, but not "Card 3".
11. Refresh the document.
12. When the document loads, both "Card 1" and "Card 2" are shown. "Card 3" has been lost.

**Comment by burtonator** [comment]
Closing this as I can't duplicate it but this may have been fixed as I spent a ton of time working on this codel

**Comment by sopoforic** [comment]
Yeah, this seems to be fixed.
