### ISSUE TITLE
Empty folders behave weirdly

### ISSUE THREAD

**Issue by sopoforic** [burtonator/polar-bookshelf#1473]
2.0 beta 20 on Chrome 84.

I have a folder structure like:

```
/
/genre
/genre/nonfiction
/type
/type/webpage
/type/book
```

Clicking the (empty) folder `/genre` shows all documents. I would expect it to show all documents with either `/genre` or one of its children assigned.

Furthermore, if I assign `/genre` to a document and then remove that tag, now clicking `/genre` shows no documents. I presume that the empty tag object remains and is overriding the previous behavior. Right-clicking on the empty folder and 'deleting' it restores the previous (but still incorrect!) behavior.

**Comment by burtonator** [comment]
K... will investigate this as part of 2.0.0 release.

**Comment by sopoforic** [comment]
I'm still seeing this behavior in beta 29.
