### ISSUE TITLE
"Mark Entire Document as Read" does not update progress on main screen

### ISSUE THREAD

**Issue by sopoforic** [burtonator/polar-bookshelf#1476]
2.0 beta 20 Chrome 84.

In an EPUB, I had a pagemark about halfway through. This progress was correctly reflected both inside the document viewer and on the main document repository screen.

I right clicked on the document and selected "Mark Entire Document as Read". This correctly extended the pagemark over the whole document, and the progress meter inside the viewer updated to be all blue. However, the progress meter on the main document list screen did not update.

Refreshing the document correctly retains the pagemark and full progress bar.

Refreshing the document list incorrectly retains the previous incomplete progress amount.

**Comment by burtonator** [comment]
I can't duplicate this... there's a slight delay for the snapshot to make it to the main document repo though. It's about 10s... I'm going to check into this as a separate issue as it should be instant.
