### ISSUE TITLE
Full screen view doesn't work twice in a row

### ISSUE THREAD

**Issue by jgraeupner88** [burtonator/polar-bookshelf#1479]
**Describe the bug**
Clicking on fullscreen view icon in the doc viewer works the first time around but not a second time. need to open doc again. Also, let' use F11 as a shortcut for this feature (G Chrome and others use that too)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by burtonator** [comment]
Might also want to have a key binding for this.

**Comment by jgraeupner88** [comment]
Yes, you mean F11 in the suggestion? That's what G Chrome etc uses
