### ISSUE TITLE
Naming for keyboard shortcuts

### ISSUE THREAD

**Issue by jgraeupner88** [burtonator/polar-bookshelf#1480]
**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

https://opencollective.com/polar-bookshelf

**Describe the bug**
When opening the keyboard shortcut window in Polar, let's rename it to 'Active keyboard shortcuts'

**To Reproduce**
1. Go to anywhere in Polar and open the keyboard shortcut dialog box

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by burtonator** [comment]
IT's renamed now.
