### ISSUE TITLE
Text confusing when opening original URL in file

### ISSUE THREAD

**Issue by jgraeupner88** [burtonator/polar-bookshelf#1481]
**Describe the bug**
Text for captured webpage URLs is confusing. See below how to change

**To Reproduce**
1. Open any document
2. Click on the overflow menu at the top right. That text needs to be changed to "Open original URL in browser" and "Copy original URL to clipboard"

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by burtonator** [comment]
Is it an error or you just want the text changed?

**Comment by jgraeupner88** [comment]
Change the text so it’s clear we mean the original URL not Polar’s generated URL for this file
