### ISSUE TITLE
Old starter documents being restored on new browser sessions

### ISSUE THREAD

**Issue by spepakay** [burtonator/polar-bookshelf#1482]
**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

https://opencollective.com/polar-bookshelf

**Describe the bug**
Every time I login to my account on the web (http://app.getpolarized.io) on a new browser (on a new machine), all the starter documents (google whitepapers on borg, dremel etc) are restored

**To Reproduce**
1. Login to your account on your existing browser (let's say it is Chrome)
2. Delete the starter documents (Google whitepapers on Dremel, Borg, MapReduce etc)
3. For good measure delete all the tags and folders as well
4.  Now start  a new browser session (maybe Opera or Safari or Firefox). Don't use the Chrome browser you used in step 1 to 3. Or you can start a new incognito session in Chrome
5. Login to your account
6. See all the deleted starter documents (Google whitepapers) reappear

**Expected behavior**
I would expect the state of my Document Repository to be preserved across sessions on different machines and different browsers.

**Comment by burtonator** [comment]
This is fixed in 2.0...
