### ISSUE TITLE
First character ignored in tagging

### ISSUE THREAD

**Issue by sopoforic** [burtonator/polar-bookshelf#1484]
2.0 beta 25 on chrome 84.

When adding tags to a document, the first character typed is ignored.

# Steps to reproduce

1. From the document list, select a document.
2. Press `t` to open the tag window.
3. Type `hello`.
4. Notice that the box contains `ello`. The initial `h` merely opens the autocomplete dropdown.

This behavior is also exhibited after selecting a tag to add--the next letter typed is ignored.

**Comment by burtonator** [comment]
Ah... this bug again.  OK.  Going to fix it in 2.0.0

**Comment by burtonator** [comment]
Will be fixed in next release.
