### ISSUE TITLE
Pressing enter on tag box gives unexpected behavior

### ISSUE THREAD

**Issue by sopoforic** [burtonator/polar-bookshelf#1486]
2.0 beta 25 on Chrome 84.

Pressing `Enter` to close the tag box instead cycles between two states. Observe the document at the top, "Fading Foundations":

![chrome_kHopJmbXt3](https://user-images.githubusercontent.com/78205/93386166-4bfc4300-f835-11ea-8c14-fae0b14117fe.png)
![chrome_Mpk7QRe6CZ](https://user-images.githubusercontent.com/78205/93386202-5b7b8c00-f835-11ea-94e4-29ad6c540cad.png)

Notice the collection of tags on the first image is not actually on any document at present; I'm not sure where they're pulled from. Also notice that the tags column is *blank* in the second image--evidently, pressing `Enter` is not actually setting the tags, or at least they're not getting displayed. In any case, pressing `Enter` on the first image produces the second, and vice-versa. Pressing the "Done" button correctly commits the tag changes and dismisses the box.

**Comment by sopoforic** [comment]
It's not visible in those screenshots, but when I first encountered the bug, the "Fading" doc had an updated time of 10 days, and pressing `Enter` was switching the display there between "a few seconds" and "10 days", so it seems like it was restoring the old state.

**Comment by sopoforic** [comment]
This also appears to happen (perhaps unsurprisingly) when using the tag box from within a document.

**Comment by burtonator** [comment]
Nice... ok.  Going to try to debug this one too.

**Comment by burtonator** [comment]
I'm not getting this at all.. what OS?

**Comment by sopoforic** [comment]
Windows 10, using Chrome 84.

**Comment by sopoforic** [comment]
In this GIF, you can see the tags switching between the old and new states when I hit enter:

![y9xf8haebY](https://user-images.githubusercontent.com/78205/93511576-0e5cf000-f8f1-11ea-8d26-0ce0a73270cb.gif)

**Comment by burtonator** [comment]
I think this was a bug in our old keyboard handling systme which is now fixxed.

**Comment by sopoforic** [comment]
Still happening in beta 28.

**Comment by sopoforic** [comment]
This still happens in beta 29.
