### ISSUE TITLE
Sometimes duplicate tags can be added

### ISSUE THREAD

**Issue by sopoforic** [burtonator/polar-bookshelf#1487]
2.0 beta 25 on Chrome 84.

Sometimes, duplicate tags can be added:

![chrome_p0YMwSOada](https://user-images.githubusercontent.com/78205/93387372-1bb5a400-f837-11ea-961b-cb1bd9f6786e.png)

I don't know exactly what makes this possible--usually it would display "No options" when typing a duplicate tag, but after messing around with it a bit, this happened. Closing the tag box and reopening it gives the usual behavior.

In this state, typing out the tag `no` and hitting `Enter` will remove one of the existing `no` tags, but pressing `Tab` will add a duplicate.

**Comment by burtonator** [comment]
This is when they are NEW tags that haven't been created yet and aren't in the index.  Should be easy to disallow them.

**Comment by burtonator** [comment]
This seems like a valid one and I can reproduce.

**Comment by burtonator** [comment]
should be fixed in the next rellease.

**Comment by sopoforic** [comment]
This still happens in beta 28.
