### ISSUE TITLE
Characters n and p 'break' the search as they are PDF viewer hotkeys intercept text

### ISSUE THREAD

**Issue by sopoforic** [burtonator/polar-bookshelf#1489]
2.0 beta 25 on Chrome 84.

When typing in the search box or annotations in the PDF viewer, attempting to type `n` or `p` instead changes pages. These letters cannot be typed. Perhaps there are other hotkeys also intercepting keypresses too eagerly.

**Comment by burtonator** [comment]
> These letters cannot be typed. Perhaps there are other hotkeys also intercepting keypresses too eagerly.

AHAHA!!! ok... that's a bug. I'll take a look at these.

**Comment by burtonator** [comment]
This is a good find.  Going to fix it in the 2.0.0 release.

**Comment by burtonator** [comment]
nice... fixed it and will be resolved in the next release.
