### ISSUE TITLE
Highlight color icons do not appear on webpage highlights

### ISSUE THREAD

**Issue by sopoforic** [burtonator/polar-bookshelf#1494]
2.0 beta 26 on Chrome 84, Windows 10.

When highlighting text in a captured webpage, the highlighter icons used to select the color do not appear:

![chrome_TCXIKreqpB](https://user-images.githubusercontent.com/78205/93514200-e96a7c00-f8f4-11ea-9451-ab11e6b66ebc.png)

These display correctly on the PDF viewer.

**Comment by burtonator** [comment]
Thanks.  this is a recent regression that I'm trying to track down.  I'm going to fix it for 2.0.0

**Comment by burtonator** [comment]
Fixed
