### ISSUE TITLE
Trouble importing and tagging documents

### ISSUE THREAD

**Issue by clara-k-rhoades** [burtonator/polar-bookshelf#1497]
**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

https://opencollective.com/polar-bookshelf

**Describe the bug**
Each time I try to import a certain document, Polar says it doesn't exist. Which is weird because I can open if from my files. I've also gone through and tagged many of my documents only to have those tags disappear. 

**To Reproduce**
1. Go to '...' File
2. Click on '....' Import from files
3. Scroll down to '....' Try to import a document, then open it

**Expected behavior**
Tags to remain on documents and documents to open correctly

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Downloaded
 - Version [e.g. 22] shrug emoji

**Smartphone (please complete the following information):**

**Additional context**

**Comment by burtonator** [comment]
This is on 1.x?

**Comment by burtonator** [comment]
Cant fix without more detail

**Comment by clara-k-rhoades** [comment]
[image: image.png]
took me a minute to find this - sorry!

**Comment by clara-k-rhoades** [comment]
also this keeps happening to one of my documents, and makes it so i can't
highlight >.<
[image: image.png]
