### ISSUE TITLE
Missing PDF (sometime)

### ISSUE THREAD

**Issue by jgwill** [burtonator/polar-bookshelf#1498]
**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

https://opencollective.com/polar-bookshelf

**Describe the bug**
Openning PDF are missing then it might be ok for some reason.

**To Reproduce**
1. Add a PDF open it
2. Close it, close polar
3. Open Polar, open PDF
4. Hope the bug reproduce 

**Expected behavior**
PDF Opens all the time

**Screenshots**

![image](https://user-images.githubusercontent.com/23141173/94345233-819dea80-fff2-11ea-846e-da8b65460df1.png)

**Desktop (please complete the following information):**
- Windows
- Polar 1.100.13

**Additional context**

**Comment by burtonator** [comment]
Thanks. This is probably fixed in Polar 2.0 which we're working to have out the door soon.
