### ISSUE TITLE
Cannot open any epub file on macOS app

### ISSUE THREAD

**Issue by russellwheatley** [burtonator/polar-bookshelf#1531]
**Describe the bug**
Cannot open any `.epub` files.

**To Reproduce**
1. Open app
2. Click on 'Add files from disk' and select any `.epub` file

**Expected behavior**
To open epub book.

**Screenshots**
I get this error for every book I tried to open.
<img width="418" alt="Screenshot 2020-10-10 at 13 38 06" src="https://user-images.githubusercontent.com/16018629/95655305-2f82bc00-0afe-11eb-9094-489c8fc05251.png">

**Desktop (please complete the following information):**
 - OS: macOS v10.15.4
 - Version Polar Bookshelf v1.100.13

**Additional context**

**Comment by burtonator** [comment]
This is 1.x... This is resolved on 2.x
