### ISSUE TITLE
Can't use Polar without an account

### ISSUE THREAD

**Issue by m0wer** [burtonator/polar-bookshelf#1534]
**Describe the bug**
I can no longer use the Polar desktop app without registering.

**To Reproduce**
1. Install Polar desktop app.
2. Start it.

**Expected behavior**
Login should be optional for those who want to use cloud services.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian

**Additional context**
I have been using Polar without an account for a long time. This was possible until the 2.0 upgrade.

**Comment by burtonator** [comment]
Yes... this is expected and an online account is required in 2.0.  You can drop your .polar directory into the new app to migrate your data.  

You can read about the cloud migration decision in https://reddit.com/r/PolarBookshelf  where we talked about it at length.  I can give you specific links if you want.

Also talked about it a bit here:

https://getpolarized.io/2020/10/05/Polar-2-0-Release.html

We have a final 1.x which doesn't auto-update if you need to stay with 1.x but it won't be maintained any more.

https://www.reddit.com/r/PolarBookshelf/comments/j9yfbx/polar_110014_last_1x_version_with_autoupdates/

**Comment by JJger148** [comment]
I just got excited about polar but then quickly disappointed that it is a cloud app.
I had nasty experiences with Notion and Remnote, which made me stay far away from depending on cloud services. 
For those who are disappointed like me, there is hope that [keypoints](https://keypoints.app/ )will be available soon.
