### ISSUE TITLE
Can't write line breaks in comments

### ISSUE THREAD

**Issue by vonHartz** [burtonator/polar-bookshelf#1537]
**Describe the bug**
When writing a comment, pressing "enter" closes the editor. It is hence not possible to have line breaks. Also Shift + Enter doesn't work.

**To Reproduce**
1. Create a mark.
2. Create a comment.
3. Write something and press Enter or Shift + Enter.

**Expected behavior**
For Shift + Enter a line break should be produced

**Desktop (please complete the following information):**
 - OS: Linux, desktop app
 - Version: current

**Comment by burtonator** [comment]
You want '<hr>'  to display I assume?

**Comment by vonHartz** [comment]
No, it was really just about line breaks as I like to have lists in my comments. Something like:

> - Observation 1
> - Remark 1
> -> Conclusion

However, I updated to v 2.0.53 and it works again.
Thanks, I'll close this.
