### ISSUE TITLE
Files deleted when syncing PDFs to web

### ISSUE THREAD

**Issue by jaredtumiel** [burtonator/polar-bookshelf#1543]
**Describe the bug**
When creating an online Polar account and the local app first syncs PDFs to the cloud, larger PDFs (100s of pages) with many annotations (file size of the state.json file >1MB) get the error "Unable to sync between source and target" and then the files are removed from the library

**To Reproduce**
1. Have version 1 installed
2. Click on 'login', create an account and start file upload
3. See error 'cannot sync between source and target'
4. files are removed from library

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 1.100.13

**Comment by jaredtumiel** [comment]
Some extra info after playing around to see what I could fix:
I tried reinstalling Polar 1.0 and that at least gave me my library back as it was.

I then tried dragging and dropping the .polar file to the Polar 2.0 webapp. This gives the following Internal Error: An internal error has occurred: FirebaseError: [code=invalid-argument]: Property value contains an invalid nested entity.

I have isolated this to occur only with the state.json files in the folders of the PDFs that did not originally sync to the cloud. If I remove those folders and retry I do not get the error.

**Comment by burtonator** [comment]
This is a Polar 1.x bug... We're not going to be fixing Polar 1.x bugs any longer and focused on 2.0.

That said.  The issue you're having is probably because you have a lot of screenshots. We're specifically addressing this bug in 2.0 to improve stability.
