### ISSUE TITLE
Did backend just crashed?

### ISSUE THREAD

**Issue by glitchlover** [burtonator/polar-bookshelf#1551]
**Describe the bug**
Cannot open any kind of PDF

**To Reproduce**
1. Go to 'polar'
2. Click on 'any PDF'
Error 503 Backend.max_conn reached
Backend.max_conn reached

Guru Mediation:
Details: cache-sin18046-SIN 1605541758 756117280

Varnish cache server

**Expected behavior**
Just want to see the polar stuff

**Screenshots**
![image](https://user-images.githubusercontent.com/59877631/99275908-42538380-2856-11eb-99d8-411cab4ae0c8.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Microsoft Edge]
 - Version [2.0.78]

**Additional context**
I can not go to polar web page either. But my internet is fine. Is there any backend problem?

**Comment by burtonator** [comment]
That's super odd... No backend problems that I know of.  Still having the same problem?

**Comment by glitchlover** [comment]
Hmm, it is weird 😕. Sorry for the late reply though
The problem persist until I reinstall polar. I don't know what happened.
