### ISSUE TITLE
Navigation to context from Highlight

### ISSUE THREAD

**Issue by jgwill** [burtonator/polar-bookshelf#1557]
**Is your feature request related to a problem? Please describe.**

In previous Polar, we were able to contextual click on an highlight and click some option to select it in the annotation panel, that is gone in the latest.

**Describe the solution you'd like**
Add a sub-context menu "goto annotation context"

**Describe alternatives you've considered**
ALT+click

**Additional context**
NOTE

**Comment by burtonator** [comment]
It's fixed and will be in the next version. Thanks!

**Comment by jgwill** [comment]
Great
