### ISSUE TITLE
Please re introduce the feature to 'Collapse / Expand Headings and Subheadings in the Left Sidebar'

### ISSUE THREAD

**Issue by SaravananDr** [burtonator/polar-bookshelf#1558]
A clear and concise description of what the problem is. Ex. I have more than 100 Medical textbooks which have 500 or higher subheadings each, in which i need to search for a certain topic only through the left sidebar headings and sub headings. This was easily done in the previous Polar 1.x version, where it was easy to collapse the sub headings, so only the Main few titles show, but now its always expanded and this has made Polar2.0 a bit less convenient for Regular use.
![image](https://user-images.githubusercontent.com/74894502/99934855-39e2d780-2d85-11eb-82a9-9231f9bd0b03.png)

Please add someway to collapse and expand all bookmarks. The simplest solution would be make it similar to how it was in the previous version, where double click on the toolbar button is collapse all / expand all.

Any other way like a keyboard shortcut to collapse / expand all headings is also welcomed.
I am a Plus user, But please do consider adding this small feature from the old build for your Loyal User.

**Comment by burtonator** [comment]
Thanks.. prioritized it and will probably be fixed in a week or so.  Do you think we need to persist the expand/collapse state ?

**Comment by SaravananDr** [comment]
Thanks a lot

By 'Persisting' collapse state, If you mean by 'remember the way it was left, so during closing and reopening it stays the same way as left before',
I don't personally feel there is any necessity for it because I always collapse all, then search for the required topic by expanding a certain heading.

Please design it however you feel its necessary but I would prefer a completely collapsed contents when i open a document

Thanks and Regards

**Comment by burtonator** [comment]
![image](https://user-images.githubusercontent.com/45447/100264690-683eef00-2f0c-11eb-9d19-6ebf8f17f82f.png)
something like that? 

this will go into the next release. We usually push 1-2 per week.

**Comment by SaravananDr** [comment]
Yes please, make sure that all headings can be collapsed at once with a single press and all expanded at once in a single press (like in the polar 1.x), in addition to collapsing single headings one by one manually as shown in picture

Thanks a lot
