### ISSUE TITLE
Some documents don't show up in the document index / list despite being saved by app

### ISSUE THREAD

**Issue by joelstrouts** [burtonator/polar-bookshelf#1563]
I have a file "Notes Week 3.pdf" which I have uploaded to polar. When I first uploaded it I did not see it appear in the document index, so instead I opened it by clicking the "would you like to open now" popup that appears.

I worked on this document, made annotations etc. but when I came back to read the document another day, I still couldn't find it listed in the index. I also couldn't find it by searching its name.

Thinking my work was lost, I went to re-upload the document and start again - and the same thing happened: the document didn't appear in the list but the popup let me open it AND the annoations I made in a previous session were still there.

If I add a new tag to the document whilst it's open (eg: 'foo') then a new entry appears in the tag sidebar like: "Foo ... (1)", but if you click that tag it just shows an empty document list. So it looks like everything ELSE is working fine, its just not showing up in the list for some reason.

Changing the name of the document being uploaded changes nothing.

So:
this document is saved by polar but only accessible by clicking that 'open now' popup prompted by re-uploading the document because it doesn't show up in the index.

So far I've only noticed this problem with this one document

**Comment by joelstrouts** [comment]
Turns out it was archived.

**Comment by burtonator** [comment]
Thanks Joel... we have another bug where something is accidentally archiving documents and confusing people.  We're trying to figure out what's happening here.
