### ISSUE TITLE
anki sync problem

### ISSUE THREAD

**Issue by Mingjined** [burtonator/polar-bookshelf#1576]
**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

https://opencollective.com/polar-bookshelf

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by burtonator** [comment]
Totally happy to fix this for you but you'd need to explain what the problem was.
