### ISSUE TITLE
Polar connect anki sync add-on issue

### ISSUE THREAD

**Issue by Mingjined** [burtonator/polar-bookshelf#1577]
oh! sorry for the mistake before. ( I am new to github)
The problem:
the polar conncet anki add-on doesn't show up when I click -" Polar connect for anki sync".
when I click on it, the following message shows-
"This shared item is no longer available."
I'd like some help regarding this issue
(in case its required, I have ankiconnect add-on already) 
![2021-01-08](https://user-images.githubusercontent.com/73438631/103934335-cfc29e00-514a-11eb-96c6-a358a71be3c1.png)

**Comment by burtonator** [comment]
In Polar 2.0 ?  I don't think we link to that

**Comment by Mingjined** [comment]
> In Polar 2.0 ? I don't think we link to that

Then, what should be done now? The add-on doesn't work for the version? Or are their different versions? I downloaded polar from microsoft store just a few hours ago.

**Comment by Mingjined** [comment]
> In Polar 2.0 ? I don't think we link to that 

I got it.. it was ankiconnect update that was causing error in anki. The problem is solved now. 
sorry for disturbing needlessly. and Thanks for showing up to help.

Polar bookshelf is truly a jewel for me. Thankyou very much developers for such a great tool. Lots of love for the bookshelf.
