### ISSUE TITLE
Install in a drive other than C:

### ISSUE THREAD

**Issue by tomtinker** [burtonator/polar-bookshelf#1597]
Does anyone know how to install Polar in a drive other than C:? 
My C: drive is a non-expandable SSD on a laptop, and I cannot upgrade Windows 10 because there is not 
enough space in C:. Checking the software in my drive, I found Polar is taking up more than a half a gigabyte 
just for the program - not including the data. Only Adobe takes up more space.
I really like Polar, and don't want to have to uninstall it. How can I move or reinstall Polar on a different drive?

**Comment by burtonator** [comment]
No way to install on another drive right now unfortunately.
