### ISSUE TITLE
Spaced Repetition Algorithms for documents

### ISSUE THREAD

**Issue by danielpatrickhug** [burtonator/polar-bookshelf#1602]
Hi Everyone,

 Is there anyway to add the spaced repetition algo to the document list? So, my reading materials are automatically recommended to me instead of having to do it manually? 

Thank you

Edit: I would be happy to work on it if someone could give me a quick run down of the structure of this repo and point me in the right direction.

**Comment by burtonator** [comment]
Could you submit this as a feature request here: 

https://app.getpolarized.io/feature-requests
