### ISSUE TITLE
Distribute Polar with some PDF files and PHZ files.

### ISSUE THREAD

**Issue by burtonator** [burtonator/polar-bookshelf#179]
This way the user has documents in their repository when they first launch the app.

**Comment by SitiSchu** [comment]
Could put the Help(bottom part of the readme) as one of the Documents.
I could write a simple LaTeX Document for that.

**Comment by burtonator** [comment]
It would be nice if we actually had some markdown -> html generator or something.

**Comment by SitiSchu** [comment]
pandoc should be able to do that

**Comment by danieltomasz** [comment]
This is a planned behaviour? I am getting these files  even if I delete them 
![schermafdruk_2019-02-22_17-45-50](https://user-images.githubusercontent.com/7980381/53257258-fba91780-36c9-11e9-8153-4effe6df74e4.png)

**Comment by burtonator** [comment]
Ah. OK. It's a bug. You're probably getting them if you delete and restart without adding anything.

I'll fix it in the next release

**Comment by burtonator** [comment]
Thanks.. this is fixed now and will be patched in the next release.
