### ISSUE TITLE
Windows 10 warning on startup due to lack of code signing

### ISSUE THREAD

**Issue by albertotn** [burtonator/polar-bookshelf#186]
Windows on program startup tells me, with a big warning that app is not trusted ( because is not signed with a certificate ?), this could be a potential problem with new users

**Comment by burtonator** [comment]
Agreed... this should be fixed in the next release.

**Comment by burtonator** [comment]
And thanks for reporting this.

**Comment by albertotn** [comment]
works perfectly, thanks!
