### ISSUE TITLE
Moving a pagemark seems to move the page on windows.

### ISSUE THREAD

**Issue by burtonator** [burtonator/polar-bookshelf#198]
https://www.youtube.com/watch?v=havT8mNKsqA&feature=youtu.be

**Comment by SitiSchu** [comment]
Only if the Hand Tool is selected though

**Comment by burtonator** [comment]
OH!!! the hand tool!!! AHA! I might have to disable that :-/

**Comment by burtonator** [comment]
is that super required for your usage?

**Comment by burtonator** [comment]
unfortunately, none of those options in that pulldown would probably work so I will have to disable them for now.  I can try to rescurrect them in the future but they're just going to break.

**Comment by SitiSchu** [comment]
Just something I noticed...it's not too horrible if it happens ^^ I'll just have to remember to switch tools ¯\_(ツ)_/¯

**Comment by burtonator** [comment]
Is it something you actively use? I'm removing them in the next release as they're just bugs and not usable in the current form.

**Comment by SitiSchu** [comment]
The hand tool is quite useful since I'm using a graphic tablet and it makes moving around files a bit easier if I can just drag the pdf.
