### ISSUE TITLE
Need a strategy for mapping decks in Anki.

### ISSUE THREAD

**Issue by burtonator** [burtonator/polar-bookshelf#250]
Right now we create a deck per book. So if you're reading: "War and Peace" you will get a deck every time you sync at / for "War and Peace" ...

This prevents you from moving it to another deck as a sub-deck.

I need some way to map it from the deck to the sub-deck if it's moved.

One idea could be to move the books based on tags... so if you tag it the book 'deck:foo' then  all the flashcards there get stored into that deck in Anki.  

Right now we don't support colons in tags but we could.

**Comment by zo34** [comment]
I think there are two things going on here: first, a source document reference for flashcards, and second, a destination deck for the flashcards.

If we use a tag for the source document it will be easy for users to grab a set of cards from some source document, regardless of what deck they are stored in. This would also allow Polar to find all cards related to that source document.

Then there's the issue of where the cards go. We could automatically set some default base deck for each document, and allow the user to override this setting (perhaps from the document navigator). This setting would propagate to the flashcard builder, where the user (if they chose) could point the card to a deck of their choice.

This allows a direct reference to the source document of a card, as well as source agnostic deck locations.

**Comment by zo34** [comment]
> You mean the source would be the name of the book?

Yes.

> It might also be nice to map certain tags to decks.

Do you mean that a tag would be mapped (that is, unique) to a specific deck?

**Comment by burtonator** [comment]
> Do you mean that a tag would be mapped (that is, unique) to a specific deck?

Yeah. the 'bitcoin' tag would go to the CompSci/Bitcoin deck for example.

**Comment by zo34** [comment]
> Yeah. the 'bitcoin' tag would go to the CompSci/Bitcoin deck for example.

So, if I were to use that tag, would it override the default deck (assuming a default has been implemented)? Anki has a custom study feature that allows selection of cards by tag. I don't think that quite covers what you've described, though. I could see this being really useful for collating a large number of sources into a single CS deck (or other domain specific deck) on the fly.
