### ISSUE TITLE
Display tag values in the main document repository

### ISSUE THREAD

**Issue by lazear** [burtonator/polar-bookshelf#273]
It would be really nice to be able to see what tags have been applied to a document without clicking on the tag icon. Is it possible to have the tag values visible in a column?

**Comment by burtonator** [comment]
It's possible just not implemented yet. How would they be displayed?  comma separated and sorted alphabetically?

**Comment by lazear** [comment]
Yeah that would probably work. Perhaps display however many tags will fit within the current column width? Not sure if that's possible, no real experience with JS.

My only other feature request would be the ability to drag a file onto the repository window and have it added to the document repository.

This is an **awesome** idea by the way. Really cool way to organize all of the research papers I need to read.

**Comment by burtonator** [comment]
I can clip the tags... so you would see "..." at the end.

It looks like I can toggle visibility here:

https://react-table.js.org/#/story/readme

via 'show' on the column header:

    show: true,

... 

so I guess I could just have a pulldown for which columns should be displayed.  

I'm getting more familiar with React so these things are becoming easier.  :)

https://github.com/burtonator/polar-bookshelf/issues/274

is a bug for drag and drop of the files. It's a good feature suggestion.  I might also make it related to importing from a directory.  I might do the recursive directory import first.

**Comment by burtonator** [comment]
We can use something like this for the CSS / UI for the drop down:

https://codepen.io/bseth99/pen/fboKH

**Comment by burtonator** [comment]
https://stackoverflow.com/questions/23103567/bootstrap-dropdown-checkbox-select
