### ISSUE TITLE
[Feature Request] Keyboard accelerators for menu items

### ISSUE THREAD

**Issue by EvanAnderson** [burtonator/polar-bookshelf#282]
I'm using Polar Bookshelf on Windows. It's disorienting not to be able to use "traditional ALT-F, ALT-W, etc keyboard accelerators to open the pull-down menus.

**Comment by burtonator** [comment]
oh.. Alt-F would open the file menu for example?

**Comment by EvanAnderson** [comment]
Exactly. I'm a heavy keyboard user and it would significantly increase the operating speed of the application to have those shortcuts. From a Windows-centric I typically expect the first letters of the menu items to be keyboard accelerators. Typically there would be accelerators on the individual menu items, as well. Some people would do CTRL-O, I'd do ALT-F / O, expecting ALT-F to open the "File" menu, and "O" to grab the "Open" menu item. I consistently find myself using the pull-down menus in lieu of CTRL-based accelerators. I think it's a fairly standard use-pattern for long-time Windows users, albeit one Microsoft has moved away from w/ the Ribbon in Office.

(I know this isn't the place, but I'm really, really liking the look of Polar Bookshelf. My head is dancing with ideas... plugin to syndicate document URLs and annotations via RSS/Atom, etc.)

**Comment by burtonator** [comment]
> From a Windows-centric I typically expect the first letters of the menu items to be keyboard accelerators

Yeah.  The main issue I'm struggling with right now is how to map them across platform. I think I'm going to re-work this code as it's hard to map everything properly the way Electron does the menu hierarchy.

I think what I'm going to do is create a generic menu structure, then tag it with platform specific changes after the fact.

For example.  on OS X I need a "Polar" menu to go BEFORE the File menu.  

So I can't just have a generic structure any more so I need some way to add custom platform extensions and custom bindings.  

Baby steps. A lot of this stuff will come online shortly.

Feel free to send PRs :) .. I can give you a pointer to the code. It's in MainAppMenu.ts I think.

**Comment by EvanAnderson** [comment]
I'm pretty much Windows-only. If I can find one of my "Mac-friends" who finds this interesting I'll consider making a PR after having them test. I've never done any Electron development before-- looks interesting. The platform-specific stuff is what I'd assume would be-- ahem-- challenging.

re: the pointer to the code -- Yeah, that's where I found it. Good deal.

**Comment by burtonator** [comment]
It's not super hard. I think if we just modeled this as a JSON unit test it would be best.  Basically take the generic menu structure, then mutate it so that it has the right Windows bindings.  

Running polar from source is easy. Just npm install and npm start ... easy to start hacking on.

**Comment by burtonator** [comment]
I think it might support accerators for the individual items but not the high level items like File... Goign to need to figure out a solution here.

**Comment by burtonator** [comment]
You can configure different key combinations based on the user's operating system.

{
  accelerator: process.platform === 'darwin' ? 'Alt+Cmd+I' : 'Ctrl+Shift+I'
}
