### ISSUE TITLE
Feature: ability to mark a range of pages read.

### ISSUE THREAD

**Issue by burtonator** [burtonator/polar-bookshelf#283]

**Comment by boxxxie** [comment]
some feedback on how do go about solving this problem would be nice...
like where to look in the code base, or some thoughts on what needs to be changed, or if there are some related tests to this feature and what they may be named or what files they may be in.

**Comment by burtonator** [comment]
Honestly I think all that needs to happen is for you to stick a new 'pagemark' in into the docMeta... 

pagemarks/controller/PagemarkController.ts

Pagemarks.updatePagemark(this.model.docMeta, pageNum, pagemark);

... if the pagemark is actually updated directly on the docMeta the view updates.  

there would also need to be a popup asking for the range (pages M...N). We could probably just trigger it via the menu and then bring up a reactstrap modal dialog prompting for the range.

**Comment by burtonator** [comment]
We can do this with the new popup support in the doc dropdown now.  Should be a matter of a simple component and form range.
