### ISSUE TITLE
Flag/unflagging an item too quickly opens the document

### ISSUE THREAD

**Issue by setr** [burtonator/polar-bookshelf#292]
Counts as a double-click; works on any button though only the important marker would realistically hit the issue

Opening documents by double-click should probably be limited up to the end of the progress bar

**Comment by burtonator** [comment]
Ah.  Thanks.  This is a good point.  

I think this could be a good first issue for someone to solve.  

This should be in:

apps/repository/js/App.tsx

```
                    getTrProps={(state: any, rowInfo: any) => {
                        return {

                            onClick: (e: any) => {
                                this.highlightRow(rowInfo.index as number);
                            },

                            onDoubleClick: (e: any) => {
                                this.onDocumentLoadRequested(rowInfo.original.fingerprint, rowInfo.original.filename);
                            },

                            style: {
                                background: rowInfo && rowInfo.index === this.state.selected ? '#00afec' : 'white',
                                color: rowInfo && rowInfo.index === this.state.selected ? 'white' : 'black',
                            }
                        };
                    }}

```

I think move the onDoubleClick to the getTdProps below and only add the double click on the main 'title' column.

I think that's all that's needed to fix this.

**Comment by xuebingli** [comment]
The fix looks straightforward. I'm happy to give it go.

**Comment by burtonator** [comment]
Go for it. I'll merge it from a pr if it looks good
