### ISSUE TITLE
Captured doc 'Truncated' after captured.  

### ISSUE THREAD

**Issue by fourcube** [burtonator/polar-bookshelf#305]
OS: MacOS Mojave (10.14)

**Steps to reproduce:**
Try to capture: https://solidity.readthedocs.io/en/develop/abi-spec.html

**Problem:**
Only a part of the page is captured, even though it looks okay in the preview browser.

This is an awesome project! Thank you!

**Comment by burtonator** [comment]
The document.body.scrollHeight of that page is off.. VERY weird.. I'm not sure how that's even possible.

It's scrolling for me just fine.

Clearly there is something I don't understand here.

**Comment by burtonator** [comment]
And the IFRAME scrolling is working so the iframe thinks it's large...

**Comment by burtonator** [comment]
lookos like it needs to be iframe.contentDocument.documentElement.scrollHeight

**Comment by burtonator** [comment]
OK.. I think I have a fix for it now.  Good catch and thanks for reporting this.

**Comment by fourcube** [comment]
Wow that was quick, thanks!
