### ISSUE TITLE
Issues with Capturing GitHub 

### ISSUE THREAD

**Issue by chibicode** [burtonator/polar-bookshelf#308]
Hi there, this is an amazing app! For me the main case would be to save READMEs on GitHub offline. But I noticed a few issues (version 1.03 / Mac):

- When you try to capture GitHub, by default it captures mobile UI. I have to set the user agent to Chrome Desktop every time to capture the README content, which is sort of annoying.

<img width="800" alt="screen shot 2018-10-19 at 7 59 48 am" src="https://user-images.githubusercontent.com/992008/47226298-f848fc80-d374-11e8-83c1-c262d02e7428.png">

- For some reason, if you scroll down, there's a lot of empty content at the end:

<img width="800" alt="screen shot 2018-10-19 at 8 00 31 am" src="https://user-images.githubusercontent.com/992008/47226333-1ca4d900-d375-11e8-983e-f8a8be55c740.png">

This happens with every user agent. This actually won't get captured, but I thought was strange.

I couldn't find related issues (searched "github" or "user agent").

**Comment by burtonator** [comment]
> When you try to capture GitHub, by default it captures mobile UI. I have to set the user agent to Chrome Desktop every time to capture the README content, which is sort of annoying.

Sure but we have to pick some default and the mobile looks better for news articles.  

Is there an easier way you recommend to handle this?

**Comment by burtonator** [comment]
It actually works when you click "View all of readme" 

even with the mobile browser.

The preview is a full web browser so you can click on links, login, etc, until you're ready to hit the capture button.

**Comment by chibicode** [comment]
Thanks for your quick response, I guess the only actual issue is the second half (random blank section at the end).

**Comment by burtonator** [comment]
Oh , you mean the vast white space at the end which isn't really part of the document.

Nothing is missing there. That's an unrelated bug with our inability to properly resize the iframe. 

Iframe resizing is kind of non-sense and impossible to do and I don't have a decent work around for it just  yet.

**Comment by chibicode** [comment]
@burtonator I see, thanks! I'll close this then.
