### ISSUE TITLE
Poll / Discussion: Would a tabbed layout be better?

### ISSUE THREAD

**Issue by burtonator** [burtonator/polar-bookshelf#311]
I think we might be able to build out a tabbed UI using 

https://github.com/ctxhou/react-tabtab

What I would do is have a high level wrapper that launched the individual apps in <webview> elements.

This would isolate the webpps individually so that maintaining is easier since they're isolated.  

the default tab would be the document repository and I could build a drawer to the left for the document repository, then in the future an annotation repository UI, and then each doc would be opened in its own tab.

The capture system could use tabs too and it might be possible to just eventually make it into its own proper browser.

**Comment by goerz** [comment]
Personally, I think I prefer windows to tabs

**Comment by sandersantema** [comment]
I like tabbed programs. On OS's which have a proper window manager it might not be that important but on macOS I lose track of multiple loose windows. It's essential that these tabs work properly, if the behaviour is completely alien to how the macOS tabs work macOS users might for instance be better of with loose windows.
