### ISSUE TITLE
Suggestion: add command for capturing web page

### ISSUE THREAD

**Issue by sandersantema** [burtonator/polar-bookshelf#335]

**Comment by burtonator** [comment]
You mean a command line app?

**Comment by sandersantema** [comment]
No I wasn't clear sorry, I meant a keybinding (which is sometimes called a command on macOS).

**Comment by setr** [comment]
[cmd, ctrl]+N, of course! (what else could be new, but a capture?)

**Comment by burtonator** [comment]
Actually.. I think you're right!  That's a really good point!
