### ISSUE TITLE
Progress Bar is Not Visible

### ISSUE THREAD

**Issue by mlaradji** [burtonator/polar-bookshelf#368]
**Describe the bug**
The progress bar for all titles is always empty, regardless of actual reading progress. I am unsure whether this is a UI issue or a tracking issue. I can sort titles by the progress column in ascending or descending order and it is consistent, which suggests that some form of tracking is being done.

**To Reproduce**
This bug has always been present for me, and so if other people have the progress bar working fine, it suggests there's something wrong or different with my setup.

**Expected behavior**
I expected the progress bar to "fill up" as I read through a title.

**Screenshots**
https://github.com/mlaradji/polar-bookshelf/blob/master/Screenshot_20181101_162851_empty-progressbar.png

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.1
 - GUI: KDE
 - polar-bookshelf: 1.0.9 Rev 16 (snap)
 - snapd: 2.34.2+18.04

**Additional context**
None.

**Comment by burtonator** [comment]
You have to update the pagemarks... the reading progress depends on the pagemarks being updated.

I'm going to create a video here shortly explaining how to use Polar from a new user perspective.  

If you update the pagemarks the progress will be updated.

**Comment by panpiotrs** [comment]
I'd like to see how you are using this if you need to read something second time (let's say 10 pages of a book - are you deleting pagemarks and then redoing them or you just read with this overlay) or if you need to annotate something on pagemarked area. In the video https://www.youtube.com/watch?v=LfmvrzE7U-M you just scrolled to show how annotating works on area without pagemark. It's very nice feature overall, but I think it would be also very useful to see in bookshelf another column with progress computed in classical way: how deep you scrolled the document.
