### ISSUE TITLE
Deleting a flash card leaves the UI grayed out.

### ISSUE THREAD

**Issue by dulz01** [burtonator/polar-bookshelf#403]
Deleting a flash card from the sidebar leaves the UI grayed out. Unable to click on buttons with the mouse.
Requires me to reopen the document to fix the issue.

Edit: A little more information, I'm on version 1.0.13 and the issue shows up consistently whenever I try to delete a flashcard. This applies to all documents I've opened and it doesn't matter if I delete the flashcard straight after creating it or closing the document first before deleting it.

![deleting flashcard issue](https://user-images.githubusercontent.com/12128099/48321822-404efc80-e65f-11e8-8fde-e5e244b4049f.PNG)

**Comment by burtonator** [comment]
Wow. I don't have this problem but I'll try to duplicate

**Comment by likyng** [comment]
This also happens to me (1.0.3, Ubuntu 18.04, Node v11.1.0) when deleting a normal annotation. When I open the dev tools and set the `id="blackout"` div to `display: none` it works again. There is no error output in the console as far as I can see (no js experience...)

**Comment by burtonator** [comment]
ah.. you're right. I duplicated it so should be an easy fix.
