### ISSUE TITLE
Translation Software access seleted words support.

### ISSUE THREAD

**Issue by roachsinai** [burtonator/polar-bookshelf#416]
I'm using a translation software, and it support the immediate translation function: show the meaning of the words selected by mouse in Chinese(if I use mouse select a word, there is a samll tray beside the word, and show the word meaning in Chinese when I click that tray).

The software is also support Adobe pdf reader, but not work for pdf document opened by bookshelf.

**Comment by burtonator** [comment]
Not sure.. we won't be able to fix this as it's up to the app to add polar support...
