### ISSUE TITLE
Statistic page for keeping track of reading (pages per day) and motivating the users to read more

### ISSUE THREAD

**Issue by burtonator** [burtonator/polar-bookshelf#429]
We need to include analytics about the per repo file size but we also should include the length of the file, in bytes, in the DocMeta and DocInfo

- total number of documents
- total number of documents over time (we can use the 'added' to determine this metric)
- breakdown of the document type (PDF vs HTML)
- amount of reading you're doing per day (number of documents read per day) as a histograph
- length of streak in days and a github style chart like this:

![image](https://user-images.githubusercontent.com/45447/50550741-92a5a600-0c2a-11e9-8c67-5b73a5e96091.png)

**Comment by burtonator** [comment]
https://apexcharts.com/javascript-chart-demos/heatmap-charts/ 

apex charts supports a heatmap

**Comment by burtonator** [comment]
This one supports charts.js:

http://tmroyal.github.io/Chart.HeatMap/

**Comment by burtonator** [comment]
we're going to need SOME way to write additional metadata about documents after init... including the height + width of each page (or when that page is loaded) and we can also use this infra for taking thumbnails.

We could probably do some onPageLoaded event that I could hook info for this.. for PDF the onPageLoaded would have to work too but onPageLoaded for HTML would kick in once the iframe was rendered.

**Comment by burtonator** [comment]
the height+width would be to compute 'logical' pages not physical pages.. the physical page of HTML is just one long page.

**Comment by burtonator** [comment]
The problem I have now is what if the user marks multiple pages as read at once?  Are they counted as reading or not?

**Comment by burtonator** [comment]
Still not sure of the best way to handle this:

  - delete the read tracking?
  - disable the tracking temporarily.
  - change the 'type' of the pagemarks ... this would be a new feature but 'ignored' would work.  or something like 'previously read'

**Comment by danieltomasz** [comment]
Maybe rather than tracking  physical pages  is better to track  time when the app is open  and the there is focus on open window with pdf? is there a way to track it? this is an different idea than you propose but maybe you find it  useful. Anyway, your original idea of gamification of reading is great !

**Comment by burtonator** [comment]
time is something I could add too.. not sure how I would track it though as I have no way to konw if the user really stepped away from the computer.  A lot of people don't really use the mouse when they read. I guess I could say if there is no keyboard / mouse activity for say 2 minutes then they are away.?
