### ISSUE TITLE
Duplicate fingerprint, different PDF files

### ISSUE THREAD

**Issue by rabuf** [burtonator/polar-bookshelf#432]
**Describe the bug**
Multiple files added from the same directory at the same time. Only some were actually added to Polar.

**To Reproduce**
1. Open the developer tools
2. Go to the console
3. Add two distinct PDF files (purchased, don't want to attach but can supply on request)
- The files in question are (my titles, name doesn't matter): Weinberg - Active Regulation.pdf and Weinberg - Passive Regulation.pdf. Purchased from Leanpub.
4. Error message will appear in console. The error message may be the other file, depending on the order that Polar gets to them.
5. Repeatedly import the missing file, same error message.

**Expected behavior**
All distinct, files should have been added to Polar.

**Error Messages**
```
breadcrumbs.ts:155
[warn] [1.0.14] [PDFImporter.js] This file is already present in the datastore with fingerprint
cabd9312b11e8ce57f9f954b10311625: /Users/jtsummers/Dropbox/Books/Systems Theory/Weinberg -
Passive Regulation.pdf
```

**Desktop (please complete the following information):**
 - OS: macOS 10.14.1
 - Polar Version: 1.0.14

**Additional context**
I've attempted renaming the files. Importing from other directories. The checksums of the two files are distinct from each other. Viewing them, it's clear that they have different contents. Using Preview I have edited the missing file, but that doesn't seem to change the right portion of the PDF to cause it to import.

pdfjs seems to calculate the fingerprint from the MD5 checksum only if some ID value is not present. It is possible these two files have the same ID despite being distinct files.

https://github.com/mozilla/pdf.js/blob/58c3ea08202becf007c304512c44726719acb508/src/core/core.js#L513

**Comment by burtonator** [comment]
I'll see if I can get something implemented with this tomorrow as it might be as simple as ten lines of code to just tell it to read a new variable if present.

**Comment by rabuf** [comment]
I can test from source but it may take a day or two for me to have time. Thanks for the quick response.

**Comment by burtonator** [comment]
I think I have a decent workaround for this:

We need two types of fingerprints.  Primary and legacy. We should ALWAYs use a primary fingerprint / ID now if a legacy one doesn't exist.  But we should use a legacy one if it DOES exist.  

This way existing documents imported in the past can still be used.

Otherwise we use the new hashcode base fingerprint.

We will have to use the fingerprint to see if the document is loaded though.

This can be done by comparing the previous fingerprint which is '' to the new one which will ~= '' 

This is used JUST for load detection.  

This algorithm should be trivial to implement.

**Comment by burtonator** [comment]
- WebController.listenForDocumentLoad is what I need to start with.

**Comment by burtonator** [comment]
DocFormat needs to be updated to support this type of detection...

**Comment by burtonator** [comment]
ok... I have a basic/working version of this but we have one more thing to fix... we import  the PDF twice because we use the OLD fingerprint in PDF loader... we should read the fingerprint from the URL metadata not from the PDF.

**Comment by burtonator** [comment]
I have a patch for this now... the main remaining issue is whether we're storing hashcodes with PHZ files... I don't think we are. I think the fingerprint is generated from the filename.
