### ISSUE TITLE
The ability to sync specific documents to Anki

### ISSUE THREAD

**Issue by zachlefevre** [burtonator/polar-bookshelf#441]
NOTE: Polar is supported by community donations.  Bug reports and features are prioritized for people who make a donation: https://opencollective.com/polar-bookshelf

**Is your feature request related to a problem? Please describe.**
I have many documents which I have archived, and do not wish to sync to Anki. Also I have many documents that I have synced to Anki, then archived, and have moved the decks to be a sub-deck of another deck. When I sync to Anki, any sub-decks are recreated as decks.

**Describe the solution you'd like**
The ability to sync individual documents, not the entire library.

**Describe alternatives you've considered**

**Additional context**
<img width="871" alt="upd" src="https://user-images.githubusercontent.com/17463558/49402978-17c39b00-f711-11e8-9cee-66a3b87e11b3.PNG">

**Comment by burtonator** [comment]
Could we just solve it another way by not re-indexing it if it's in a different deck?  

We're considering changing the default strategy to always write to a specific deck like "Default" and as part of that I"m going to see if I can not re-add if it the same card just happens to be in a different deck.

**Comment by zachlefevre** [comment]
I think that would be better behavior, however I do not necessarily want every flashcard in polar to become a flash card in Anki.

I do not like the idea of a "Default" deck, as it would be more difficult to determine if the card originated from a document that I did not want to sync.

**Comment by burtonator** [comment]
> I think that would be better behavior, however I do not necessarily want every flashcard in polar to become a flash card in Anki.

You should probably use a comment then as flashcards are meant to be flashcards and sync'd to systems like anki that support flashcards.

> I do not like the idea of a "Default" deck, as it would be more difficult to determine if the card originated from a document that I did not want to sync.

I think we're going to add another field in the metadata for 'Source' and other fields so you can isolate them. Anki suggests placing everything in one big deck and with Polar you can do this.  We're still going to keep per deck sync though I think.
