### ISSUE TITLE
Starts printing on macOS when opening a PDF document. 

### ISSUE THREAD

**Issue by sandersantema** [burtonator/polar-bookshelf#442]
NOTE: Polar is supported by community donations.  Bug reports and features are prioritized for people who make a donation: https://opencollective.com/polar-bookshelf

**Describe the bug**
Starts printing on macOS when opening a PDF document. 

**To Reproduce**
1. Open a pdf

**Expected behavior**
The pdf viewer not opening a printing window. 

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6
 - Latest polar version

**Comment by burtonator** [comment]
Wait.. it just starts sending data to your printer?

**Comment by sandersantema** [comment]
Sorry I wasn't clear, I see that now. It doesn't actually start printing but it opens the printing window (as it would do when you press cmd/ctrl p)

**Comment by burtonator** [comment]
How did you open it?  Did you import it first? double click on it?

**Comment by sandersantema** [comment]
I believe drag and drop, but in the newest version the problem seems to be gone.
