### ISSUE TITLE
Feature suggestion: vim inspired key bindings

### ISSUE THREAD

**Issue by likyng** [burtonator/polar-bookshelf#460]
As a heavy user of VIM keybindings in most applications I use, I'd appreciate support for VIM style keybindings for polar bookshelf too. It's absolutely not a must have function, though. Maybe it could be possible to "simply" integrate the vimium chrome plugin into the pdf reader to get vim style navigation/searching.

**Comment by burtonator** [comment]
This will probably have to wait for a bit unless someone integrates a patch themselves.  

The key bindings are a bit confusing right now due to how React + Electron behave and some of the manual event listeners we have.  Need to standardize it.

**Comment by stekern** [comment]
As a quick follow-up to this: What about using `j` and `k` for scrolling (they are now used for switching pages), and `h` and `l` for switching pages? I believe this is a more default behavior.

**Comment by leogodin217** [comment]
Just a +1 for this. I use Vim key bindings in Chrome and every text editor/ide I use.
