### ISSUE TITLE
It is not integrating with Anki. 2.0 or 2.1.8

### ISSUE THREAD

**Issue by cjdduarte** [burtonator/polar-bookshelf#520]
NOTE: Polar is supported by community donations.  Bug reports and features are prioritized for people who make a donation: https://opencollective.com/polar-bookshelf

**Describe the bug**
It is not integrating with Anki. 2.0 or 2.1.8

**Screenshots**

![image](https://user-images.githubusercontent.com/42243532/50769055-d5d6c900-1269-11e9-832f-ca5cf71ffdad.png)

**Desktop (please complete the following information):**
 - OS: Windos 10

**Comment by cjdduarte** [comment]
I found that it requires the templates in with the denomination of the terms in English and the original Templates. However, since I use Anki in the PT-BR language, the error occurred. Would not it be possible to have some place to parameterize this (template name and fields name?

![image](https://user-images.githubusercontent.com/42243532/50771213-1be35b00-1271-11e9-8389-4c8479fb0e03.png)

**Comment by burtonator** [comment]
Nice! Thanks for finding this.

I think I have to first resolve the names from their IDs... I hope at least.  I'll take a look at fixing this for 1.9.0... trying to get 1.8.0 out the door.

**Comment by cjdduarte** [comment]
> Hi! I had the same problem (I also use Anki in PT-BR, Anki 2.1 and Polar 1.8) and I solved it by doing 2 things:
> 
> 1. Changing Anki's language to English (open Preferences with Ctrl + P);
> 2. Adding two note types in English (Basic and Cloze)

Rodolfo, acabei chegando na mesma solução que a sua. Porém não precisou mudar para Inglês. Basta os cartões estarem com os nomes em Inglês.

Aproveitando. Temos um grupo no Telegram em PT-BR para trocar informações sobre o Anki. caso deseja participar: https://t.me/ankiflashcards

**Comment by rodolfoebueno** [comment]
> > Hi! I had the same problem (I also use Anki in PT-BR, Anki 2.1 and Polar 1.8) and I solved it by doing 2 things:
> > 
> > 1. Changing Anki's language to English (open Preferences with Ctrl + P);
> > 2. Adding two note types in English (Basic and Cloze)
> 
> Rodolfo, acabei chegando na mesma solução que a sua. Porém não precisou mudar para Inglês. Basta os cartões estarem com os nomes em Inglês.
> 
> Aproveitando. Temos um grupo no Telegram em PT-BR para trocar informações sobre o Anki. caso deseja participar: https://t.me/ankiflashcards

Legal, cjdduarte! Vou entrar em contato. Obrigado.
