### ISSUE TITLE
Polar UI does not show up if no network available

### ISSUE THREAD

**Issue by asaintsever** [burtonator/polar-bookshelf#522]
**Describe the bug**
Polar process hangs and UI does not appear in offline mode.

**To Reproduce**
1. Disable WiFi, unplug any network wire
2. Start a shell and type polar-bookshelf
3. Process starts but with error:
[error] [1.7.0] [MainAppExceptionHandlers.js] Uncaught exception:  { Error: getaddrinfo ENOTFOUND localapp.getpolarized.io
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:50:26)
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'localapp.getpolarized.io' }
[error] [1.7.0] [MainAppExceptionHandlers.js] Unhandled rejection:  [Error: net::ERR_INTERNET_DISCONNECTED]
4. No UI and polar-bookshelf process hangs -> have to kill it

**Expected behavior**
No reason Polar cannot works in offline mode with the documents already saved.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Version Polar 1.7.0

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by burtonator** [comment]
You're right.. it's because you can't resolve the localhost app. 

Can you find out if you can still resolve 'localhost' ?

just type nslookup localhost and see if it works for you?

I might use that or just 127.0.0.1 as a short term workaround.

**Comment by burtonator** [comment]
Going to try to fix this in the 1.9.0 series FYI... should be out in another week.

**Comment by asaintsever** [comment]
Yes I can resolve 'localhost' so your fix should work.

**Comment by thiswillbeyourgithub** [comment]
I have noticed the problem for months and it is still here. Any progess ?

Polar 1.32.32

**Comment by burtonator** [comment]
Will be fixed in the next release... which should do out today or tomorrow.
