### ISSUE TITLE
There is no icon after install. 

### ISSUE THREAD

**Issue by roachsinai** [burtonator/polar-bookshelf#523]
**Describe the bug**
There is no icon after install.

**Screenshots**
![screenshot_20190109_095138](https://user-images.githubusercontent.com/9500049/50870724-2a0db480-13f4-11e9-918c-ba784c9b791a.png)

**Desktop (please complete the following information):**
 - OS: [Manjaro]
 - Browser [chrome]
 - Version [1.7]

**Additional context**
Can't find a icon like on my computer.

```
➜  ~ sudo find / -name "polar-bookshelf.*"    
/usr/share/applications/polar-bookshelf.desktop
find: ‘/run/user/1000/gvfs’: 权限不够
/home/roach/.cache/yay/polar-bookshelf-bin/polar-bookshelf.desktop
➜  ~ 
```

**Comment by burtonator** [comment]
Monjaro used Gnome?  is the .desktop file invalid ?  Does it link to a valid file?  Did you install via .deb or something else?

**Comment by roachsinai** [comment]
I'm using KDE. I install it from [AUR](https://aur.archlinux.org/packages/polar-bookshelf-bin/). Will upload .desktop tomorrow, can't acess my self computer now.

**Comment by burtonator** [comment]
I don't use KDE so would need your help to debug this . Also this is going to be an unsupported package (we didn't package it) so can't advise much here.

Maybe try the snap or AppImage?

**Comment by roachsinai** [comment]
I can't find a icon, yes maybe I should first report to aur packager.

```
➜  polar-bookshelf-bin git:(master) ✗ pwd                         
/home/roach/.cache/yay/polar-bookshelf-bin
➜  polar-bookshelf-bin git:(master) ✗ cat polar-bookshelf.desktop
[Desktop Entry]
Name=Polar Bookshelf
Comment=Polar is a personal knowledge repository for PDF and web content supporting incremental reading and document annotation
Exec=polar-bookshelf
Terminal=false
Type=Application
Icon=polar-bookshelf
StartupWMClass=Polar Bookshelf
Categories=Office;Viewer;
X-Desktop-File-Install-Version=0.24
➜  polar-bookshelf-bin git:(master) ✗ 
```

If can't solve it will try AppImage.

**Comment by roachsinai** [comment]
Solved by the packager of aur.

**Comment by douglasg14b** [comment]
Having this issue on KDE Neon with the Snap package.

**Comment by burtonator** [comment]
@douglasg14b if you can debug it and let us know what's happening I can fix it.

**Comment by douglasg14b** [comment]
@burtonator  Will do!
