### ISSUE TITLE
Logging out of cloud sync makes it impossible to login back again.

### ISSUE THREAD

**Issue by warfarincoumadin** [burtonator/polar-bookshelf#536]
Steps to reproduce:

1. Sign up for cloud sync.
2. Logout
3. Log back in
4. PB redirects to https://www.accountchooser.com/learnmore.html and  breaks (white screen that cannot be removed)

Windows 10

**Comment by burtonator** [comment]
Can you record a video of what's happening? I don't see that on my machine...

**Comment by gitbrn** [comment]
@burtonator I have the same issue, running on Ubuntu 18.04, through the Snap, v1.10.0.

PB actually redirects to https://www.accountchooser.com/redirect.html#localhost:8500, then immediately to the learnmore page.

[Screengrab](https://imgur.com/a/8SRGbUD)

**Comment by burtonator** [comment]
@gitbrn Thanks!  This is really helpful.  I think it's the issue of going to a separate site.  the video really helped!

**Comment by burtonator** [comment]
@gitbrn I have a quick fix implemented for this.  I wasn't testing this one edge case but will do so in the future.

**Comment by gitbrn** [comment]
No worries, glad the video helped. Thanks for the quickfix (and such an awesome program in general!).

**Comment by gitbrn** [comment]
Just confirming that this is fixed for me - running v1.11.0, Snap on Ubuntu 18.04. Thanks!
