### ISSUE TITLE
one click git pull/push

### ISSUE THREAD

**Issue by tim-hub** [burtonator/polar-bookshelf#549]
**Is your feature request related to a problem? Please describe.**
Currently, each time when I want to pull and push all of my config to the gir remote repo, I have to do it in my CMD line. it takes time and many different steps.

**Describe the solution you'd like**
A gui button which located in the GUI and can run the tasks above automatically in one click.

**Comment by burtonator** [comment]
Use polar sync!   That's what it's there for... Happens all in real time.  No git required.
