### ISSUE TITLE
Survey is marked as private

### ISSUE THREAD

**Issue by bradparks** [burtonator/polar-bookshelf#574]
Polar showed me a link that said "Please take 2 min to fill out this survey".

I clicked on the link, and it went to a typeform page that was "private"

Error message: "Oops! This typeform is private."

https://kevinburton1.typeform.com/login/?utm_source=typeform.com&utm_medium=typeform&utm_content=typeform-private&utm_campaign=u1zNWG

**Comment by burtonator** [comment]
Thanks. Fixed.  Made changes to billing settings and there was an error which is now fixed.
