### ISSUE TITLE
New user setup wizard for onboarding

### ISSUE THREAD

**Issue by burtonator** [burtonator/polar-bookshelf#586]
I think we need a new user setup wizard... 

Right now we would need the following steps:

1.  Agree to the ToS and notify them of GDPR
2.  Set them up for Cloud Sync (optional)
3.  Get some initial documents for them to use / read to make it more sticky for them.

**Comment by andreaferretti** [comment]
New user here. This is definitely needed. As a new user I am just left with no idea what to do with the software.

I cannot even start as I cannot find a way to import more than one document at a time. I have a folder with thousands of documents and no idea how to go on

**Comment by burtonator** [comment]
- have them confirm certain important aspect of polar like:
  - we are supported by the community
  - dropbox is not supported. 
  - polar cloud sync

**Comment by burtonator** [comment]
- prompt to invite users for free cloud sync.

**Comment by burtonator** [comment]
- prompt to import a directory and then print the PDFs found and the number found...

**Comment by burtonator** [comment]
- link to the chrome extension (for now)

**Comment by burtonator** [comment]
- link to the discord group

**Comment by burtonator** [comment]
The onboarding mechanism should have a way to do a differential if we add a new feature but a user hasn't completed part of the onboarding process.

This way we also support resume as well so that if a user wants to 'skip' they can just resume at any point.

However, if we add an important feature the user can just be prompt when they upgrade.

**Comment by burtonator** [comment]
We can't have this collide with the GDPR feature or any of the incremental prompts like asking for feedback.

**Comment by burtonator** [comment]
The differential feature should just be via a new set of flags that's added after each tour and possibly some sort of sub-tour so that when a new feature is launched we can have the user just take the sub-tour.

**Comment by burtonator** [comment]
Final steps in the tour:

- tell the user about the chrome extension ?
- walk them through adding more files?

**Comment by burtonator** [comment]
Also make sending out invitations part of the onboarding and maybe make it a top level feature in the UI... If I can get more people to use this button it will increase our growth significantly.

**Comment by ParaplegicRacehorse** [comment]
A new user wizard really should not, I think, be more than a license acceptance and a brief introduction to features and pointer to where to get more help. #126 exists for documentation. "Tours" are just so much pop-up-junk to get in the way of actually using or experimenting with the software. The Help menu in 1.19.0 has links to lots of good stuff. It's also where users (me, anyway) go to look for help; that and `Ctrl-?`

If you must have pop-up-junk, sort out some way to add a tool-tip option which functions in both the document browser, modal dialogs, and the different doc-view states.

-----

> Also make sending out invitations part of the onboarding and maybe make it a top level feature in the UI... If I can get more people to use this button it will increase our growth significantly.

Ugh, no! Good software gets recommends without resorting to such chinzy gimmicks. Polar is already getting recommends. Keep improving it: adding features, manuals, tutorials, an active blog and community pages. Users will follow.

**Comment by burtonator** [comment]
@ParaplegicRacehorse The new user tour can be skipped and it increased our cohort retention from 2% to 11%.  50% of people actually complete the entire tour.  

Going to close this one anyway as the tour is completed :)
