### ISSUE TITLE
Polar deleted all documents from its repository after an update

### ISSUE THREAD

**Issue by Rumata888** [burtonator/polar-bookshelf#590]
Polar deleted all documents from its repository after an update to 1.8 on Ubuntu

**Expected behavior**
This shouldn't happen.

I can attach a screenshot of an empty list of documents in Polar if that helps.
 OS: Ubuntu 16.04
 Browser: I have chrome, chromium and firefox. Chromium is the default one

**Comment by burtonator** [comment]
I bet you used to run a snap install and went to a non-snap install?  (or vice versa)

I doubt Polar deleted your repo... the issue is it can't find it due to snap being a problem.

I think I might stop supporting snap for this reason.

**Comment by Rumata888** [comment]
It created a new folder ind /home/$USER/snap/polar-bookshelf/. So I just copied the contents from the previous one. There is a "common" folder. Maybe you could save data there.

**Comment by burtonator** [comment]
@andreafweretti. Yes. Polar just couldn't find his Polar repo dir.

The files were there. Nothing was lost. We are probably going to remove support for snaps for this reason

**Comment by andreaferretti** [comment]
Great, thank you! :-)
