### ISSUE TITLE
PDF rendering issues on Ubuntu (disable GPU)

### ISSUE THREAD

**Issue by janimo** [burtonator/polar-bookshelf#593]
On Ubuntu 18.04, all PDFs I have tried viewing have small rendering issues, namely parts of glyphs missing in texts. The exact same documents are rendered correctly with the Firefox built-in viewer. It may be related to hardware accelerated rendering, a way to turn it off would be useful.

**Comment by burtonator** [comment]
ok.. I thinkthe problem is that on some platforms I need to call "app.disableHardwareAcceleration()"

.. mostly if you have a wonky GPU... I'll try to add a command line option.

**Comment by burtonator** [comment]
just set this up as an ENV var of POLAR_DISABLE_GPU 

then call app.disableHardwareAcceleration()

**Comment by burtonator** [comment]
will be POLAR_DISABLE_HARDWARE_ACCELERATION in the next release or buidl from HEAD.
