### ISSUE TITLE
Scaling bug reading Captured Web Pages

### ISSUE THREAD

**Issue by DOFfactory** [burtonator/polar-bookshelf#598]
I capture a web page which is succesful and it is saved in Polar. The reading windows opens. The text is too small at 100%, so I chose to enlarge it to 150%. When I reach the end of a document, I notice that the last sentence of the page is unfinished. However, I cannot scroll further. When I switch back to 100%. the page shows correctly again and shows the "unfinished" sentence and the rest of the page.

**Expected behavior**
Obviously this should not happen.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Internal for Polae
 - Version 1.10

**Comment by burtonator** [comment]
Agreed.. this has been bothering me for some time but there are some weird CSS issues involved that I haven't been able to track down.  

One other thing I'm meaning to do is set a minimum font size and use our own bundled fonts.  Some sites use fonts that are simply too small and ugly to read.

**Comment by burtonator** [comment]
I fixed this in 1.10 but there is still a problem with pagemarks not being placed properly.  they are zoomed too high...

**Comment by DOFfactory** [comment]
Well, I don't see it fixed in v1.10

**Comment by burtonator** [comment]
@DOFfactory sorry. you're right. I mean to say 1.11 (which isn't out yet).

the issue was that the parent div wasn't resized so it was hidden.

**Comment by burtonator** [comment]
next release will be out on or around Feb 1.
