### ISSUE TITLE
Colors and little icons to show there is a note...

### ISSUE THREAD

**Issue by murpholinox** [burtonator/polar-bookshelf#616]
![screenshot from 2019-02-08 15-54-56](https://user-images.githubusercontent.com/732802/52508351-020f9d80-2bba-11e9-89c5-562703ac734a.png)

Would be nice to have a set of colors more like Mendeley (more transparent or pastel-ish?) and also the little icon showing there's a note related to the highlight.

**Comment by burtonator** [comment]
I agree. I think I could do it for PDFs just not for HTML files for now.  I'll try to spend some more time working on this.

**Comment by burtonator** [comment]
https://github.com/burtonator/polar-bookshelf/issues/617

**Comment by burtonator** [comment]
https://github.com/burtonator/polar-bookshelf/issues/618

**Comment by burtonator** [comment]
Created two bugs for this and closing this one.  (see links above)
