### ISSUE TITLE
Search within the current document.

### ISSUE THREAD

**Issue by janimo** [burtonator/polar-bookshelf#623]
**Is your feature request related to a problem? Please describe.**
Easily searching the web for terms, phrases or names encountered in documents.

**Describe the solution you'd like**
A right-click menu allowing to search the web for the highlighted text, as present in web browsers.

**Comment by burtonator** [comment]
Yes... I agree. It's annoying.  Electron doesn't have a very good search framework.

**Comment by janimo** [comment]
Just to clarify, I meant searching the web not within the current document. It would likely need configuration settings for the search engine to use, so not a simple change.

**Comment by burtonator** [comment]
We probably won't ever add support for searching the entire web. Polar isn't designed to be a full browser - just a document manager.

**Comment by janimo** [comment]
I was thinking of launching an external browser with the highlight passed as the query string to the search engine, useful for unfamiliar terms encountered while reading a doc. But thinking about this more, I am not sure how jumping to a definition like this fits in with the learning framework encouraged by Polar.
