### ISSUE TITLE
What were the modifications made to pdf.js for the viewer?

### ISSUE THREAD

**Issue by himat** [burtonator/polar-bookshelf#656]
**Describe the bug**
I was curious about how the pdf.js viewer was modified from the original in the `pdfviewer` directory. There is only one relevant commit which is https://github.com/burtonator/polar-bookshelf/commit/bedf5ce04a58d386b0d5e4fa30c7ad8a2cd0d43d, and this just adds the entire folder, but since the pdfjs files are so huge, it's hard to tell what was changed.

Can @burtonator to let us know how he modified those files to get the current viewer with the colored highlighting options?

**Comment by burtonator** [comment]
oh.. the highlighting and annotation functionality is just layered on top of the viewer. 

The viewer wasn't modified too much. Just a few changes here and there.

**Comment by himat** [comment]
Right, but it's hard to tell what was actually changed? I was thinking about contributing to the viewer part, but the pdf.js file is very large (tens of thousands of lines), so it seems very hard to even figure out what does what

**Comment by burtonator** [comment]
ah. ok. agreed. So the entire 'pdfviewer' directory is lifted right from the binary pdf.js distribution.

I definitely agree that it's ugly but it's left over from the MVP stage of Polar and needs to be reworked.  We basically load it as its own webapp and layer some stuff directly on top of it.

the plan is to build out a totally new viewer with epub, html, pdf and markdown support.

**Comment by himat** [comment]
but the default pdf.js distribution doesn't have annotation abilities, so I was wondering how you added that?
It would probably be good for me to figure that out since the new viewer probably won't be made that soon yet

**Comment by burtonator** [comment]
check out PDFViewer.ts as the entry point... it basically layers divs on top of the main pdf.js app.
