### ISSUE TITLE
Newest version has no URL bar when choosing to create PDF from link

### ISSUE THREAD

**Issue by Abourass** [burtonator/polar-bookshelf#683]
**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

https://opencollective.com/polar-bookshelf

**Describe the bug**
Newest version has no URL bar when choosing to create PDF from link

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by burtonator** [comment]
AH! You're right.. working on a fix now!! should roll out today. Not sure how this got in... mea culpa

**Comment by burtonator** [comment]
Fix for this going out now... it will be 1.13.10 in about 30 minutes once the build finishes pushing.
