### ISSUE TITLE
Capture web content broken for all pages [osx]

### ISSUE THREAD

**Issue by sagarjauhari** [burtonator/polar-bookshelf#684]
**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

https://opencollective.com/polar-bookshelf

**Describe the bug**
Capture web content broken for all pages

**To Reproduce**
Install release 1.13.9 on mac

**Expected behavior**
URL bar should be visible. 'Capture' button should be visible

**Screenshots**
![image](https://user-images.githubusercontent.com/1958807/53833256-ef7c5000-3f3c-11e9-971c-d12f5f495854.png)

**Desktop (please complete the following information):**
 - OSX
 - Version [1.13.9]

**Comment by sagarjauhari** [comment]
There's no URL address bar or capture button!

**Comment by sagarjauhari** [comment]
Something broke in the latest release because I installed `1.13.8` on my mac and it is working properly.

**Comment by burtonator** [comment]
Can you try with 1.13.10? I just pushed it... we caught this just affter 1.13.9 shipped and pushed .10

**Comment by sagarjauhari** [comment]
Yes, it works now! thanks for the fix.
A Unit/UI/Selenium test should have caught such an error.

**Comment by burtonator** [comment]
I know... the problem is that spectron with Electron is horrible to setup and run... I need a better alternative.

From now on I'm just going to do 1x release per week and a smoke test of them before they go out.

**Comment by Rumata888** [comment]
Same problem on ubuntu 18.04
