### ISSUE TITLE
Clicking the darkened area outside the Tag pop-up no longer closes pop-up

### ISSUE THREAD

**Issue by rslay** [burtonator/polar-bookshelf#685]
**To Reproduce**
1. Click on the tag icon next to a listed document
2. Click outside of the pop-up (in the darkened area), or press `Enter` without a dropdown tag selected

**Expected behavior**
The pop-up should disappear, but instead the only thing that happens is the text field becomes unfocused.

**Screenshot**
![image](https://user-images.githubusercontent.com/25256438/53856922-26e60d80-3fcc-11e9-84a7-4f9c31543772.png)

**Affected OS**
 - Windows 10 x64
 - Mac OSX Mojave x64

**Additional context**
Only pressing `ESC` closes the pop-up, and only if the text field is active.

**Comment by rslay** [comment]
This behavior seems to have surfaced with the most recent update (1.13.10), it was not happening to me in the previous version.

**Comment by burtonator** [comment]
Thanks. They changed the popup functionality in the most recent react version so this broke us.  Next version should have it fixed.  There's like a 750ms delay though which I don't like.  Will have to figure out that part still.

**Comment by burtonator** [comment]
Will be fixed in the next release...
