### ISSUE TITLE
Remove existing tags

### ISSUE THREAD

**Issue by RamiAwar** [burtonator/polar-bookshelf#711]
**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

https://opencollective.com/polar-bookshelf

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by burtonator** [comment]
I need a description of the bug...
