### ISSUE TITLE
Snap packages not working

### ISSUE THREAD

**Issue by alexanderlanganke** [burtonator/polar-bookshelf#74]
I am on Ubuntu 18.04 (up to date debs and snaps). Clicking on the Polar Bookshelf Icon does nothing. Am running the Polar Bookshelf Snap.

**Comment by burtonator** [comment]
Thanks for reporting this. I'm on Ubuntu 18.04 too. 

Can you try the .deb? I'll try the snaps again too.  I also made a static tar.gz which you can run too.

Thanks for the feedback. We're still beta and trying to move out of the beta phase fast so this really helps.

**Comment by alexanderlanganke** [comment]
The .deb works fine. Is the snap up-to-date?
Is the snap setup to build from GIT automatically?

**Comment by burtonator** [comment]
The .deb and .snap build a the same time so something must be wrong with the .snap configuration.  I'm going to have to find a way to unit text the actual builds not just the source code.

Also don't have CI setup so we don't have nightlies yet.

**Comment by alexanderlanganke** [comment]
How about Launchpad? The Instructions make it seem easy to setup: https://docs.snapcraft.io/build-snaps/ci-integration

**Comment by burtonator** [comment]
Literally looking at that now.

The snap doesn't actually work on the latest version so I'm trying to figure out why.  The other issue is that MacOS and Windows have more work to do too so a lot to catch up on.  Need to create keys, sign the builds, etc.  

It think for now I *might* have to back out on snap just to get the next release done.  I'll know soon though.

There's a LOT to the next release so I don't want to hold it if the static builds and .deb work.

**Comment by alexanderlanganke** [comment]
Accessing the homedir (~/home) should be as easy as declaring the "home" plug.

Google search gives this thread on snapcraft https://forum.snapcraft.io/t/use-of-home-and-network-plugs/2587/4

Is this applicable to our problem?

**Comment by burtonator** [comment]
If you send a pr I'll merge it 👌. I think it's pretty easy to implement. If not I'll try to get to it in the next release

**Comment by alexanderlanganke** [comment]
I do not think I can do that. I assume you are creating the snap locally right now via snapcraft? If so, then the snapcraft.yaml is only on your machine. What I can try to do is setup launchpad as a CI system for autocreation of a snap based on your master branch and autopush that to the snap store. If I can get that to work it would make me the maintainer of your snap package as it would be published via my Launchpad account. I can try that if I have your permission.

**Comment by burtonator** [comment]
The command:

```
export PATH=./node_modules/.bin:$PATH
tsc && electron-builder --config=electron-builder.yml --linux snap
```

Will build a .snap file locally without any snapcraft magic happening.

If the resulting .snap works on your machine we can push it into snapcraft.  I only have initial support for that though but I can deploy it again I think.

I don't mind manually pushing the builds during the release process for now.  

We're using electron-builder and it has some features for automatically pushing them or  I can just wrap it with the snap commands.

I did one early release but I haven't really automated it or anything.  

I think the main problem is that the .snap is just broken.

**Comment by alexanderlanganke** [comment]
I have no experience with electron-builder but from what I can tell all you need to do is edit electron-builder.yml to include a passage about the snap config.
Do you edit this manually or via a GUI Interface?
We probably only have to insert the snap config part concerning the plugs and build dependancies.
https://www.electron.build/configuration/snap

**Comment by burtonator** [comment]
I just edit it manually.  You can probably just add the home plugin like you suggested and it might just work.

The command above will rebuild it.

**Comment by alexanderlanganke** [comment]
I will try that and send a PR request if successfull..
