### ISSUE TITLE
Change order of created flashcards.

### ISSUE THREAD

**Issue by Virility** [burtonator/polar-bookshelf#752]
**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

https://opencollective.com/polar-bookshelf

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Perhaps some sort of drag component.

**Describe alternatives you've considered**
Copying, removing, and readding text is not preferable.

Further, newly created flash cards are added before previously created cards. I think it should be reversed.

**Comment by burtonator** [comment]
agreed and will be changed in the next version
