### ISSUE TITLE
Custom color annotation/highlight and changing the color in batch

### ISSUE THREAD

**Issue by isemaj** [burtonator/polar-bookshelf#759]
**Is your feature request related to a problem? Please describe.**
Not related to any problem.

**Describe the solution you'd like**
I would like to recommend a feature for custom color for highlight/annotation not limited to a fixed number and also another feature where in we change the color by batch.

**Describe alternatives you've considered**
Currently the highlighter is fixed to three colors. :(

**Additional context**

**Comment by burtonator** [comment]
I'm fine adding 2-3 other colors but don't want to add tons...

**Comment by isemaj** [comment]
Why?

**Comment by burtonator** [comment]
Why is it fixed?  I don't want to support arbitrary colors  for UI / UX issues as well as technical concerns.

**Comment by isemaj** [comment]
Ok
