### ISSUE TITLE
Analytics notification text spill offscreen on first time startup

### ISSUE THREAD

**Issue by DocSunset** [burtonator/polar-bookshelf#767]
**Describe the bug**
The text in the "We use cookies" popup the first time I opened the app spills off screen.

**To Reproduce**
Download the app. Open the app.

**Expected behavior**
The text should presumably wrap within the popup box.

**Screenshots**
![Screen Shot 2019-03-24 at 9 14 54 AM](https://user-images.githubusercontent.com/17572588/54879966-01ebfa00-4e16-11e9-976f-e1c305ad0dbf.png)

**Desktop (please complete the following information):**
OS X 10.11.6

**Comment by DocSunset** [comment]
I'm actually seeing a ton of really bad UI weirdness. Perhaps there's something specific to my system at play...

**Comment by DocSunset** [comment]
I see the same issue in the web version of the app.

**Comment by burtonator** [comment]
thanks.. fixed!
