### ISSUE TITLE
Cannot list documents from a mounted partition

### ISSUE THREAD

**Issue by fenchelfen** [burtonator/polar-bookshelf#771]
**Bug description**

**To Reproduce**
1. Press `ctrl+i` to import
2. Type url of the mounted partition. In my case it's `/strg/Docs/`
3. Press `enter`
4. See that you're redirected to `/home/{username}`

**Expected behaviour**

See the list of documents in `/strg/Docs/`

**Screenshots**

I start with the following ![image](https://user-images.githubusercontent.com/35563366/54934376-75cdf580-4f2f-11e9-8a7e-e615790f5e41.png)

The url just before pressing `enter` 
![image](https://user-images.githubusercontent.com/35563366/54934890-4cfa3000-4f30-11e9-8034-77b788c436b5.png)

After I press `enter`, I see
![image](https://user-images.githubusercontent.com/35563366/54934447-9433f100-4f2f-11e9-8103-0d14753c7720.png)

**Desktop:**

 - OS: `4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
 - Version [e.g. 1.15.0]

**Additional context**

It worked well before I updated the app from a version below 1.0

**Comment by burtonator** [comment]
Are you using the snap distribution?  It might be permissions / capabilities  I need to request in the snap.  Snaps are weird and you can't really 'see' the native filesystem due to sandboxing.

**Comment by fenchelfen** [comment]
Yes, I'm using snap.

**Comment by fenchelfen** [comment]
That's a totally snap-related thing. I see it in many applications. Closing
