### ISSUE TITLE
[error] [1.16.0] [DiskDatastore.js] Datastore does not contain document:

### ISSUE THREAD

**Issue by jesusmgarcia** [burtonator/polar-bookshelf#801]
**Describe the bug**
I'm trying to capture web page. It captures the web page correctly in the capture web content window, but when I press the button "Capture the HTML page and save locally" and the pdf viewer loads, an error box is shown saying: "**[error] [1.16.0] [DiskDatastore.js] Datastore does not contain document:**". Anyway, the saved HTML page appears to be correct, other than the content is very large.

**To Reproduce**
1. Click '+Add' green button and select 'Capture Web Page'
2. Write the desired URL in the edit box, for example: "https://www.google.com", and press return to capture the URL. Check that the content is very large and empty.
3. Click 'Capture the HTML page and save locally' blue button.
4. Wait to load of the PDF viewer and see a red box in the upper right corner.
5. See attached screenshot.
![Captura de pantalla 2019-04-02 a las 22 15 23](https://user-images.githubusercontent.com/6751209/55434133-2aeb5800-5597-11e9-96fa-c4aa8047982b.png)

**Expected behavior**
No large content in the captured web content and no red box showing the error.

**Desktop (please complete the following information):**
 - OS: Mac OSX 10.14.4
 - Browser: Chrome 73.0.3683.86
 - Version: Polar 1.16.0

**Comment by burtonator** [comment]
Thanks.. yes.. I just encountered this today and will work on a fix and push it out soon.  

I've started working on another big branch so thought it was a local bug.  

I appreciate the heads up.

**Comment by burtonator** [comment]
FYI.. you can safely ignore this error. We're going to push a new release here shortly which properly removes the error but it's false.  We're creating the document as it's the first time it was seen by the doc repository.
