### ISSUE TITLE
After adding 200mb scanned  file often blank screens & cannot remove file

### ISSUE THREAD

**Issue by danieltomasz** [burtonator/polar-bookshelf#803]
I  am using latest snap Polar 1.16 on Ubuntu, I added this  220 mb scanned [file](https://we.tl/t-g9IdZ89qpQ) and Polar will  become blank always when I try to remove this file 
(link is only valid for limited time perios)

**Comment by burtonator** [comment]
Thanks.. this is fixed and will be resolved when we released 1.17... about a week I think.
