### ISSUE TITLE
Easier way to jump to context

### ISSUE THREAD

**Issue by jdlongman** [burtonator/polar-bookshelf#818]
At present, jumping to the context of an annotation is hidden behind an ellipsis menu.
Since this feature is often used when reviewing past read material, it would be beneficial to make it more accessible.
For instance, double clicking the color (yellow/red/green) on the left of an annotation in the annotation bar could allow jumping to the context.

**Comment by burtonator** [comment]
You can use the 'timestamp' at the bottom left of the highlight... but would a context menu (right click) and then the same contents as the elipsis menu work for you?  ... Make it easier to use.

**Comment by jdlongman** [comment]
Closing this issue as clicking on the timestamp works
However for other functions (such as deleting annotation or changing its color), a right click menu would not make the problem go away, as it still requires an extra action and menu. When working with massive amounts of files and comments this quickly becomes painful.
Instead I would suggest clicking the color on the annotation bar would give the option to change its color. And the delete annotation button should still be visible without going into a menu.
