### ISSUE TITLE
Files not being deleted

### ISSUE THREAD

**Issue by jdlongman** [burtonator/polar-bookshelf#821]
Current Behavior: Deleting a file from Navigation View doesnt remove the pdf or the metadata. Reimporting a new version of the file with the same name, Polar simply retrieves the old record and opens the old file.

Expected Behavior: File should be deleted from stash along with its metadata.

Environment: Desktop version, Ubuntu 18

Update: manually deleting the file from stash and the state.json doesn't work either, reopening Polar makes it retrieve the old file.

**Comment by jdlongman** [comment]
I was able to get rid of the old file eventually, but not sure precisely what I did. It was some combination of deleting through the Navigation view and restarting Polar to let it sync. 

In any case, deleting a file in Navigation view should auto sync immediately so that a new version of the file can be dragged in straight away.

**Comment by burtonator** [comment]
Could you document a way to reproduce this?   Just a set of steps... 

Are you using cloud sync or just desktop sync?

**Comment by burtonator** [comment]
desktop sync meaning you're using the desktop version with cloud sync enabled?

**Comment by jdlongman** [comment]
Yes that is correct.

**Comment by burtonator** [comment]
Thanks.. this should be straight forward.. they should definitely be deleted but I'll try to take a look.

**Comment by burtonator** [comment]
ok.. I just fixed a bunch of bugs with deletes that snuck in as part of the last refactor.

I didn't reproduce EXACTLY what you've noted here bug it seems very very close to what you describe.

I'm going to close this and if you notice the problem after 1.17.1 is released please reopen or submit a new bug.

Thanks for finding this.
