### ISSUE TITLE
Cannot GET /apps/repository/index.html

### ISSUE THREAD

**Issue by lwakefield** [burtonator/polar-bookshelf#822]
**Describe the bug**
Opening `Polar Bookshelf.app` gives `Cannot GET /apps/repository/index.html`

This happens immediately on opening `Polar Bookshelf.app` (for macos). I am a first time user. This occurs for me on both the `1.17.1` and `1.16.2` release,  I haven't yet tested across older releases yet.

**Screenshots**

<img width="2544" alt="Screen Shot 2019-04-09 at 7 13 06 AM" src="https://user-images.githubusercontent.com/5688923/55796004-fdbb1000-5a96-11e9-8fc1-a048564e3649.png">

**Desktop (please complete the following information):**
ProductName:    Mac OS X
ProductVersion: 10.13.6
BuildVersion:   17G5019

**Comment by burtonator** [comment]
interesting.. you're using our official builds?

Could you have another app running on port 8500?

**Comment by lwakefield** [comment]
I'm using official builds (originally from the website, then from the GitHub releases page).

I just checked what is running locally - nothing is on 8500, but there are plenty of other ports in use: 9200, 9300, 27017, 5432, 6379, 57003, 57004, 4567-4593, 8080, 9090, 4000. Do any of those seem like they might conflict?

**Comment by burtonator** [comment]
That is insanely weird.. I have no idea what could be going on here.. Are you running it in a non-standard directory? Not in /Applications maybe?  

If you're technical I could give you some commands to debug it...

**Comment by burtonator** [comment]
I also just tested on my Mac and it works fine.

**Comment by lwakefield** [comment]
Ah - I was running it from Alfred.app. Maybe there is a chance it was picking up the mounted volume?

Either way, I browsed to `/Applications` to open it and that seemed to work okay.

I think it is safe to close this for now.

Thanks!
