### ISSUE TITLE
Anki Sync doesn't work

### ISSUE THREAD

**Issue by lyannn** [burtonator/polar-bookshelf#825]
**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

https://opencollective.com/polar-bookshelf

**Describe the bug**
Anki Sync doesn't work.

**To Reproduce**
1. Go to tools
2. Click on sync flashcards to anki
anki is running, anki connect is installed, see nothing 
I have changed the notetype name, and changed language into English, still don't work

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your [problem.]
![anki](https://user-images.githubusercontent.com/49386567/55940343-80e48d80-5c72-11e9-9e85-bbcac06f4050.PNG)

![polar](https://user-images.githubusercontent.com/49386567/55940352-8346e780-5c72-11e9-9622-168f1b47311f.PNG)

![2019-04-11 (2)](https://user-images.githubusercontent.com/49386567/55941144-37953d80-5c74-11e9-96ab-eec21006d608.png)

![捕获](https://user-images.githubusercontent.com/49386567/55940355-8510ab00-5c72-11e9-969d-e87cd10d31d1.PNG)

**Desktop (please complete the following information):**
 - Version: polar 1.17.2, anki2.0 win10

**Comment by burtonator** [comment]
Anki has some weird bugs that I haven't been able to track down with flashcards being incorrectly detected as identical.  

If someone wants to dive in and figure out why I'm open minded to a patch but so far it has evaded any attempt at a fix.

**Comment by lyannn** [comment]
Can you add another option, export flashcards in apkg format or text format at local ?

**Comment by burtonator** [comment]
The export system can easily be extended if you wanted to send a PR

They're located at:

```
web/js/metadata/exporter
```

**Comment by lyannn** [comment]
> The export system can easily be extended if you wanted to send a PR
> 
> They're located at:
> 
> ```
> web/js/metadata/exporter
>

**Comment by lyannn** [comment]
Thank you so much,(●'ᴗ'σ)σணღ*,  Polar is amazing !
