### ISSUE TITLE
Github code snippets lost when on captured Medium pages

### ISSUE THREAD

**Issue by ettomatic** [burtonator/polar-bookshelf#832]
**Describe the bug**
Captured Medium blog posts miss the Github code snippets.

**To Reproduce**
1. Capture to a blog post like: https://hackernoon.com/elixir-deep-dive-evercam-a-10k-loc-phoenix-app-bd84bc20345d
2. All the Github code snippets present in the article are missing from the captured page

**Comment by burtonator** [comment]
Closing this as it should be fixed on 1.17.4 ... at least in the desktop app.

The webapp may or may not work.. We're reworking capture to better support the webapp.
