### ISSUE TITLE
File takes forever to open

### ISSUE THREAD

**Issue by jdlongman** [burtonator/polar-bookshelf#835]
Upgraded to 1.17.3 on Ubuntu, now dragging a file into the documents view takes up to five minutes before it opens. Dragging multiple files doesnt work at all. I have slow upload so it might be something to do with sync issues.

**Comment by jdlongman** [comment]
Note: If it is indeed uploading the entire file when I import it, this should be optional (as in Mendeley), since it takes a very long time and I just want to read the file.

**Comment by jdlongman** [comment]
I have logged out of Cloud Sync and it now opens files immediately.
So it seems this was the issue. 
Opening the file locally before starting upload should be the correct behavior here.

**Comment by burtonator** [comment]
Try 1.17.4... just released today.  this should fix the issue.

Sorry about the regression.  I'm working on refactoring some things to make them more "correct" in terms of blobs, streams, memory usages, and cloud sync.

I implemented a regression where it waits for cloud sync to finish first.  1.17.4 fixes it... also sync operations should be much faster which you will mostlly notice on the webapp... just mobile.
