### ISSUE TITLE
Removing tags in filtered view can break UI

### ISSUE THREAD

**Issue by sopoforic** [burtonator/polar-bookshelf#845]
If the repository view is filtered to show only docs tagged with "Foo" and you edit the tags on a document to remove the tag "Foo" from it, then the document disappears from the view and the tag window vanishes, but the repository view is still darkened and non-interactive. Polar must be restarted to become usable again.

Two changes should be made:

1. The tag window should not disappear immediately upon clicking the 'X' on the tag "Foo", so that the user can continue editing the tags.

2. When the tag window is dismissed, the repository view should become interactive again.

**Comment by burtonator** [comment]
wow.. yeah.. good catch.  I think I'm going to refactor this to only make the change when the user hits control-enter or the 'ok' button..

**Comment by burtonator** [comment]
Will be fixed when 1.18 is released.
