### ISSUE TITLE
Edit tags of multiple documents simultaneously

### ISSUE THREAD

**Issue by leliamesteban** [burtonator/polar-bookshelf#849]
**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

https://opencollective.com/polar-bookshelf

**Is your feature request related to a problem? Please describe.**
I add each issue of a comic separately, so I have eg. Deadpool kills the marvel universe #1 of 5, #2 of 5 etc. I'd like to add the same tags to every issue, but doing so is cumbersome. I have to click create tag on each document, type in all the tags, escape and then do it again and again.

**Describe the solution you'd like**
If I select multiple documents (eg. by clicking one document, then clicking another while holding down shift), I expect any actions I perform to be performed on all the documents except when this is unreasonable (eg. editing title). Editing the tags of multiple documents like this would save me a lot of time.

The solution from issue #614 does not work for me (the tag button does not appear on the left)

**Describe alternatives you've considered**
I could put the entire comic in one document, and I've considered this. However, whether or not I do end up choosing this does not make the issue go away. It's still a useful feature and I'm sure I'll encounter it again.

**Additional context**

**Comment by burtonator** [comment]
Are you on a more recent build?

![image](https://user-images.githubusercontent.com/45447/56464575-927c1280-63a1-11e9-8b0a-4cb2f26294d1.png)

The tag button is already there and multi-tag should work for you...

**Comment by leliamesteban** [comment]
ahhhh, my mistake. sorry for your time, I missed it
