### ISSUE TITLE
Don't auto-download "next article" from blogs

### ISSUE THREAD

**Issue by zuluqq** [burtonator/polar-bookshelf#866]
In trying to download https://www.outsideonline.com/2229791/why-are-most-endurance-athletes-rich, Polar actually downloads a bunch of other articles that follow it, I'm guessing through the site's "auto-next" setup that's activated by scrolling to the bottom. Any way of capping it at just that one article?

**Comment by burtonator** [comment]
No.. there's no way to handle this right now unfortunately.  We have to expand the page to make sure all images load and some sites detect that as scrolling and do a 'hack' to keep you on the site by potentially showing you more content (plus ads).

There's no way for us to detect this vs normal page interaction.

We might add more features in the future though to 'prune' the captured content if this happens by removing the items from the DOM before they're saved.

**Comment by zuluqq** [comment]
Pruning would be great. Still not ideal because of the extra processing power and time, but much better than having a one-page document that is suddenly 10 pages.

**Comment by clemux** [comment]
For what it's worth, Pocket captures this web page correctly. So a solution should exist, but I there's still no timetable about Mozilla's promise to open-source the pocket code base since they acquired the company.

**Comment by burtonator** [comment]
They might not handle iframe properly though... Some iframe only load when they are visibile so they might not support that use case..ill figure out a workable solution though.

Might be better to support the iframes on a case by case basis.
