### ISSUE TITLE
EPUB Support

### ISSUE THREAD

**Issue by infosisio** [burtonator/polar-bookshelf#867]
Why not? It would be awesome.

**Comment by burtonator** [comment]
Theree are other bugs for epub ... we might implement it via conversion to PDF in more of the short term and hopefully support it directly at some point.

**Comment by arnoo** [comment]
There is already an issue for this : https://github.com/burtonator/polar-bookshelf/issues/135

**Comment by burtonator** [comment]
Closing as duplicate of #135
