### ISSUE TITLE
Polar doesn't start after upgrade to 1.18.0

### ISSUE THREAD

**Issue by trenkert** [burtonator/polar-bookshelf#891]
I get this error when starting polar-bookshelf from terminal:

`[17791:0426/212134.086189:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/Polar Bookshelf/chrome-sandbox is owned by root and has mode 4755.`

**Comment by burtonator** [comment]
Thanks.. we had a bad release sneak out.. how did you get on 1.18.0?  I purged the release and immediately pushed 1.18.1 which fixed it.

Maybe it snuck out via snap? 

Anyway.. 1.18.1 should fix this for you.

REALLY sorry about this.. one of the next major tasks I"m working on next month is to improve our release and testing system so it's more robust about these issues but testing across three platforms + web is really a lot of work.

I've been doing this by hand but human error bit me.

**Comment by burtonator** [comment]
This may take a bit longer to resolve... you might try the AppImage for now... I'm still getting the SUID error...

**Comment by carter-yagemann** [comment]
If it's any help, I get the same message for 1.18.1 on Debian Stretch for both the deb and appimage. I tried manually setting the owner and mode of `chrome-sandbox` as described in the message. This causes the message to go away, but now I get a trap message and the program terminates before any GUI appears.

**Comment by burtonator** [comment]
Could you confirm that this is resolved in 1.19.4?
