### ISSUE TITLE
Proposition

### ISSUE THREAD

**Issue by managombo** [burtonator/polar-bookshelf#895]
Hello I am happy about this project initiative.

I would like to propose why not create a wiki of books. It is like a network of interconnected document by the reference in the books. Then when one person open a book, he can easily navigate to another book referred by this one. He can also easily get the definition and the wikipedia of a keyword (scientific term for example) just by selecting the word. Also he can view the comment on the document done by other people who rode the same version of the document (for exmpleif some one comment by writing the resume of a part of the document).

The purpose of my proposition is to ease the creation of an ecosystem of an interconnected documents and people. It can also be extended by webservices and web semantic used on a part of a document to gather the more information available on the web who can help better apprehend the selected part of the document.

Tank you.

**Comment by burtonator** [comment]
The best we can do now is to give you the ability to tag them and maybe put them together in a folder (once we add folder support).
