### ISSUE TITLE
Chrome/chromium extension fails to fetch many documents

### ISSUE THREAD

**Issue by Rumata888** [burtonator/polar-bookshelf#896]
When trying to open some pdfs in browser, for example http://archiv.infsec.ethz.ch/education/fs08/secsem/bleichenbacher98.pdf
, with extension installed viewer fails with the following error: 
PDF.js v2.0.943 (build: dc98bf76)
Message: Failed to fetch
Browser:
Chromium
Version 73.0.3683.86 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)

**Comment by burtonator** [comment]
Thanks.. I think this is a bug WRT the chrome extension?

**Comment by Rumata888** [comment]
Unfortunately not. A document I've been reading for quite some time failed
to open with the same error in the desktop version later.

**Comment by burtonator** [comment]
Is it the one in the above URL?

**Comment by Rumata888** [comment]
This one https://crypto.stanford.edu/~dabo/cryptobook/BonehShoup_0_4.pdf

**Comment by Rumata888** [comment]
DevTools log:
Warning: Indexing all PDF objects
internal/bootstrap/loaders.js:1014 Warning: Indexing all PDF objects
viewer.js:985 Uncaught (in promise) Error: Invalid or corrupted PDF file.
    at viewer.js:985
/snap/polar-bookshelf/58/resources/app.asar/web/js/logger/ConsoleLogger.js:19 [notice] [1.18.2] [CloudService.js] Authenticated as: Иннокентий Сенновский (isennovskiy@gmail.com)
/snap/polar-bookshelf/58/resources/app.asar/web/js/ga/RendererAnalytics.js:172 Operation took too long: firestore:enablePersistence: 1446ms
doLogging @ /snap/polar-bookshelf/58/resources/app.asar/web/js/ga/RendererAnalytics.js:172
/snap/polar-bookshelf/58/resources/app.asar/web/js/ga/RendererAnalytics.js:172 Operation took too long: firestore:createInstance: 1450ms
doLogging @ /snap/polar-bookshelf/58/resources/app.asar/web/js/ga/RendererAnalytics.js:172
/snap/polar-bookshelf/58/resources/app.asar/web/js/ga/RendererAnalytics.js:172 Operation took too long: datastore:init: 1451ms
doLogging @ /snap/polar-bookshelf/58/resources/app.asar/web/js/ga/RendererAnalytics.js:172
2/snap/polar-bookshelf/58/resources/app.asar/web/js/annotation_sidebar/AnnotationSidebarService.js:39 Uncaught TypeError: Cannot read property 'toggle' of undefined
    at AnnotationSidebarService.toggleAnnotationSidebar (:8500/snap/polar-bookshelf/58/resources/app.asar/web/js/annotation_sidebar/AnnotationSidebarService.js:39)
    at AnnotationSidebarService.onMessageReceived (:8500/snap/polar-bookshelf/58/resources/app.asar/web/js/annotation_sidebar/AnnotationSidebarService.js:34)
    at window.addEventListener.event (:8500/snap/polar-bookshelf/58/resources/app.asar/web/js/annotation_sidebar/AnnotationSidebarService.js:14)

**Comment by burtonator** [comment]
Thanks. Just fixed this and working on a release in another week or so. Trying to get it out soon but Google takes forever to approve
