### ISSUE TITLE
Selecting all in highlighted notes copied Anki box as well

### ISSUE THREAD

**Issue by samuelcwl** [burtonator/polar-bookshelf#923]
**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

https://opencollective.com/polar-bookshelf

**Is your feature request related to a problem? Please describe.**

When I'm creating Clozes using the Annotation panel, I'll double click on the sentence to select the entire sentence, CMD+C to copy and paste it in the Cloze box. The result is as follows:

<img width="309" alt="Screen Shot 2019-05-04 at 11 54 28 PM" src="https://user-images.githubusercontent.com/16283396/57188163-fd603a00-6ec7-11e9-94a2-acdd56ae0442.png">

It slows down my workflow a ton as I have to carefully select with my mouse, copy and paste it into the Anki box.

**Describe the solution you'd like**

Possible to limit the select all to the text? Maybe create another div wrapper or put a div whitespace between the two divs? (Haven't looked at the code so I might be totally wrong here)

**Describe alternatives you've considered**

**Additional context**

**Comment by burtonator** [comment]
What platform.  I can't duplicate this on my machine.  What version?

**Comment by samuelcwl** [comment]
Version 1.19.0, OSX 10.13.6

**Comment by burtonator** [comment]
yeah.. very weird.  I have a partial work around to get rid of the red color but can't get rid of the comment box.

**Comment by burtonator** [comment]
Yeah.. a div parent and a whitespace div fixed it and prevents the copy from going nuts.  Will be fixed in 1.19.3.

**Comment by samuelcwl** [comment]
Perfect, appreciate it - thanks!
