### ISSUE TITLE
Customizable Key-bindings?

### ISSUE THREAD

**Issue by samuelcwl** [burtonator/polar-bookshelf#924]
**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

https://opencollective.com/polar-bookshelf

**Is your feature request related to a problem? Please describe.**

Currently the hotkey for creating clozes is CTRL + SHIFT + C. Would it be possible to options to change it to CMD + SHIFT + C? This is the default Anki keybinding for OSX so was wondering if there could be any way to switch up the keybindings.

This could extend to the other default keybindings for Polar as well.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by burtonator** [comment]
It probably will be a while before we support customizable key bindings.  We're planning on improving them though. 

One issue is sync so we have to keep all this supported when you use the cloud , not just local, and we don't have a pref sync system yet.  

Will investigate in the future though.
