### ISSUE TITLE
Polar UI has gotten a bit slow

### ISSUE THREAD

**Issue by burtonator** [burtonator/polar-bookshelf#925]
I think we can improve this by using shouldComponentUpdate and easily make this much faster.

This should go into 1.19.1

**Comment by burtonator** [comment]
Also, measure the duration of the event handler **before and after** so that I can know for certain that it's faster.  There aren't many components that need updating though so should be somewhat straight forward.

Maybe 5-10x components need to become "cell" components.

**Comment by Rumata888** [comment]
Don't know if it's related, but creating flashcards becomes extremely slow after a while. Even pasting in the box lags.

**Comment by burtonator** [comment]
interesting.. might be related.. how much of a lag?

It is in fact O(N) as I didn't realize that react is silly about doing repaints but I'm working on fixing that.

**Comment by burtonator** [comment]
it shouldn't be THAT slow.. meaning it should be < 200-500ms ... if it's slower than that this might be another issue.

**Comment by Rumata888** [comment]
It becomes really slow after a while. Even with the annotation bar closed. I have created about 200 anki cards and around that many annotations.

**Comment by burtonator** [comment]
@Rumata888 I think I've just duplicated this bug on my end and this is a separate issue.  At least I can verify that it hits me and can work on a work around.

**Comment by burtonator** [comment]
@Rumata888 FYI have a fix for this.. might not make ti into 1.19 but probably 1.19.1... not ssure yet.

**Comment by Rumata888** [comment]
It's a pity. Makes polar almost unusable at times. Just out of curiosity, what was it?

**Comment by burtonator** [comment]
it will make it into 1.19... a few days away.

We weren't probably removing event listeners and they were stacking up.  It was about N^2 btw.. fixed now though.

**Comment by Rumata888** [comment]
Sounds great.
