### ISSUE TITLE
Consider switching to pspdfkit

### ISSUE THREAD

**Issue by jdlongman** [burtonator/polar-bookshelf#959]
As can be seen from the following demo: https://web-examples.pspdfkit.com/custom, this pdf renderer is leagues ahead of pdf.js in terms of speed etc. It has also already implemented the kind of highlighting and text selection necessary in Polar.

It may be a lot faster just to switch to this than to deal with the limitations of pdf.js.

**Comment by burtonator** [comment]
Can't... it's proprietary software and not compatible with our license.

**Comment by burtonator** [comment]
but yeah.. the text selection is way better but I'm hoping the recent updates to pdfjs fix this.
