### ISSUE TITLE
Comments are deleted when the color of an annotation is changed.

### ISSUE THREAD

**Issue by cjsmooth** [burtonator/polar-bookshelf#963]
**Describe the bug**
If I change the color of an annotation on the annotation bar, any comments attached to that annotation disappear.

**To Reproduce**
1. Create an annotation
2. Go to the annotation bar
3. Create a comment on that annotation
4. Change the color of that annotation

**Expected behavior**
I assume that changing the color of annotation is not intended to delete the associated comments.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 1.19.2

**Comment by burtonator** [comment]
you're right.. Try to get on 1.19.4 but this shouldn't happen.

Note that the data is still on disk.. just not updated in the UI.. but that still shouldn't happen.

**Comment by burtonator** [comment]
I think this is happening because we don't re-build the children...
