### ISSUE TITLE
Changing highlight color deletes comments attached to the highlight

### ISSUE THREAD

**Issue by b-camacho** [burtonator/polar-bookshelf#979]
Description:
Comments can be added to annotations. If the color of the annotation is changed after a comment was added, the comment appears to be permanently deleted. The deleted comments were not visible in .md/.json dumps. Reverting to the original color is not possible through the UI, although I do not think it would help.

1. Open a pdf in Polar Desktop.
2. Select some text.
3. Choose an annotation color (red, yellow or green).
4. After the new annotation appears in the left sidebar, click `Create comment`.
5. Write some text in the box, click `Comment`.
6. Click on the color square in the bottom right corner of the annotation.
7. Choose any color.

**Expected behavior**
The color of the annotation should change, but all the comments attached to the annotation should persist.

**Screenshots**
Before changing the color:
![2019-05-17-223426_951x189_scrot](https://user-images.githubusercontent.com/12277070/57957677-fa683f00-78f4-11e9-8901-9a13fd8040ad.png)
After changing the color:
![2019-05-17-223449_951x105_scrot](https://user-images.githubusercontent.com/12277070/57957685-09e78800-78f5-11e9-93e6-a31ba53af537.png)

**Desktop (please complete the following information):**
 - OS: Linux - Arch 5.0.13
 - Browser: n/a
 - Version: 1.19.5 (installed through snapd)

**Comment by burtonator** [comment]
Thanks. This is fixed in 1.19.6 which went out this morning. If you find that this isn't fixxed for you please feel free to reopen this bug or create another one.
