### ISSUE TITLE
Progress isn't captured

### ISSUE THREAD

**Issue by jbwhit** [burtonator/polar-bookshelf#987]
**Describe the bug**
I read a full journal article within the Polar Bookshelf. Highlighted a few notes, and when I finished I closed the article. The main page has it that I've still made no progress on reading this article (when it should be that I completed it). 

**To Reproduce**
1. Read an article.
2. Close article.
3. View Bookshelf and note that progress hasn't been recorded.

**Expected behavior**
Progress to be recorded (or somehow directly updatable).

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.4 (18E226)
 - (Tried with both desktop and within chrome) -- same problem.
 - Polar version:  1.19.6

**Comment by burtonator** [comment]
pagemarks are manual not automatic but we're thinking of adding an automatic mode though.
